#!/usr/bin/env bash
###############################################################################
# macosapps
#
# Configure and set various preferences for non-default macOS applications,
# including developer and third-party applications.
###############################################################################

###############################################################################
# Platform Check
###############################################################################

if [[ ! "$OSTYPE" =~ ^darwin ]]
then
  printf "script/configure/macos_apps is only supported on macOS.\nSkipping...\n"
  exit 0
fi

###############################################################################
# Google Chrome, etc
###############################################################################

# Check for updates once a week.
# More information:
# http://apple.stackexchange.com/a/208015
# Revert command:
# defaults write com.google.Keystone.Agent checkInterval 18000
defaults write com.google.Keystone.Agent checkInterval 604800

###############################################################################
# iTerm2
###############################################################################

# Set hidden AlternateMouseScroll preference for better scrolling in command
# line programs.
# More information:
# - https://filippo.io/native-scrolling-and-iterm2/
# - https://code.google.com/p/iterm2/issues/detail?id=2311
# - http://stackoverflow.com/questions/14437979/iterm2-scroll-less-output-with-mouse
# Revert command:
# defaults delete com.googlecode.iterm2 AlternateMouseScroll
defaults write com.googlecode.iterm2 AlternateMouseScroll -bool true
