#!/usr/bin/env bash
###############################################################################
# osx.sh
#
# Configure and set various preferences for OS X and default Apple applications
###############################################################################

###############################################################################
# Platform Check
###############################################################################

if [[ ! "$OSTYPE" =~ ^darwin ]]
then
  printf "osx.sh is only supported on OS X.\nSkipping...\n"
  exit 0
fi

# _macos_version()
#
# Usage:
#   _macos_version
#
# Description:
#   Return the current macOS version, e.g., '11' when running 10.11.
_macos_version() {
  sw_vers -productVersion | awk -F. '{print $2}'
}

# _is_mavericks
#
# Usage:
#   _is_mavericks
#
# Description:
#   Returns true if the current system is running OS X 10.9 Mavericks.
_is_mavericks() {
  [[ "$(_macos_version)" == "9" ]]
}

# _is_yosemite
#
# Usage:
#   _is_yosemite
#
# Description:
#   Returns true if the current system is running OS X 10.10 Yosemite.
_is_yosemite() {
  [[ "$(_macos_version)" == "10" ]]
}

# _is_el_capitan
#
# Usage:
#   _is_el_capitan
#
# Description:
#   Returns true if the current system is running OS X 10.11 El Capitan.
_is_el_capitan() {
  [[ "$(_macos_version)" == "11" ]]
}

###############################################################################
# UX
###############################################################################

# Reduce Transparency.
# UI location:
#   System Preferences -> Accessibility -> Display -> Reduce Transparency
# Description: Reportedly minimizes performances issues like lagging
# animations due to windowserver getting bloated.
#
# Note: Requires restart.
#
# Revert command:
# defaults write com.apple.universalaccess reduceTransparency 0
if _is_yosemite
then
  defaults write com.apple.universalaccess reduceTransparency 1
else
  defaults write com.apple.universalaccess reduceTransparency 0
fi

###############################################################################
# Disk Utility
###############################################################################

# Enable the debug menu.
#
# Revert command:
# defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool false
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true

# Enable advanced options
#
# TODO: this was already set to `"advanced-image-options" = 1`, so the actual
# default will need to be determined.
defaults write com.apple.DiskUtility advanced-image-options -bool true

###############################################################################
# Finder
###############################################################################

# Finder: allow text selection in Quick Look.
#
# Revert command:
# defaults delete com.apple.finder QLEnableTextSelection
defaults write com.apple.finder QLEnableTextSelection -bool true

###############################################################################
# Address Book, Dashboard, iCal, TextEdit
###############################################################################

# Enable the debug menu in Address Book.
#
# Revert command:
# defaults delete com.apple.addressbook ABShowDebugMenu
defaults write com.apple.addressbook ABShowDebugMenu -bool true

# Enable Dashboard dev mode (allows keeping widgets on the desktop)
defaults write com.apple.dashboard devmode -bool true

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0
# Open and save files as UTF-8 in TextEdit
#
# Revert commands:
# defaults delete com.apple.TextEdit PlainTextEncoding
# defaults delete com.apple.TextEdit PlainTextEncodingForWrite
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

###############################################################################
# Mac App Store
###############################################################################

# Enable the WebKit Developer Tools in the Mac App Store
#
# Revert command:
# defaults delete com.apple.appstore WebKitDeveloperExtras
defaults write com.apple.appstore WebKitDeveloperExtras -bool true

# Enable Debug Menu in the Mac App Store
#
# Revert command:
# defaults delete com.apple.appstore ShowDebugMenu
defaults write com.apple.appstore ShowDebugMenu -bool true

###############################################################################
# Kill affected applications
###############################################################################

for app in "Address Book" "Disk Utility" "Finder"
do
	killall "${app}" > /dev/null 2>&1
done
echo "Done. Note that some of these changes require a logout/restart to take effect."
