###############################################################################
# ssh.sh
#
# SSH shell settings.
#
# See also: $HOME/.ssh
###############################################################################

# generate_ssh_config
#
# Usage:
#   generate_ssh_config
#
# Description:
#   Combine the contents of `.ssh/config.d` and `.ssh/default.sshconfig` into
#   a `.ssh/config` file that is then used as the config file for `ssh`.
#
#   This function can be called directly in order to manually generate a new
#   `.ssh/config` file, since commands other than `ssh` will use the
#   generated configuration.
generate_ssh_config() {
  printf "\
###############################################################################
# .ssh/config
#
# This is a generated ssh config file that is created by a wrapper around the
# \`ssh\` command in order to combine multiple ssh config files.
#
# WARNING: DO NOT EDIT THIS FILE DIRECTLY. IT WILL BE OVERWRITTEN.
#
# More information: ~/.shared_rc.d/ssh.sh
###############################################################################
" > ~/.ssh/config-all
  cat ~/.ssh/config.d/* >> ~/.ssh/config
  cat ~/.ssh/default.sshconfig >> ~/.ssh/config
}

# Alias `ssh` to a function that combines the contents of `.ssh/config.d` and
# `.ssh/config` into a `.ssh/config-all` file that is then used as the config
# file for `ssh`.
#
# More information: http://superuser.com/q/247564
_SSH_CMD="$(which ssh)"
ssh() {
  generate_ssh_config
  "$_SSH_CMD" "$@"
}
