#!/usr/bin/env bash
################################################################################
# Programs
###############################################################################

###############################################################################
# Platform Check
###############################################################################

# Skip unless OS X
if [[ ! "$OSTYPE" =~ ^darwin ]]; then
  printf "brew-programs is only supported on OS X\nSkipping...\n"
  exit 0
fi

###############################################################################
# Programs
###############################################################################

# Ack
#
# Ack is a tool like grep, optimized for programmers
#
# http://beyondgrep.com/
brew install ack

# GNU Aspell
#
# A Free and Open Source spell checker
#
# http://aspell.net/
brew install aspell --with-lang-en

# Autoconf
#
# Autoconf is an extensible package of M4 macros that produce shell scripts to
# automatically configure software source code packages. These scripts can
# adapt the packages to many kinds of UNIX-like systems without manual user
# intervention.
#
# http://www.gnu.org/software/autoconf/
brew install autoconf

# bup
#
# Very efficient backup system based on the git packfile format, providing
# fast incremental saves and global deduplication (among and within files,
# including virtual machine images).
#
# Options:
#   --with-pandoc
#     build and install the manpage (depends on pandoc)
#   --run-tests
#     Run unit tests after compilation
#
# https://bup.github.io/
# https://github.com/bup/bup
brew install bup --with-pandoc --run-tests

# calc
#
# Calc is an interactive calculator which provides for easy large numeric
# calculations, but which also can be easily programmed for difficult or long
# calculations. It can accept a command line argument, in which case it
# executes that single command and exits. Otherwise, it enters interactive
# mode. In this mode, it accepts commands one at a time, processes them, and
# displays the answers. In the simplest case, commands are simply expressions
# which are evaluated.
#
# http://www.isthe.com/chongo/tech/comp/calc/
brew install calc

# checkbashisms - check for bashisms in /bin/sh scripts
#
# checkbashisms,  based  on  one  of  the checks from the lintian system,
# performs basic  checks  on  /bin/sh  shell  scripts  for  the  possible
# presence  of  bashisms.  It takes the names of the shell scripts on the
# command line, and outputs warnings if possible bashisms are detected.
#
# http://manpages.ubuntu.com/manpages/natty/man1/checkbashisms.1.html
brew install checkbashisms

# clib(1) - C package manager-ish
#
# Package manager for the C programming language.
#
# https://github.com/clibs/clib
brew install clib

# cmatrix
#
# 'The Matrix'-inspired scrolling lines.
#
# http://www.asty.org/cmatrix/
brew install cmatrix

# composer
#
# Dependency Manager for PHP
#
# http://getcomposer.org
brew install composer

# coq
#
# Coq is a formal proof management system. It provides a formal language to
# write mathematical definitions, executable algorithms and theorems together
# with an environment for semi-interactive development of machine-checked
# proofs. Typical applications include the certification of properties of
# programming languages (e.g. the CompCert compiler certification project, or
# the Bedrock verified low-level programming library), the formalization of
# mathematics (e.g. the full formalization of the Feit-Thompson theorem or
# homotopy type theory) and teaching.
#
# https://coq.inria.fr/
brew install coq

# ctags
#
# Ctags is a programming tool that generates an index (or tag) file of names
# found in source and header files of various programming languages. Depending
# on the language, functions, variables, class members, macros and so on may be
# indexed. These tags allow definitions to be quickly and easily located by a
# text editor or other utility. Alternatively, there is also an output mode
# that generates a cross reference file, listing information about various
# names found in a set of language files in human-readable form.
#
# http://ctags.sourceforge.net/
brew install ctags

# dash
#
# DASH is a POSIX-compliant implementation of /bin/sh that aims to be as small
# as possible. It does this without sacrificing speed where possible. In fact,
# it is significantly faster than bash (the GNU Bourne-Again SHell) for most
# tasks.
#
# http://gondor.apana.org.au/~herbert/dash/
brew install dash

# djvu2pdf
#
# A small tool to convert Djvu files to PDF files.
#
# http://0x2a.at/s/projects/djvu2pdf
#
# See also:
# http://djvu.sourceforge.net/
# https://en.wikipedia.org/wiki/DjVu
brew install djvu2pdf

# Docker Machine
#
# Machine management for a container-centric world
#
# Machine makes it really easy to create Docker hosts on your computer, on
# cloud providers and inside your own data center. It creates servers,
# installs Docker on them, then configures the Docker client to talk to them.
#
# https://docs.docker.com/machine/
# https://github.com/docker/machine
brew install docker-machine --devel

# Docker Swarm
#
# Swarm: a Docker-native clustering system
#
# Docker Swarm is native clustering for Docker. It turns a pool of Docker hosts
# into a single, virtual host.
#
# https://github.com/docker/swarm
brew install docker-swarm --devel

# dots
#
# A configuration tool and framework for your laptop or desktop
#
# https://github.com/alphabetum/dots
brew install dots

# Dwarf Fortress
#
# Dwarf Fortress is a part construction and management simulation, part
# roguelike, freeware indie video game.
#
# http://www.bay12games.com/dwarves/
brew install dwarf-fortress

# ELinks - Full-Featured Text WWW Browser
#
# ELinks is an advanced and well-established feature-rich text mode web
# (HTTP/FTP/..) browser.
#
# http://elinks.or.cz/
brew install elinks

# Elixir
#
# Elixir is a dynamic, functional language designed for building scalable and
# maintainable applications.
#
# http://elixir-lang.org/
brew install elixir

# EncFS - an Encrypted Filesystem
#
# EncFS provides an encrypted filesystem in user-space. It runs with regular
# user permissions using the FUSE library.
#
# https://github.com/vgough/encfs
# https://vgough.github.io/encfs/
brew install encfs

# Erlang
#
# Erlang is a programming language used to build massively scalable soft
# real-time systems with requirements on high availability. Some of its uses
# are in telecoms, banking, e-commerce, computer telephony and instant
# messaging. Erlang's runtime system has built-in support for concurrency,
# distribution and fault tolerance.
#
# http://www.erlang.org/
brew install erlang

# Exiv2
#
# Image metadata library and tools
#
# http://www.exiv2.org
brew install exiv2

# FFmpeg
#
# A complete, cross-platform solution to record, convert and stream audio and
# video.
#
# https://ffmpeg.org/
brew install ffmpeg

# forego
#
# Foreman (Manage Procfile-based applications) in Go.
#
# https://github.com/ddollar/foreman
# https://github.com/ddollar/forego
brew install forego

# Flow
#
# Flow is a static type checker, designed to find type errors in JavaScript
# programs.
#
# http://flowtype.org/
brew install flow

# git
#
# Git is a free and open source distributed version control system designed to
# handle everything from small to very large projects with speed and efficiency
#
# http://git-scm.com
brew install git

# git-annex
#
# git-annex allows managing files with git, without checking the file contents
# into git. While that may seem paradoxical, it is useful when dealing with
# files larger than git can currently easily handle, whether due to limitations
# in memory, time, or disk space.
#
# https://git-annex.branchable.com/
brew install git-annex

# git-extras
#
# GIT utilities -- repo summary, repl, changelog population, author commit
# percentages and more.
#
# https://github.com/tj/git-extras
brew install git-extras

# go / golang
#
# Go is an open source programming language that makes it easy to build simple,
# reliable, and efficient software.
#
# https://golang.org/
# https://github.com/golang/go
brew install go

# GnuPG
#
# GnuPG is a complete and free implementation of the OpenPGP standard as
# defined by RFC4880 (also known as PGP). GnuPG allows to encrypt and sign
# your data and communication, features a versatile key management system as
# well as access modules for all kinds of public key directories. GnuPG, also
# known as GPG, is a command line tool with features for easy integration with
# other applications. A wealth of frontend applications and libraries are
# available.
#
# https://www.gnupg.org/
brew install gpg
# GnuPG - Version 2
#
# Version 2 of GnuPG also provides support for S/MIME and Secure Shell (ssh).
#
# https://www.gnupg.org/
brew install gnupg2
# Prefer gnupg2 gpg2 binary. Another version is installed with the gpgtools
# cask, but using the gpg2 formula's version shouldn't have any impact on the
# functioning of the other tools.
brew link --overwrite gnupg2

# GNU Grep
#
# Grep searches one or more input files for lines containing a match to a
# specified pattern. By default, Grep outputs the matching lines.
#
# https://www.gnu.org/software/grep/
#
# NOTES:
#   - An older version of grep is included by default in OS X
#   - this version is installed with a 'g' prefex and is called via `ggrep`
brew install homebrew/dupes/grep

# heroku
#
# Heroku client - CLI tool for creating and managing Heroku apps
#
# https://toolbelt.heroku.com/standalone
# https://github.com/heroku/heroku
brew install heroku

# htop (htop-osx)
#
# htop, an interactive process viewer.
#
# https://github.com/max-horvath/htop-osx
brew install htop

# hub
#
# hub is a command-line wrapper for git that makes you better at GitHub.
#
# http://hub.github.com/
#
# NOTE: installing HEAD in order to get the golang rewrite 2.0.0 pre-release.
brew install --HEAD hub

# iftop
#
# iftop does for network usage what top(1) does for CPU usage. It listens to
# network traffic on a named interface and displays a table of current
# bandwidth usage by pairs of hosts. Handy for answering the question "why is
# our ADSL link so slow?".
#
# http://www.ex-parrot.com/~pdw/iftop/
brew install iftop

# ImageMagick
#
# ImageMagick® is a software suite to create, edit, compose, or convert bitmap
# images. It can read and write images in a variety of formats (over 100)
# including DPX, EXR, GIF, JPEG, JPEG-2000, PDF, PNG, Postscript, SVG, and
# TIFF. Use ImageMagick to resize, flip, mirror, rotate, distort, shear and
# transform images, adjust image colors, apply various special effects, or draw
# text, lines, polygons, ellipses and Bézier curves.
#
# http://www.imagemagick.org
#
# Build notes:
#
# --with-webp - build with support for the webp image format:
#
# https://developers.google.com/speed/webp/?csw=1
brew install imagemagick --with-webp

# io
#
# Io is a prototype-based programming language inspired by Smalltalk (all
# values are objects, all messages are dynamic), Self (prototype-based),
# NewtonScript (differential inheritance), Act1 (actors and futures for
# concurrency), LISP (code is a runtime inspectable/modifiable tree) and Lua
# (small, embeddable).
#
# NOTE: including --without-addons to avoid installation errors.
#
# http://iolanguage.org/
brew install io --without-addons

# irssi
#
#Irssi is a terminal based IRC client for UNIX systems. It also supports SILC
# and ICB protocols via plugins.
#
# http://irssi.org/
brew install irssi

# ispell
#
# International Ispell is an interactive spell-checking program for Unix which
# supports a large number of European languages. An emacs interface is
# available as well as the standard command-line mode.
#
# http://lasr.cs.ucla.edu/geoff/ispell.html
brew install ispell

# Leiningen
#
# Automate Clojure projects without setting your hair on fire.
#
# https://github.com/technomancy/leiningen
brew install leiningen

# lesspipe
#
# lesspipe.sh is an input filter for the pager less as described in less's man
# page.
#
# http://www-zeuthen.desy.de/~friebel/unix/lesspipe.html
brew install lesspipe

# libcello
#
# Higher level programming in C
#
# http://libcello.org/
brew install libcello

# libgit2
#
# libgit2 is a portable, pure C implementation of the Git core methods provided
# as a re-entrant linkable library with a solid API, allowing you to write
# native speed custom Git applications in any language which supports C
# bindings.
#
# https://libgit2.github.com/
brew install libgit2

# Lua
#
# Lua is a powerful, fast, lightweight, embeddable scripting language.
#
# http://www.lua.org/
brew install lua

# LuaRocks
#
# Package management for Lua modules. LuaRocks is a deployment and management
# system for Lua modules and allows you to install Lua modules as
# self-contained packages called "rocks", which also contain version dependency
# information.
#
# http://luarocks.org
brew install luarocks

# Lynx
#
# Lynx is a fully-featured World Wide Web (WWW) client for users running
# cursor-addressable, character-cell display devices such as vt100 terminals
#
# http://lynx.isc.org/release/
brew install lynx

# matplotlib
#
# matplotlib is a python 2D plotting library which produces publication
# quality figures in a variety of hardcopy formats and interactive environments
# across platforms. matplotlib can be used in python scripts, the python and
# ipython shell (ala MATLAB®* or Mathematica®†), web application servers, and
# six graphical user interface toolkits.
#
# http://matplotlib.org
brew install homebrew/python/matplotlib

# Memcached
#
# Free & open source, high-performance, distributed memory object caching
# system, generic in nature, but intended for use in speeding up dynamic web
# applications by alleviating database load.
#
# http://memcached.org/
brew install memcached

# Mercurial
#
# Mercurial is a free, distributed source control management tool.
#
# http://mercurial.selenic.com/
brew install mercurial

# Midnight Commander
#
# GNU Midnight Commander is a visual file manager
#
# https://www.midnight-commander.org/
# http://en.wikipedia.org/wiki/Midnight_Commander
brew install midnight-commander

# MIT/GNU Scheme
#
# MIT/GNU Scheme is an implementation of the Scheme programming language,
# providing an interpreter, compiler, source-code debugger, integrated
# Emacs-like editor, and a large runtime library.
#
# http://www.gnu.org/software/mit-scheme/
brew install mit-scheme

# msgpack
#
# MessagePack is an efficient binary serialization format. It lets you exchange
# data among multiple languages like JSON. But it's faster and smaller. Small
# integers are encoded into a single byte, and typical short strings require
# only one extra byte in addition to the strings themselves.
#
# http://msgpack.org/
brew install msgpack

# MongoDB
#
# MongoDB (from humongous) is a cross-platform document-oriented database.
# Classified as a NoSQL database, MongoDB eschews the traditional table-based
# relational database structure in favor of JSON-like documents with dynamic
# schemas (MongoDB calls the format BSON).
#
# https://www.mongodb.org/
brew install mongodb

# Mosh / mobile-shell
#
# Remote terminal application that allows roaming, supports intermittent
# connectivity, and provides intelligent local echo and line editing of user
# keystrokes.
#
# Mosh is a replacement for SSH. It's more robust and responsive, especially
# over Wi-Fi, cellular, and long-distance links.
#
# https://mosh.mit.edu/
brew install mobile-shell

# Mono
#
# Cross platform, open source .NET framework
#
# http://www.mono-project.com/
brew install mono
# mono's makecert conflicts with czmq's. Prefer mono's for now.
brew link --overwrite mono

# MOST
#
# MOST is a powerful paging program for Unix, VMS, MSDOS, and win32 systems.
# Unlike other well-known paging programs most supports multiple windows and
# can scroll left and right.
#
# http://www.jedsoft.org/most/
brew install most

# mutt
#
# Mutt is a small but very powerful text-based mail client for Unix operating
# systems.
#
# http://www.mutt.org/
#
# Options:
#   --with-trash-patch
#     Apply trash folder patch
brew install mutt --with-trash-patch

# neovim
#
# http://neovim.org/
# https://github.com/neovim/neovim
# https://github.com/neovim/neovim/wiki/Installing
#
# Note that this is a tapped formula from the neovim/homebrew-neovim tap.
brew install --HEAD neovim/neovim/neovim

# ngrep - network grep
#
# ngrep strives to provide most of GNU grep's common features, applying them to
# the network layer. ngrep is a pcap-aware tool that will allow you to specify
# extended regular or hexadecimal expressions to match against data payloads of
# packets.
#
# http://ngrep.sourceforge.net/
brew install ngrep

# nim / nimrod
#
# Nim (formerly known as "Nimrod") is a statically typed, imperative
# programming language that tries to give the programmer ultimate power without
# compromises on runtime efficiency. This means it focuses on compile-time
# mechanisms in all their various forms.
#
# http://nim-lang.org/
brew install nimrod --HEAD

# node.js
#
# Node.js® is a platform built on Chrome's JavaScript runtime. Node.js uses an
# event-driven, non-blocking I/O model
#
# https://nodejs.org/
#
# NOTE: also install npm
brew install node

# NSQ
#
# NSQ is a realtime distributed messaging platform designed to operate at
# scale, handling billions of messages per day.
#
# http://nsq.io/
# https://github.com/bitly/nsq
brew install nsq

# numpy
#
# NumPy is the fundamental package for scientific computing with Python. It
# contains among other things:
#
# - a powerful N-dimensional array object
# - sophisticated (broadcasting) functions
# - tools for integrating C/C++ and Fortran code
# - useful linear algebra, Fourier transform, and random number capabilities
#
# Besides its obvious scientific uses, NumPy can also be used as an efficient
# multi-dimensional container of generic data. Arbitrary data-types can be
# defined. This allows NumPy to seamlessly and speedily integrate with a wide
# variety of databases.
#
# http://www.numpy.org
brew install homebrew/python/numpy

# OCaml
#
# OCaml, originally known as Objective Caml, is the main implementation of the
# Caml programming language.
#
# http://ocaml.org
brew install ocaml

# OPAM - OCaml Package Manager
#
# OPAM is a source-based package manager for OCaml. It supports multiple
# simultaneous compiler installations, flexible package constraints, and a
# Git-friendly development workflow.
#
# https://opam.ocaml.org
brew install opam

# ori - A Secure Distributed File System
#
# Ori is a distributed file system built for offline operation and empowers the
# user with control over synchronization operations and conflict resolution.
# We provide history through light weight snapshots and allow users to verify
# the history has not been tampered with. Through the use of replication
# instances can be resilient and recover damaged data from other nodes.
#
# http://ori.scs.stanford.edu/
# https://bitbucket.org/orifs/ori/wiki/Home
brew install ori

# osxutils
#
# osxutils is a bundle of Mac OS X command line utilities that bring power over
# all sorts of Mac-specific information, settings and meta-data to the command
# line.
#
# https://github.com/vasi/osxutils
brew install osxutils

# p7zip
#
# A file archiver with a high compression ratio. p7zip is a port of 7za.exe for
#POSIX systems like Unix.
#
# http://p7zip.sourceforge.net/
brew install p7zip

# PacVim
#
# PacVim is a game that teaches you vim commands. You must move pacman (the
# green cursor) to highlight each word on the gameboard while avoiding the
# ghosts (in red).
#
# https://github.com/jmoon018/PacVim
brew install pacvim

# Pandoc
#
# Pandoc converts files from one markup format into another
#
#http://johnmacfarlane.net/pandoc/
brew install pandoc

# PHP 5.6
#
# PHP is a server-side scripting language designed for web development but also
# used as a general-purpose programming language.
#
# https://php.net
#
# Options:
#   --with-gpm
#     Build with gmp support. GNU Multiple Precision:
#     http://php.net/manual/en/book.gmp.php
brew install homebrew/php/php56 --with-gmp

# pidgin
#
# Pidgin is a chat program which lets you log in to accounts on multiple chat
# networks simultaneously. This means that you can be chatting with friends on
# MSN, talking to a friend on Google Talk, and sitting in a Yahoo chat room
# all at the same time.
#
# https://pidgin.im/
#
# Options:
#   --with-gsasl
#     Build with gsasl support
#
#     GNU SASL Library - Libgsasl
#
#     GNU SASL is an implementation of the Simple Authentication and Security
#     Layer framework and a few common SASL mechanisms. SASL is used by
#     network servers (e.g., IMAP, SMTP) to request authentication from
#     clients, and in clients to authenticate against servers.
#
#     http://www.gnu.org/software/gsasl/
#
#   --without-GUI
#     Build Finch instead of Pidgin
#
#     A text-based user interface for using libpurple.  This can be run from a
#     standard text console or from a terminal within X Windows.  It
#     uses ncurses and our homegrown gnt library for drawing windows
#     and text.
#
#     https://en.wikipedia.org/wiki/Finch_(software)
#     https://developer.pidgin.im/wiki/Using%20Finch
#     http://linux.die.net/man/1/finch
brew install pidgin --with-gsasl --without-GUI

# pigz
#
# A parallel implementation of gzip for modern multi-processor, multi-core
# machines
#
# http://www.zlib.net/pigz/
brew install pigz

# pow
#
# Pow is a zero-config Rack server for Mac OS X.
#
# http://pow.cx/
# https://github.com/basecamp/pow
brew install pow
# pow post-install
#
# Create the required host directories:
if [[ ! -d "$HOME/Library/Application Support/Pow/Hosts" ]]; then
  mkdir -p "$HOME/Library/Application Support/Pow/Hosts"
  if [[ ! -e "$HOME/.pow" ]]; then
    ln -s "$HOME/Library/Application Support/Pow/Hosts" "$HOME/.pow"
  fi
fi
# Setup and launch port 80 forwarding and launchd agents
if ! ( [[ -e "/Library/LaunchDaemons/cx.pow.firewall.plist" ]] || \
       [[ -e "/etc/resolver/dev" ]]
  ); then
  sudo pow --install-system
  sudo launchctl load -w "/Library/LaunchDaemons/cx.pow.firewall.plist"
fi
if [[ ! -e "$HOME/Library/LaunchAgents/cx.pow.powd.plist" ]]; then
  pow --install-local
  launchctl load -w "$HOME/Library/LaunchAgents/cx.pow.powd.plist"
fi

# pv - Pipe Viewer
#
# A terminal-based tool for monitoring the progress of data through a pipeline.
#
# http://www.ivarch.com/programs/pv.shtml
brew install pv

# python
#
# Python 2
#
# https://www.python.org
brew install python

# python3
#
# Python 3
#
# https://www.python.org
brew install python3

# R
#
# R is a free software environment for statistical computing and graphics.
#
# http://www.r-project.org/
#
# Options:
#   --with-openblas
#     Build with openblas support
#     http://www.openblas.net/
brew install r --with-openblas

# ranger
#
# ranger is a file manager with VI key bindings. It provides a minimalistic
# and nice curses interface with a view on the directory hierarchy. The
# secondary task of ranger is to psychically guess which program you want to
# use for opening particular files.
#
# http://ranger.nongnu.org/
brew install ranger

# rbenv
#
# Groom your app’s Ruby environment
#
# https://github.com/sstephenson/rbenv
brew install rbenv

# rename
#
# renames files according to modification rules specified on the command line.
#
# http://plasmasturm.org/code/rename
brew install rename

# Redis
#
# Redis is an open source, BSD licensed, advanced key-value cache and store. It
# is often referred to as a data structure server since keys can contain
# strings, hashes, lists, sets, sorted sets, bitmaps and hyperloglogs.
#
# http://redis.io/
brew install redis

# Rhino
#
# Rhino is an open-source implementation of JavaScript written entirely in
# Java.
#
# http://www.mozilla.org/rhino/
brew install rhino

# Riak
#
# Riak is an open source, distributed database.
#
# http://basho.com/riak/
brew install riak

# RingoJS
#
# Ringo is a CommonJS-based JavaScript runtime written in Java and based on the
# Mozilla Rhino JavaScript engine.
#
# http://ringojs.org
brew install ringojs

# sbt
#
# The interactive build tool
#
# Use Scala to define your tasks. Then run them in parallel from the shell.
#
# http://www.scala-sbt.org/
brew install sbt

# Scala
#
# Scala is an object-functional programming language for general software
# applications.
#
# http://www.scala-lang.org/
brew install scala

# scipy
#
# SciPy (pronounced “Sigh Pie”) is a Python-based ecosystem of open-source
# software for mathematics, science, and engineering.
#
# http://www.scipy.org
brew install homebrew/python/scipy

# GNU Screen
#
# Screen is a full-screen window manager that multiplexes a physical terminal
# between several processes, typically interactive shells.
#
# https://www.gnu.org/software/screen
#
# NOTE: An older BSD version is included with OS X, but this newer GNU
# version supercedes it.
brew install homebrew/dupes/screen

# scsh
#
# Scsh is a POSIX API layered on top of the Scheme programming language in a
# manner to make the most of Scheme's capability for scripting. It is limited
# to 32-bit platforms but there is a development version against the latest
# scheme48 that works in 64-bit mode.
#
# https://en.wikipedia.org/wiki/Scsh
# http://scsh.net/docu/html/man.html
brew install scsh

# ShellCheck
#
# Automatically detects problems with sh/bash scripts and commands
#
# http://www.shellcheck.net/
brew install shellcheck

# Siege
#
# Siege is an http load testing and benchmarking utility.
#
# http://www.joedog.org/index/siege-home
brew install siege

# Sphinx
#
# Sphinx is a free software/open source Fulltext search engine designed to
# provide full-text search functionality to client applications.
#
# http://www.sphinxsearch.com
brew install sphinx

# GNU Stow
#
# GNU Stow is a symlink farm manager which takes distinct packages of software
# and/or data located in separate directories on the filesystem, and makes
# them appear to be installed in the same place.
#
# http://www.gnu.org/software/stow/
brew install stow

# syncthing
#
# Open Source Continuous File Synchronization
#
# http://syncthing.net
# https://github.com/syncthing/syncthing
brew install syncthing
# syncthing post-install
#
# Setup and launch launchd agent
if [[ ! -e "$HOME/Library/LaunchAgents/homebrew.mxcl.syncthing.plist" ]]; then
  ln -sfv /usr/local/opt/syncthing/*.plist "$HOME/Library/LaunchAgents"
  launchctl load "$HOME/Library/LaunchAgents/homebrew.mxcl.syncthing.plist"
fi


# tag
#
# A command line tool to manipulate tags on Mavericks files, and to query for
# files with those tags.
#
# https://github.com/jdberry/tag
brew install tag

# tree
#
# Tree is a recursive directory listing command that produces a depth indented
# listing of files.
#
# http://mama.indstate.edu/users/ice/tree/
brew install tree

# Tig - text-mode interface for Git
#
# Tig is an ncurses-based text-mode interface for git. It functions mainly as a
# Git repository browser, but can also assist in staging changes for commit at
# chunk level and act as a pager for output from various Git commands.
#
# http://jonas.nitro.dk/tig/
brew install tig

# tmux
#
# tmux is a terminal multiplexer. It lets you switch easily between several
# programs in one terminal, detach them (they keep running in the background)
# and reattach them to a different terminal.
#
# http://tmux.sourceforge.net
brew install tmux

# tmuxinator
#
# Manage complex tmux sessions easily
#
# https://github.com/tmuxinator/tmuxinator
brew install tmuxinator-completion

# The Silver Searcher
#
# A code-searching tool similar to ack, but faster.
#
# https://github.com/ggreer/the_silver_searcher
# http://geoff.greer.fm/ag/
#
# NOTE: command name is `ag`
brew install the_silver_searcher

# Valgrind
#
# Valgrind is an instrumentation framework for building dynamic analysis tools.
# There are Valgrind tools that can automatically detect many memory management
# and threading bugs, and profile your programs in detail.
#
# http://valgrind.org/
#
# NOTE: installing head version for yosemite support.
brew install --HEAD valgrind

# vim
#
# Vim (a contraction of Vi IMproved) is a clone of Bill Joy's vi editor for
# Unix. It was written by Bram Moolenaar based on source for a port of the
# Stevie editor to the Amiga and first released publicly in 1991. Vim is
# designed for use both from a command-line interface and as a standalone
# application in a graphical user interface.
#
# http://www.vim.org/
brew install vim --override-system-vi
# vim - MacVim
#
# The text editor Vim for Mac OS X.
#
# http://code.google.com/p/macvim/
brew install macvim

# w3m
#
# w3m is a text-based web browser as well as a pager like `more' or `less'.
# With w3m you can browse web pages through a terminal emulator window (xterm,
# rxvt or something like that). Moreover, w3m can be used as a text formatting
# tool which typesets HTML into plain text.
#
# http://w3m.sourceforge.net/
brew install w3m

# Wcalc
#
# Wcalc is a very capable calculator. It supports abitrary precision, has
# standard functions (sin, asin, and sinh for example, in either radians or
# degrees), many pre-defined constants (pi, e, c, etc.), support for using
# variables, "active" variables, a command history, hex/octal/binary input
# and output, unit conversions, embedded comments, and an expandable
# expression entry field. It evaluates expressions using the standard order
# of operations.
#
# http://w-calc.sourceforge.net
brew install w-calc

# webkit2png
#
# webkit2png is a command line tool that creates screenshots of webpages
#
# http://www.paulhammond.org/webkit2png/
brew install webkit2png

# WeeChat
#
# WeeChat is a fast, light and extensible chat client.
#
# https://weechat.org/
brew install weechat

# wget
#
# GNU Wget is a free software package for retrieving files using HTTP, HTTPS
# and FTP, the most widely-used Internet protocols.
#
# https://www.gnu.org/software/wget/
#
# NOTE: including support of IRIs, Internationalized Resource Identifiers,
# which are similar to URI, but allow unicode charaters to be used.
brew install wget --with-iri

# Wine
#
# Run Windows applications on Linux, BSD, Solaris and Mac OS X.
#
# http://winehq.org/
brew install wine

# Winetricks
#
# Winetricks is an easy way to work around problems in Wine.
#
# http://code.google.com/p/winetricks/
brew install winetricks

# zeromq
#
# ØMQ (also spelled ZeroMQ, 0MQ or ZMQ) is a high-performance asynchronous
# messaging library aimed at use in scalable distributed or concurrent
# applications. It provides a message queue, but unlike message-oriented
# middleware, a ØMQ system can run without a dedicated message broker. The
# library is designed to have a familiar socket-style API.
#
# http://zeromq.org/
brew install zeromq

# Zopfli
#
# Zopfli Compression Algorithm is a new zlib (gzip, deflate) compatible
# compressor. This compressor takes more time (~100x slower), but compresses
# around 5% better than zlib and better than any other zlib-compatible
# compressor.
#
# https://code.google.com/p/zopfli/
brew install zopfli

