#!/usr/bin/env bash
################################################################################
# brew-tools
###############################################################################

###############################################################################
# Platform Check
###############################################################################

# Skip unless OS X
if [[ ! "$OSTYPE" =~ ^darwin ]]
then
  printf "brew-tools is only supported on OS X\nSkipping...\n"
  exit 0
fi

###############################################################################
# Helpers
###############################################################################

# _homebrew_formula_is_installed()
#
# Test whether a given homebrew formula is installed on the system.
#
# Usage:
#   _homebrew_formula_is_installed "formula_name"
_homebrew_formula_is_installed() {
  local _formula_name="$1"
  [[ -n "$(brew list "$_formula_name" 2>/dev/null)" ]]
}

###############################################################################
# Programs
###############################################################################

# AAlib
#
# AAlib is a software library which allows applications to automatically
# convert still and moving images into ASCII art.
#
# http://aa-project.sourceforge.net/aalib/
# https://en.wikipedia.org/wiki/AAlib
brew install aalib

# Ack
#
# Ack is a tool like grep, optimized for programmers
#
# http://beyondgrep.com/
brew install ack

# Ansible
#
# Ansible is a radically simple IT automation platform that makes your
# applications and systems easier to deploy. Avoid writing scripts or custom
# code to deploy and update your applications— automate in a language that
# approaches plain English, using SSH, with no agents to install on remote
# systems.
#
# http://www.ansible.com/home
# https://github.com/ansible/ansible
#
# NOTE: the recommended way to install ansible is via pip, but the homebrew
# installation should be more readily available with fewer environment issues.
brew install ansible

# Archey
#
# An archey script clone for OS X
#
# Displays system information and a colorful Apple logo.
#
# https://obihann.github.io/archey-osx/
# https://github.com/obihann/archey-osx
#
# See also:
# https://github.com/djmelik/archey
#
# NOTE: uninstall since this is currently unused.
# TODO: remove this section.
if _homebrew_formula_is_installed "archey"
then
  brew uninstall archey
fi

# aria2
#
# aria2 is a lightweight multi-protocol & multi-source, cross platform download
# utility operated in command-line. It supports HTTP/HTTPS, FTP, SFTP,
# BitTorrent and Metalink.
#
# Options:
#   --with-libssh2
#     Build with libssh2 support
#
# https://github.com/tatsuhiro-t/aria2
# https://aria2.github.io/
brew install aria2 --with-libssh2

# GNU Aspell
#
# A Free and Open Source spell checker
#
# http://aspell.net/
brew install aspell --with-lang-en

# Autoconf
#
# Autoconf is an extensible package of M4 macros that produce shell scripts to
# automatically configure software source code packages. These scripts can
# adapt the packages to many kinds of UNIX-like systems without manual user
# intervention.
#
# http://www.gnu.org/software/autoconf/
brew install autoconf

# Autoenv: Directory-based Environments
#
# If a directory contains a `.env` file, it will automatically be executed
# when you `cd` into it.
#
# This is great for...
#
# - auto-activating virtualenvs
# - project-specific environment variables
# - making millions
# - Foreman env files are completely compatible.
#
#You can also nest envs within eachother.
#
# https://github.com/kennethreitz/autoenv
brew install autoenv

# GNU Bash
#
# Bash 4. Newer than OS X default.
#
# http://www.gnu.org/software/bash/
#
# NOTE: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before
# running `chsh`.
brew install bash

# bash-completion
#
# http://bash-completion.alioth.debian.org/
# https://alioth.debian.org/projects/bash-completion/
brew install bash-completion

# Bats
#
# Bash Automated Testing System
#
# Bats is a TAP-compliant testing framework for Bash. It provides a simple way
# to verify that the UNIX programs you write behave as expected.
#
# https://github.com/sstephenson/bats
brew install bats

# bfg repo-cleaner
#
# Removes large or troublesome blobs like git-filter-branch does, but faster.
# And written in Scala
#
# http://rtyley.github.io/bfg-repo-cleaner/
brew install bfg

# bmon
#
# bmon is a monitoring and debugging tool to capture networking related
# statistics and prepare them visually in a human friendly way. It features
# various output methods including an interactive curses user interface and a
# programmable text output for scripting.
#
# https://github.com/tgraf/bmon
brew install bmon

# boot2docker
#
# boot2docker management utility
#
# This tool downloads the boot2docker ISO image, creates a VirtualBox virtual
# machine, sets up two networks for that virtual machine (one NAT to allow
# the VM and containers to access the internet, the other host-only to allow
# container port mapping to work securely), and then provides the user a
# simple way to login via SSH.
#
# https://github.com/boot2docker/boot2docker-cli
brew install boot2docker
# - Post-install for boot2docker LaunchAgent
# if [[ ! -e "$HOME/Library/LaunchAgents/homebrew.mxcl.boot2docker.plist" ]]
# then
#   ln -sfv /usr/local/opt/boot2docker/*.plist "$HOME/Library/LaunchAgents"
#   launchctl load "$HOME/Library/LaunchAgents/homebrew.mxcl.boot2docker.plist"
# fi
# - Post-install for disabled boot2docker LaunchAgent
if [[ -e "$HOME/Library/LaunchAgents/homebrew.mxcl.boot2docker.plist" ]]
then
  launchctl unload "$HOME/Library/LaunchAgents/homebrew.mxcl.boot2docker.plist"
  rm "$HOME/Library/LaunchAgents/homebrew.mxcl.boot2docker.plist"
fi

# bup
#
# Very efficient backup system based on the git packfile format, providing
# fast incremental saves and global deduplication (among and within files,
# including virtual machine images).
#
# Options:
#   --with-pandoc
#     build and install the manpage (depends on pandoc)
#   --run-tests
#     Run unit tests after compilation
#
# https://bup.github.io/
# https://github.com/bup/bup
brew install bup --with-pandoc --run-tests

# calc
#
# Calc is an interactive calculator which provides for easy large numeric
# calculations, but which also can be easily programmed for difficult or long
# calculations. It can accept a command line argument, in which case it
# executes that single command and exits. Otherwise, it enters interactive
# mode. In this mode, it accepts commands one at a time, processes them, and
# displays the answers. In the simplest case, commands are simply expressions
# which are evaluated.
#
# http://www.isthe.com/chongo/tech/comp/calc/
brew install calc

# checkbashisms - check for bashisms in /bin/sh scripts
#
# checkbashisms,  based  on  one  of  the checks from the lintian system,
# performs basic  checks  on  /bin/sh  shell  scripts  for  the  possible
# presence  of  bashisms.  It takes the names of the shell scripts on the
# command line, and outputs warnings if possible bashisms are detected.
#
# http://manpages.ubuntu.com/manpages/natty/man1/checkbashisms.1.html
brew install checkbashisms

# clib(1) - C package manager-ish
#
# Package manager for the C programming language.
#
# https://github.com/clibs/clib
brew install clib

# cmatrix
#
# 'The Matrix'-inspired scrolling lines.
#
# http://www.asty.org/cmatrix/
brew install cmatrix

# cmus
#
# cmus is a small, fast and powerful console music player for Unix-like
# operating systems.
#
# https://cmus.github.io
# https://news.ycombinator.com/item?id=10430512
brew install cmus

# commonmark
#
# Strongly specified, highly compatible implementation of Markdown
#
# http://commonmark.org
#
# NOTE: executable name is `cmark`.
brew install commonmark

# composer
#
# Dependency Manager for PHP
#
# http://getcomposer.org
brew install composer

# contacts
#
# Command-line tool to access OS X's Contacts (formerly 'Address Book')
#
# http://www.gnufoo.org/contacts/contacts.html
brew install contacts

# coq
#
# Coq is a formal proof management system. It provides a formal language to
# write mathematical definitions, executable algorithms and theorems together
# with an environment for semi-interactive development of machine-checked
# proofs. Typical applications include the certification of properties of
# programming languages (e.g. the CompCert compiler certification project, or
# the Bedrock verified low-level programming library), the formalization of
# mathematics (e.g. the full formalization of the Feit-Thompson theorem or
# homotopy type theory) and teaching.
#
# https://coq.inria.fr/
brew install coq

# cowsay
#
# cowsay / cowthink - configurable speaking/thinking cow (and a bit more)
#
# Cowsay generates an ASCII picture of a cow saying  something  provided  by
# the user.
#
# https://web.archive.org/web/20120225123719/http://www.nog.net/~tony/warez/cowsay.shtml
brew install cowsay

# cputhrottle
#
# Limit the CPU usage of a process
#
# http://www.willnolan.com/cputhrottle/cputhrottle.html
brew install cputhrottle

# creds
#
# Creds, manage API keys with GPG on the command line.
#
# Simple encrypted credential file management with GPG.
#
# https://github.com/joemiller/creds
# https://news.ycombinator.com/item?id=11304585
brew install joemiller/taps/creds

# crystal-lang
#
# The Crystal Programming Language
#
# Crystal is a programming language with the following goals:
# - Have the same syntax as Ruby, or at least as similar as possible.
# - Statically type-checked but without having to specify the type of
#   variables or method arguments.
# - Be able to call C code by writing bindings to it in Crystal.
# - Have compile-time evaluation and generation of code, to avoid boilerplate
#   code.
# - Compile to efficient native code.
#
# http://crystal-lang.org/
# https://github.com/manastech/crystal
brew install crystal-lang

# ctags
#
# Ctags is a programming tool that generates an index (or tag) file of names
# found in source and header files of various programming languages. Depending
# on the language, functions, variables, class members, macros and so on may be
# indexed. These tags allow definitions to be quickly and easily located by a
# text editor or other utility. Alternatively, there is also an output mode
# that generates a cross reference file, listing information about various
# names found in a set of language files in human-readable form.
#
# http://ctags.sourceforge.net/
brew install ctags

# dash
#
# DASH is a POSIX-compliant implementation of /bin/sh that aims to be as small
# as possible. It does this without sacrificing speed where possible. In fact,
# it is significantly faster than bash (the GNU Bourne-Again SHell) for most
# tasks.
#
# http://gondor.apana.org.au/~herbert/dash/
brew install dash

# djvu2pdf
#
# A small tool to convert Djvu files to PDF files.
#
# http://0x2a.at/s/projects/djvu2pdf
#
# See also:
# http://djvu.sourceforge.net/
# https://en.wikipedia.org/wiki/DjVu
brew install djvu2pdf

# Docker
#
# Docker is an open platform for developers and sysadmins to build, ship, and
# run distributed applications.
#
# Docker is an open source project to pack, ship and run any application as a
# lightweight container.
#
# https://www.docker.com/
# https://github.com/docker/docker
brew install docker

# Docker Machine
#
# Machine management for a container-centric world
#
# Machine makes it really easy to create Docker hosts on your computer, on
# cloud providers and inside your own data center. It creates servers,
# installs Docker on them, then configures the Docker client to talk to them.
#
# https://docs.docker.com/machine/
# https://github.com/docker/machine
brew install docker-machine

# Docker Swarm
#
# Swarm: a Docker-native clustering system
#
# Docker Swarm is native clustering for Docker. It turns a pool of Docker hosts
# into a single, virtual host.
#
# https://github.com/docker/swarm
brew install docker-swarm

# dots
#
# A configuration tool and framework for your laptop or desktop
#
# https://github.com/alphabetum/dots
brew install dots

# Dwarf Fortress
#
# Dwarf Fortress is a part construction and management simulation, part
# roguelike, freeware indie video game.
#
# http://www.bay12games.com/dwarves/
brew install dwarf-fortress

# ELinks - Full-Featured Text WWW Browser
#
# ELinks is an advanced and well-established feature-rich text mode web
# (HTTP/FTP/..) browser.
#
# http://elinks.or.cz/
brew install elinks

# Elixir
#
# Elixir is a dynamic, functional language designed for building scalable and
# maintainable applications.
#
# http://elixir-lang.org/
#
# NOTE: also installs mix
#
# Mix is a build tool that provides tasks for creating, compiling, testing
# Elixir projects, as well as handle dependencies, and more.
#
# http://elixir-lang.org/docs/stable/mix/
# http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html
brew install elixir

# Emacs
#
# GNU Emacs text editor
#
# https://www.gnu.org/software/emacs/
#
# Options:
#   --with-cocoa
#     Build a Cocoa version of emacs
#
# NOTE: Temporarily disable in favor of railwaycat/emacsmacport/emacs-mac
# brew install emacs --with-cocoa
if _homebrew_formula_is_installed "emacs"
then
  brew uninstall emacs
fi

# emacs-mac-port / emacs-mac
#
# This is "Mac port" addition to GNU Emacs 24.  This provides a native
# GUI support for Mac OS X 10.4 - 10.10.  Note that Emacs 23 and later
# already contain the official GUI support via the NS (Cocoa) port for
# Mac OS X 10.4 and later.  So if it is good enough for you, then you
# don't need to try this.
#
# https://github.com/railwaycat/emacs-mac-port/blob/master/README-mac
# http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git/
# https://github.com/railwaycat/homebrew-emacsmacport
# https://github.com/syl20bnr/spacemacs#os-x
#
# Options:
#   --with-spacemacs-icon
#     Using the spacemacs Emacs icon by Nasser Alshammari
brew install railwaycat/emacsmacport/emacs-mac \
  --with-spacemacs-icon

# EncFS - an Encrypted Filesystem
#
# EncFS provides an encrypted filesystem in user-space. It runs with regular
# user permissions using the FUSE library.
#
# https://github.com/vgough/encfs
# https://vgough.github.io/encfs/
brew install homebrew/fuse/encfs

# Erlang
#
# Erlang is a programming language used to build massively scalable soft
# real-time systems with requirements on high availability. Some of its uses
# are in telecoms, banking, e-commerce, computer telephony and instant
# messaging. Erlang's runtime system has built-in support for concurrency,
# distribution and fault tolerance.
#
# http://www.erlang.org/
brew install erlang

# es
#
# Extensible shell with first class functions, lexical scoping, and more.
#
# http://wryun.github.io/es-shell/
brew install es

# Exiv2
#
# Image metadata library and tools
#
# http://www.exiv2.org
brew install exiv2

# fasd
#
# CLI tool for quick access to files and directories
#
# https://github.com/clvv/fasd
brew install fasd

# FFmpeg
#
# A complete, cross-platform solution to record, convert and stream audio and
# video.
#
# https://ffmpeg.org/
brew install ffmpeg

#  _____ _       _      _
# |  ___(_) __ _| | ___| |_
# | |_  | |/ _` | |/ _ \ __|
# |  _| | | (_| | |  __/ |_
# |_|   |_|\__, |_|\___|\__|
#          |___/
#
# Figlet
#
# FIGlet is a program for making large letters out of ordinary text
#
# http://www.figlet.org/
brew install figlet

# Fish
#
# Fish is a smart and user-friendly command line shell for OS X, Linux, and
# the rest of the family.
#
# http://fishshell.com/
# https://github.com/fish-shell/fish-shell
brew install fish

# Flow
#
# Flow is a static type checker, designed to find type errors in JavaScript
# programs.
#
# http://flowtype.org/
brew install flow

# forego
#
# Foreman (Manage Procfile-based applications) in Go.
#
# https://github.com/ddollar/foreman
# https://github.com/ddollar/forego
brew install forego

# Facebook PathPicker
#
# PathPicker accepts a wide range of input -- output from git commands, grep
# results, searches -- pretty much anything. After parsing the input,
# PathPicker presents you with a nice UI to select which files you're
# interested in. After that you can open them in your favorite editor or
# execute arbitrary commands.
#
# http://facebook.github.io/PathPicker/
# https://github.com/facebook/pathpicker/
brew install fpp

# gdrive
#
# Google Drive CLI Client
#
# gdrive is a command line utility for interacting with Google Drive.
#
# https://github.com/prasmussen/gdrive
# https://news.ycombinator.com/item?id=12784952
brew install gdrive

# geoip
#
# Libraries and tools for MaxMind’s GeoIP.
#
# http://dev.maxmind.com/geoip/
# https://github.com/maxmind/geoip-api-c
brew install geoip

# git
#
# Git is a free and open source distributed version control system designed to
# handle everything from small to very large projects with speed and efficiency
#
# http://git-scm.com
brew install git

# git-annex
#
# git-annex allows managing files with git, without checking the file contents
# into git. While that may seem paradoxical, it is useful when dealing with
# files larger than git can currently easily handle, whether due to limitations
# in memory, time, or disk space.
#
# https://git-annex.branchable.com/
brew install git-annex

# git-extras
#
# GIT utilities -- repo summary, repl, changelog population, author commit
# percentages and more.
#
# https://github.com/tj/git-extras
brew install git-extras

# git-lfs
#
# Git Large File Storage
#
# Git LFS is a command line extension and specification for managing large
# files with Git.
#
# https://git-lfs.github.com/
# https://github.com/github/git-lfs
brew install git-lfs

# go / golang
#
# Go is an open source programming language that makes it easy to build simple,
# reliable, and efficient software.
#
# https://golang.org/
# https://github.com/golang/go
#
# NOTE: uninstall since go is installed using other approaches.
# TODO: remove this section.
if _homebrew_formula_is_installed "go"
then
  brew uninstall go
fi

# GnuPG
#
# GnuPG is a complete and free implementation of the OpenPGP standard as
# defined by RFC4880 (also known as PGP). GnuPG allows to encrypt and sign
# your data and communication, features a versatile key management system as
# well as access modules for all kinds of public key directories. GnuPG, also
# known as GPG, is a command line tool with features for easy integration with
# other applications. A wealth of frontend applications and libraries are
# available.
#
# https://www.gnupg.org/
brew install gpg
# GnuPG - Version 2
#
# Version 2 of GnuPG also provides support for S/MIME and Secure Shell (ssh).
#
# https://www.gnupg.org/
brew install gnupg2

# GRASS GIS
#
# GRASS GIS, commonly referred to as GRASS (Geographic Resources Analysis
# Support System), is a free and open source Geographic Information System
# (GIS) software suite used for geospatial data management and analysis, image
# processing, graphics and maps production, spatial modeling, and
# visualization. GRASS GIS is currently used in academic and commercial
# settings around the world, as well as by many governmental agencies and
# environmental consulting companies. It is a founding member of the Open
# Source Geospatial Foundation (OSGeo).
#
# http://grass.osgeo.org/
brew install grass

# ghostscript
#
# Interpreter for PostScript and PDF
#
# http://www.ghostscript.com/
brew install gs

# The Haskell Tool Stack
#
# `stack` is a cross-platform program for developing Haskell projects. It is
# aimed at Haskellers both new and experienced.
#
# Stackage is a stable source of Haskell packages. We guarantee that packages
# build consistently and pass tests before generating nightly and Long Term
# Support (LTS) releases.
#
# https://www.stackage.org
# https://github.com/commercialhaskell/stack
# https://github.com/commercialhaskell/stack/blob/master/GUIDE.md
brew install haskell-stack

# GNU Grep
#
# Grep searches one or more input files for lines containing a match to a
# specified pattern. By default, Grep outputs the matching lines.
#
# https://www.gnu.org/software/grep/
#
# NOTES:
#   - An older version of grep is included by default in OS X
#   - this version is installed with a 'g' prefex and is called via `ggrep`
brew install homebrew/dupes/grep

# heroku
#
# Heroku client - CLI tool for creating and managing Heroku apps
#
# https://toolbelt.heroku.com/standalone
# https://github.com/heroku/heroku
brew install heroku

# Highlight
#
# Highlight converts sourcecode to HTML, XHTML, RTF, LaTeX, TeX, SVG, BBCode
# and terminal escape sequences with coloured syntax highlighting. Language
# definitions and colour themes are customizable.
#
# http://www.andre-simon.de/doku/highlight/en/highlight.php
brew install highlight

# htop (htop-osx)
#
# htop, an interactive process viewer.
#
# https://github.com/max-horvath/htop-osx
#
# NOTE: As of version 2.0.0, htop supports osx.
if _homebrew_formula_is_installed "htop-osx"
then
  brew uninstall htop-osx
fi
brew install htop

# httpie
#
# HTTPie is a command line HTTP client, a user-friendly cURL replacement.
#
# http://httpie.org
# https://github.com/jakubroztocil/httpie
brew install httpie

# hub
#
# hub is a command-line wrapper for git that makes you better at GitHub.
#
# http://hub.github.com/
#
# NOTE: uninstall / reinstall hub if 2.2.0-rc1... is still installed via
# the previous command with the `--head` option.
# TODO: remove this.
if [[ -n "$(hub --version | awk '/2.2.0-rc1/ {print $3}')" ]]
then
  brew uninstall hub
fi
brew install hub

# iftop
#
# iftop does for network usage what top(1) does for CPU usage. It listens to
# network traffic on a named interface and displays a table of current
# bandwidth usage by pairs of hosts. Handy for answering the question "why is
# our ADSL link so slow?".
#
# http://www.ex-parrot.com/~pdw/iftop/
brew install iftop

# ImageMagick
#
# ImageMagick® is a software suite to create, edit, compose, or convert bitmap
# images. It can read and write images in a variety of formats (over 100)
# including DPX, EXR, GIF, JPEG, JPEG-2000, PDF, PNG, Postscript, SVG, and
# TIFF. Use ImageMagick to resize, flip, mirror, rotate, distort, shear and
# transform images, adjust image colors, apply various special effects, or draw
# text, lines, polygons, ellipses and Bézier curves.
#
# http://www.imagemagick.org
#
# https://developers.google.com/speed/webp/?csw=1
brew install imagemagick

# io
#
# Io is a prototype-based programming language inspired by Smalltalk (all
# values are objects, all messages are dynamic), Self (prototype-based),
# NewtonScript (differential inheritance), Act1 (actors and futures for
# concurrency), LISP (code is a runtime inspectable/modifiable tree) and Lua
# (small, embeddable).
#
# NOTE: including --without-addons to avoid installation errors.
#
# http://iolanguage.org/
brew install io --without-addons

# Ioke
#
# Ioke is a new language for the JVM, based on Io and other languages. Ioke is
# a strongly typed, dynamic, prototype based programming language.
#
# https://ioke.org/
# https://github.com/olabini/ioke
brew install ioke

# irssi
#
#Irssi is a terminal based IRC client for UNIX systems. It also supports SILC
# and ICB protocols via plugins.
#
# http://irssi.org/
brew install irssi

# ispell
#
# International Ispell is an interactive spell-checking program for Unix which
# supports a large number of European languages. An emacs interface is
# available as well as the standard command-line mode.
#
# http://lasr.cs.ucla.edu/geoff/ispell.html
brew install ispell

# jp2a
#
# jp2a is a small utility that converts JPG images to ASCII.
# It's written in C and released under the GPL.
#
# http://csl.sublevel3.org/jp2a/
brew install jp2a

# jq
#
# A lightweight and flexible command-line JSON processor.
#
# jq is like sed for JSON data – you can use it to slice and filter and map
# and transform structured data with the same ease that sed, awk, grep and
# friends let you play with text.
#
# https://stedolan.github.io/jq/
# https://github.com/stedolan/jq
brew install jq

# jo
#
# JSON output from a shell
#
# This is jo, a small utility to create JSON objects
#
# https://github.com/jpmens/jo
# http://jpmens.net/2016/03/05/a-shell-command-to-create-json-jo/
brew install jo

# keybase
#
# Command-line interface to Keybase.io
#
# Public key crypto for everyone, publicly auditable proofs of identity.
#
# https://keybase.io/
brew install keybase

# kore
#
# Kore is an easy to use web application framework for writing scalable web
# APIs in C. Its main goals are security, scalability and allowing rapid
# development and deployment of such APIs.
#
# https://kore.io/
brew install kore

# ledger
#
# Ledger is a powerful, double-entry accounting system that is accessed from
# the UNIX command-line.
#
# http://www.ledger-cli.org/
# https://github.com/ledger/ledger
brew install ledger

# Leiningen
#
# Automate Clojure projects without setting your hair on fire.
#
# https://github.com/technomancy/leiningen
brew install leiningen

# lesspipe
#
# lesspipe.sh is an input filter for the pager less as described in less's man
# page.
#
# http://www-zeuthen.desy.de/~friebel/unix/lesspipe.html
brew install lesspipe

# libcello
#
# Higher level programming in C
#
# http://libcello.org/
brew install libcello

# libgit2
#
# libgit2 is a portable, pure C implementation of the Git core methods provided
# as a re-entrant linkable library with a solid API, allowing you to write
# native speed custom Git applications in any language which supports C
# bindings.
#
# https://libgit2.github.com/
brew install libgit2

# libmaxminddb
#
# C library for the MaxMind DB file format
#
# http://maxmind.github.io/libmaxminddb/
# https://github.com/maxmind/libmaxminddb
#
# NOTE: for usage example, see the test in the homebrew formula:
# http://git.io/vezQa
brew install libmaxminddb

# LNAV -- The Logfile Navigator
#
# The log file navigator, lnav, is an enhanced log file viewer that takes
# advantage of any semantic information that can be gleaned from the files
# being viewed, such as timestamps and log levels. Using this extra semantic
# information, lnav can do things like interleaving messages from different
# files, generate histograms of messages over time, and providing hotkeys for
# navigating through the file. It is hoped that these features will allow the
# user to quickly and efficiently zero in on problems.
#
# http://lnav.org/
# https://github.com/tstack/lnav
brew install lnav

# Lua
#
# Lua is a powerful, fast, lightweight, embeddable scripting language.
#
# http://www.lua.org/
#
# NOTE: also installs Luarocks
#
# Package management for Lua modules. LuaRocks is a deployment and management
# system for Lua modules and allows you to install Lua modules as
# self-contained packages called "rocks", which also contain version dependency
# information.
#
# http://luarocks.org
#
# Remove existing outdated luarocks formula installation if present.
if _homebrew_formula_is_installed "luarocks"
then
  brew uninstall luarocks
fi
brew install lua

# LuaJIT
#
# LuaJIT is a Just-In-Time Compiler (JIT) for the Lua programming language.
# Lua is a powerful, dynamic and light-weight programming language. It may be
# embedded or used as a general-purpose, stand-alone language.
#
# http://luajit.org/
brew install luajit

# Lynis
#
# Lynis is an open source security auditing tool. Commonly used by system
# administrators, security professionals and auditors, to evaluate the
# security defenses of their Linux/Unix based systems. It runs on the host
# itself, so it performs more extensive security scans than vulnerability
# scanners.
#
# https://cisofy.com/lynis/
brew install lynis

# Lynx
#
# Lynx is a fully-featured World Wide Web (WWW) client for users running
# cursor-addressable, character-cell display devices such as vt100 terminals
#
# http://lynx.isc.org/release/
brew install lynx

# MacVim
#
# The text editor Vim for Mac OS X.
#
# http://code.google.com/p/macvim/
#
# NOTE: HEAD was previously installed in order to get El Capitan fixes, and
# these fixes are now available as a snapshot version.
if _homebrew_formula_is_installed "macvim" &&
  [[ "$(brew info macvim)" =~ Cellar/macvim/HEAD ]]
then
  brew uninstall macvim
fi
brew install macvim

# man2html
#
# Convert nroff man pages to HTML
#
# http://dcssrv1.oit.uci.edu/indiv/ehood/man2html.html
brew install man2html

# matplotlib
#
# matplotlib is a python 2D plotting library which produces publication
# quality figures in a variety of hardcopy formats and interactive environments
# across platforms. matplotlib can be used in python scripts, the python and
# ipython shell (ala MATLAB®* or Mathematica®†), web application servers, and
# six graphical user interface toolkits.
#
# http://matplotlib.org
brew install homebrew/python/matplotlib

# Memcached
#
# Free & open source, high-performance, distributed memory object caching
# system, generic in nature, but intended for use in speeding up dynamic web
# applications by alleviating database load.
#
# http://memcached.org/
brew install memcached

# Mercurial
#
# Mercurial is a free, distributed source control management tool.
#
# http://mercurial.selenic.com/
brew install mercurial

# Midnight Commander
#
# GNU Midnight Commander is a visual file manager
#
# https://www.midnight-commander.org/
# http://en.wikipedia.org/wiki/Midnight_Commander
brew install midnight-commander

# MIT/GNU Scheme
#
# MIT/GNU Scheme is an implementation of the Scheme programming language,
# providing an interpreter, compiler, source-code debugger, integrated
# Emacs-like editor, and a large runtime library.
#
# http://www.gnu.org/software/mit-scheme/
brew install homebrew/x11/mit-scheme

# MongoDB
#
# MongoDB (from humongous) is a cross-platform document-oriented database.
# Classified as a NoSQL database, MongoDB eschews the traditional table-based
# relational database structure in favor of JSON-like documents with dynamic
# schemas (MongoDB calls the format BSON).
#
# https://www.mongodb.org/
brew install mongodb

# Mosh / mobile-shell
#
# Remote terminal application that allows roaming, supports intermittent
# connectivity, and provides intelligent local echo and line editing of user
# keystrokes.
#
# Mosh is a replacement for SSH. It's more robust and responsive, especially
# over Wi-Fi, cellular, and long-distance links.
#
# https://mosh.mit.edu/
brew install mobile-shell

# mopidy
#
# Mopidy is an extensible music server written in Python.
#
# Mopidy plays music from local disk, Spotify, SoundCloud, Google Play Music,
# and more. You edit the playlist from any phone, tablet, or computer using a
# range of MPD and web clients.
#
# https://www.mopidy.com
brew install mopidy/mopidy/mopidy
# - Post-install for mopidy LaunchAgent
# if [[ ! -e "$HOME/Library/LaunchAgents/homebrew.mopidy.mopidy.plist" ]]
# then
#   ln -sfv /usr/local/opt/mopidy/*.plist "$HOME/Library/LaunchAgents"
#   launchctl load "$HOME/Library/LaunchAgents/homebrew.mopidy.mopidy.plist"
# fi

# MOST
#
# MOST is a powerful paging program for Unix, VMS, MSDOS, and win32 systems.
# Unlike other well-known paging programs most supports multiple windows and
# can scroll left and right.
#
# http://www.jedsoft.org/most/
brew install most

# MPlayer
#
# MPlayer is a free software and open source media player.
#
# http://www.mplayerhq.hu/
# https://en.wikipedia.org/wiki/MPlayer
#
# Options:
#   --with-libcaca
#     Build with libcaca support
#
#     libcaca is a graphics library that outputs text instead of pixels, so
#     that it can work on older video cards or text terminals.
#
#     http://caca.zoy.org/wiki/libcaca
#
#   --with-x11
#     Build with x11 support
brew install mplayer --with-libcaca --with-x11

# msgpack
#
# MessagePack is an efficient binary serialization format. It lets you exchange
# data among multiple languages like JSON. But it's faster and smaller. Small
# integers are encoded into a single byte, and typical short strings require
# only one extra byte in addition to the strings themselves.
#
# http://msgpack.org/
brew install msgpack

# multirust
#
# A simple tool for managing multiple installations of the Rust toolchain. It
# replaces the standard Rust toolchain with components that dynamically choose
# between alternate implementations based on context.
#
# https://github.com/brson/multirust
brew install multirust

# mutt
#
# Mutt is a small but very powerful text-based mail client for Unix operating
# systems.
#
# http://www.mutt.org/
#
# Options:
#   --with-trash-patch
#     Apply trash folder patch
brew install mutt --with-trash-patch

# mvnvm
#
# Maven Version Manager
#
# http://mvnvm.org/
# https://bitbucket.org/mjensen/mvnvm
brew install mvnvm

# mysql
#
# Open source relational database management system.
#
# https://dev.mysql.com/doc/refman/5.6/en/
#
# Caveats:
#   A "/etc/my.cnf" from another install may interfere with a Homebrew-built
#   server starting up correctly.
#
#   To connect:
#     mysql -uroot
#
#   To reload mysql after an upgrade:
#       launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
#       launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
#   Or, if you don't want/need launchctl, you can just run:
#       mysql.server start
brew install mysql
# mysql post-install
#
# Setup LaunchAgent for mysql.
#
# NOTE: Temporarily remove mysql LaunchAgent autoloading. MySQL takes up a
# lot of memory and is not used much.
#
# - Post-install for enabled mysql:
# if [[ ! -e "$HOME/Library/LaunchAgents/homebrew.mxcl.mysql.plist" ]]
# then
#   ln -sfv /usr/local/opt/mysql/*.plist "$HOME/Library/LaunchAgents"
#   launchctl load "$HOME/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
# fi
# - Post-install for disabled mysql:
if [[ -e "$HOME/Library/LaunchAgents/homebrew.mxcl.mysql.plist" ]]
then
  launchctl unload "$HOME/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
  rm "$HOME/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
fi

# ncdu
#
# NCurses Disk Usage
#
# http://dev.yorhel.nl/ncdu
brew install ncdu

# ne
#
# The nice editor.
#
# http://ne.di.unimi.it
brew install ne

# neovim
#
# http://neovim.org/
# https://github.com/neovim/neovim
# https://github.com/neovim/neovim/wiki/Installing
#
# NOTE: If the current install is an HEAD install, reinstall.
if [[ "$(brew info neovim)" =~ Cellar/neovim/HEAD ]]
then
  brew uninstall neovim
fi
brew install neovim/neovim/neovim

# netcat
#
# Utility for managing network connections.
#
# http://netcat.sourceforge.net/
brew install netcat

# Newsbeuter
#
# Newsbeuter is an open-source RSS/Atom feed reader for text terminals. It
# runs on Linux, FreeBSD, Mac OS X and other Unix-like operating systems.
# Newsbeuter’s great configurability and vast number of features make it a
# perfect choice for people that need a slick and fast feed reader that can
# be completely controlled via keyboard.
#
# http://www.newsbeuter.org/
# https://github.com/akrennmair/newsbeuter/
brew install newsbeuter

# ngrep - network grep
#
# ngrep strives to provide most of GNU grep's common features, applying them to
# the network layer. ngrep is a pcap-aware tool that will allow you to specify
# extended regular or hexadecimal expressions to match against data payloads of
# packets.
#
# http://ngrep.sourceforge.net/
brew install ngrep

# nim / nimrod
#
# Nim (formerly known as "Nimrod") is a statically typed, imperative
# programming language that tries to give the programmer ultimate power without
# compromises on runtime efficiency. This means it focuses on compile-time
# mechanisms in all their various forms.
#
# http://nim-lang.org/
brew install nimrod

# node.js
#
# Node.js® is a platform built on Chrome's JavaScript runtime. Node.js uses an
# event-driven, non-blocking I/O model
#
# https://nodejs.org/
#
# NOTE: Uninstall node and npm in favor of nvm.
# https://github.com/creationix/nvm
# TODO: Remove this after node has been removed from all systems.
_uninstall_node_and_npm() {
  if _homebrew_formula_is_installed "node"
  then
    if [[ -h "${HOME}/.npmrc" ]]
    then
      rm "${HOME}/.npmrc"
    fi

    if [[ -h "${HOME}/.npm-packages" ]]
    then
      rm -r "${HOME}/.npm-packages"
    fi

    if [[ "$(which npm)" == "/usr/local/bin/npm" ]]
    then
      npm uninstall npm -g
    fi

    brew uninstall node
  fi
}
_uninstall_node_and_npm

# NSQ
#
# NSQ is a realtime distributed messaging platform designed to operate at
# scale, handling billions of messages per day.
#
# http://nsq.io/
# https://github.com/bitly/nsq
brew install nsq

# numpy
#
# NumPy is the fundamental package for scientific computing with Python. It
# contains among other things:
#
# - a powerful N-dimensional array object
# - sophisticated (broadcasting) functions
# - tools for integrating C/C++ and Fortran code
# - useful linear algebra, Fourier transform, and random number capabilities
#
# Besides its obvious scientific uses, NumPy can also be used as an efficient
# multi-dimensional container of generic data. Arbitrary data-types can be
# defined. This allows NumPy to seamlessly and speedily integrate with a wide
# variety of databases.
#
# http://www.numpy.org
brew install homebrew/python/numpy

# OCaml
#
# OCaml, originally known as Objective Caml, is the main implementation of the
# Caml programming language.
#
# http://ocaml.org
brew install ocaml

# offlineimap
#
# Synchronizes emails between two repositories
#
# http://offlineimap.org/
#
# Caveats:
#   To get started, copy one of these configurations to ~/.offlineimaprc:
#   * minimal configuration:
#       cp -n /usr/local/etc/offlineimap.conf.minimal ~/.offlineimaprc
#
#   * advanced configuration:
#       cp -n /usr/local/etc/offlineimap.conf ~/.offlineimaprc
#
#   To have launchd start offlineimap at login:
#     ln -sfv /usr/local/opt/offlineimap/*.plist ~/Library/LaunchAgents
#   Then to load offlineimap now:
#     launchctl load ~/Library/LaunchAgents/homebrew.mxcl.offlineimap.plist
brew install offlineimap
# offlineimap post-install
#
# Setup LaunchAgent for offlineimap.
#
# - Post-install for offlineimap:
#
# NOTE: enable once this offlineimap been configured.
#
# if [[ ! -e "$HOME/Library/LaunchAgents/homebrew.mxcl.offlineimap.plist" ]]
# then
#   ln -sfv /usr/local/opt/mysql/*.plist "$HOME/Library/LaunchAgents"
#   launchctl load "$HOME/Library/LaunchAgents/homebrew.mxcl.offlineimap.plist"
# fi

# OPAM - OCaml Package Manager
#
# OPAM is a source-based package manager for OCaml. It supports multiple
# simultaneous compiler installations, flexible package constraints, and a
# Git-friendly development workflow.
#
# https://opam.ocaml.org
brew install opam

# Open CASCADE Technology, 3D modeling & numerical simulation
#
# Open CASCADE Technology is a software development kit (SDK) intended for
# development of applications dealing with 3D CAD data, freely available in
# open source. It includes a set of C++ class libraries providing services for
# 3D surface and solid modeling, visualization, data exchange and rapid
# application development.
#
# http://www.opencascade.org/
brew install opencascade

# ori - A Secure Distributed File System
#
# Ori is a distributed file system built for offline operation and empowers the
# user with control over synchronization operations and conflict resolution.
# We provide history through light weight snapshots and allow users to verify
# the history has not been tampered with. Through the use of replication
# instances can be resilient and recover damaged data from other nodes.
#
# http://ori.scs.stanford.edu/
# https://bitbucket.org/orifs/ori/wiki/Home
brew install homebrew/fuse/ori

# osquery
#
# SQL powered operating system instrumentation, monitoring, and analytics.
#
# osquery is an operating system instrumentation framework for OS X and Linux.
# It makes low-level operating system analytics performant and intuitive.
#
# https://github.com/facebook/osquery
# https://osquery.io/
brew install osquery

# osxutils
#
# osxutils is a bundle of Mac OS X command line utilities that bring power over
# all sorts of Mac-specific information, settings and meta-data to the command
# line.
#
# https://github.com/vasi/osxutils
brew install osxutils

# otto
#
# Development and deployment system designed as the successor to Vagrant.
#
# https://ottoproject.io
brew install otto

# p7zip
#
# A file archiver with a high compression ratio. p7zip is a port of 7za.exe for
#POSIX systems like Unix.
#
# http://p7zip.sourceforge.net/
brew install p7zip

# Packer
#
# Packer is a tool for creating identical machine images for multiple platforms
# from a single source configuration.
#
# http://www.packer.io/
brew install packer

# PacVim
#
# PacVim is a game that teaches you vim commands. You must move pacman (the
# green cursor) to highlight each word on the gameboard while avoiding the
# ghosts (in red).
#
# https://github.com/jmoon018/PacVim
brew install pacvim

# Pandoc
#
# Pandoc converts files from one markup format into another
#
#http://johnmacfarlane.net/pandoc/
brew install pandoc

# pass
#
# the standard unix password manager
#
# Password management should be simple and follow Unix philosophy. With pass,
# each password lives inside of a gpg encrypted file whose filename is the
# title of the website or resource that requires the password. These encrypted
# files may be organized into meaningful folder hierarchies, copied from
# computer to computer, and, in general, manipulated using standard command
# line file management utilities.
#
# http://www.passwordstore.org/
# http://git.zx2c4.com/password-store/
# https://github.com/zx2c4/password-store
# https://news.ycombinator.com/item?id=9820249
brew install pass

# pdfgrep
#
# Search PDFs for strings matching a regular expression
#
# https://pdfgrep.org/
brew install pdfgrep

# PHP 5.6
#
# PHP is a server-side scripting language designed for web development but also
# used as a general-purpose programming language.
#
# https://php.net
#
# Options:
#   --with-gpm
#     Build with gmp support. GNU Multiple Precision:
#     http://php.net/manual/en/book.gmp.php
brew install homebrew/php/php56 --with-gmp

# Pick
#
# The pick(1) utility allows users to choose one option from a set of choices
# using an interface with fuzzy search functionality.
#
# https://github.com/thoughtbot/pick
# https://robots.thoughtbot.com/announcing-pick
#
# NOTE: This formula was previously only available through the thoughtbot
# tap, but it has since been moved to homebrew core.
# TODO: Remove this uninstall block when the tapped formula has been removed
# from all systems.
if _homebrew_formula_is_installed "thoughtbot/formulae/pick"
then
  brew uninstall thoughtbot/formulae/pick
fi
brew install pick

# pidgin
#
# Pidgin is a chat program which lets you log in to accounts on multiple chat
# networks simultaneously. This means that you can be chatting with friends on
# MSN, talking to a friend on Google Talk, and sitting in a Yahoo chat room
# all at the same time.
#
# https://pidgin.im/
#
# Options:
#   --with-gsasl
#     Build with gsasl support
#
#     GNU SASL Library - Libgsasl
#
#     GNU SASL is an implementation of the Simple Authentication and Security
#     Layer framework and a few common SASL mechanisms. SASL is used by
#     network servers (e.g., IMAP, SMTP) to request authentication from
#     clients, and in clients to authenticate against servers.
#
#     http://www.gnu.org/software/gsasl/
#
#   --without-GUI
#     Build Finch instead of Pidgin
#
#     A text-based user interface for using libpurple.  This can be run from a
#     standard text console or from a terminal within X Windows.  It
#     uses ncurses and our homegrown gnt library for drawing windows
#     and text.
#
#     https://en.wikipedia.org/wiki/Finch_(software)
#     https://developer.pidgin.im/wiki/Using%20Finch
#     http://linux.die.net/man/1/finch
brew install pidgin --with-gsasl --without-GUI

# pigz
#
# A parallel implementation of gzip for modern multi-processor, multi-core
# machines
#
# http://www.zlib.net/pigz/
brew install pigz

# poppler
#
# PDF rendering library (based on the xpdf-3.0 code base)
#
# http://poppler.freedesktop.org
brew install poppler
# force link poppler to overwrite xpdf links.
# TODO: remove this when xpdf has been uninstalled from all systems.
brew link poppler --force

# PostgreSQL
#
# Object-relational database system.
#
# https://www.postgresql.org/
brew install postgresql
# Post-install for postgresql.
if [[ ! -e "$HOME/Library/LaunchAgents/homebrew.mxcl.postgresql.plist" ]]
then
  ln -sfv /usr/local/opt/postgresql/*.plist "$HOME/Library/LaunchAgents"
  launchctl load "$HOME/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
fi

# pow
#
# Pow is a zero-config Rack server for Mac OS X.
#
# http://pow.cx/
# https://github.com/basecamp/pow
brew install pow
# pow post-install
#
# Create the required host directories:
if [[ ! -d "$HOME/Library/Application Support/Pow/Hosts" ]]
then
  mkdir -p "$HOME/Library/Application Support/Pow/Hosts"
  if [[ ! -e "$HOME/.pow" ]]
  then
    ln -s "$HOME/Library/Application Support/Pow/Hosts" "$HOME/.pow"
  fi
fi
# Setup and launch port 80 forwarding and launchd agents
if ! ( [[ -e "/Library/LaunchDaemons/cx.pow.firewall.plist" ]] || \
       [[ -e "/etc/resolver/dev" ]]
)
then
  sudo pow --install-system
  sudo launchctl load -w "/Library/LaunchDaemons/cx.pow.firewall.plist"
fi
if [[ ! -e "$HOME/Library/LaunchAgents/cx.pow.powd.plist" ]]
then
  pow --install-local
  launchctl load -w "$HOME/Library/LaunchAgents/cx.pow.powd.plist"
fi

# pv - Pipe Viewer
#
# A terminal-based tool for monitoring the progress of data through a pipeline.
#
# http://www.ivarch.com/programs/pv.shtml
brew install pv

# pwsafe
#
# Generate passwords and manage encrypted password databases.
#
# http://nsd.dyndns.org/pwsafe/
# https://github.com/nsd20463/pwsafe
brew install pwsafe

# python
#
# Python 2
#
# https://www.python.org
brew install python

# python3
#
# Python 3
#
# https://www.python.org
brew install python3

# R
#
# R is a free software environment for statistical computing and graphics.
#
# http://www.r-project.org/
#
# Options:
#   --with-openblas
#     Build with openblas support
#     http://www.openblas.net/
brew install r --with-openblas

# ranger
#
# ranger is a file manager with VI key bindings. It provides a minimalistic
# and nice curses interface with a view on the directory hierarchy. The
# secondary task of ranger is to psychically guess which program you want to
# use for opening particular files.
#
# http://ranger.nongnu.org/
brew install ranger

# recutils
#
# GNU Recutils is a set of tools and libraries to access human-editable, plain
# text databases called recfiles. The data is stored as a sequence of records,
# each record containing an arbitrary number of named fields.
#
# http://www.gnu.org/software/recutils/
brew install recutils

# redo
#
# Smaller, easier, more powerful, and more reliable than make. An
# implementation of djb's redo.
#
# https://github.com/apenwarr/redo
# http://homepage.ntlworld.com/jonathan.deboynepollard/FGA/introduction-to-redo.html
brew install redo

# rename
#
# renames files according to modification rules specified on the command line.
#
# http://plasmasturm.org/code/rename
brew install rename

# Redis
#
# Redis is an open source, BSD licensed, advanced key-value cache and store. It
# is often referred to as a data structure server since keys can contain
# strings, hashes, lists, sets, sorted sets, bitmaps and hyperloglogs.
#
# http://redis.io/
brew install redis

# Rhino
#
# Rhino is an open-source implementation of JavaScript written entirely in
# Java.
#
# http://www.mozilla.org/rhino/
brew install rhino

# Riak
#
# Riak is an open source, distributed database.
#
# http://basho.com/riak/
brew install riak

# RingoJS
#
# Ringo is a CommonJS-based JavaScript runtime written in Java and based on the
# Mozilla Rhino JavaScript engine.
#
# http://ringojs.org
brew install ringojs

# rsync
#
# Utility that provides fast incremental file transfer.
#
# https://rsync.samba.org/
#
# NOTE: this is a newer version than the one that ships with OS X,
# currently 3.1.1  protocol version 31 vs 2.6.9  protocol version 29.
brew install homebrew/dupes/rsync

# sbt
#
# The interactive build tool
#
# Use Scala to define your tasks. Then run them in parallel from the shell.
#
# http://www.scala-sbt.org/
brew install sbt

# Scala
#
# Scala is an object-functional programming language for general software
# applications.
#
# http://www.scala-lang.org/
brew install scala

# scipy
#
# SciPy (pronounced “Sigh Pie”) is a Python-based ecosystem of open-source
# software for mathematics, science, and engineering.
#
# http://www.scipy.org
#
# NOTE: not including python3 support because it takes 10 minutes to build.
brew install homebrew/python/scipy

# scons
#
# SCons is a software construction tool—that is, a superior alternative to the
# classic "Make" build tool that we all know and love. SCons is an Open Source
# software construction tool—that is, a next-generation build tool. Think of
# SCons as an improved, cross-platform substitute for the classic Make utility
# with integrated functionality similar to autoconf/automake and compiler
# caches such as ccache.
#
# http://www.scons.org/
brew install scons

# GNU Screen
#
# Screen is a full-screen window manager that multiplexes a physical terminal
# between several processes, typically interactive shells.
#
# https://www.gnu.org/software/screen
#
# NOTE: An older BSD version is included with OS X, but this newer GNU
# version supercedes it.
brew install homebrew/dupes/screen

# screenresolution
#
# Command line utility for getting, setting and listing display resolution on
# Mac OS X 10.6+
#
# https://github.com/jhford/screenresolution
brew install screenresolution

# scsh
#
# Scsh is a POSIX API layered on top of the Scheme programming language in a
# manner to make the most of Scheme's capability for scripting. It is limited
# to 32-bit platforms but there is a development version against the latest
# scheme48 that works in 64-bit mode.
#
# https://en.wikipedia.org/wiki/Scsh
# http://scsh.net/docu/html/man.html
brew install scsh

# ShellCheck
#
# Automatically detects problems with sh/bash scripts and commands
#
# http://www.shellcheck.net/
brew install shellcheck

# Siege
#
# Siege is an http load testing and benchmarking utility.
#
# http://www.joedog.org/index/siege-home
brew install siege

# Spark
#
# sparklines for your shell
#
# See? Here's a graph of your productivity gains after using spark: ▁▂▃▅▇
#
# https://github.com/holman/spark
brew install spark

# Sphinx
#
# Sphinx is a free software/open source Fulltext search engine designed to
# provide full-text search functionality to client applications.
#
# http://www.sphinxsearch.com
brew install sphinx

# sshfs
#
# A network filesystem client to connect to SSH servers
#
# https://github.com/libfuse/sshfs
brew install homebrew/fuse/sshfs

# GNU Stow
#
# GNU Stow is a symlink farm manager which takes distinct packages of software
# and/or data located in separate directories on the filesystem, and makes
# them appear to be installed in the same place.
#
# http://www.gnu.org/software/stow/
brew install stow

# Surfraw
#
# Surfraw provides a fast unix command line interface to a variety of popular
# WWW search engines and other artifacts of power. It reclaims google,
# altavista, babelfish, dejanews, freshmeat, research index, slashdot and many
# others from the false-prophet, pox-infested heathen lands of html-forms,
# placing these wonders where they belong, deep in unix heartland, as god
# loving extensions to the shell.
#
# Surfraw abstracts the browser away from input. Doing so lets it get on with
# what it's good at. Browsing. Interpretation of linguistic forms is handed
# back to the shell, which is what it, and human beings are good at. Combined
# with netscape-remote or incremental text browsers, such as lynx, links or
# w3m, along with screen a Surfraw liberateur is capable of navigating speeds
# that leave GUI tainted idolaters agape with fear and wonder.
#
# https://surfraw.alioth.debian.org/
brew install surfraw

# swiftlint
#
# Experimental tool to enforce Swift style and conventions.
#
# https://github.com/realm/SwiftLint
brew install swiftlint

# syncthing
#
# Open Source Continuous File Synchronization
#
# http://syncthing.net
# https://github.com/syncthing/syncthing
brew install syncthing
# syncthing post-install
#
# Setup and launch launchd agent
#
# NOTE: Temporarily disable syncthing. It's not currently being used and the
# syncing process runs unnecessarily. Commenting out post-install commands and
# adding new disabling commands.
#
# - Post-install for enabled syncthing:
# if [[ ! -e "$HOME/Library/LaunchAgents/homebrew.mxcl.syncthing.plist" ]]
# then
#   ln -sfv /usr/local/opt/syncthing/*.plist "$HOME/Library/LaunchAgents"
#   launchctl load "$HOME/Library/LaunchAgents/homebrew.mxcl.syncthing.plist"
# fi
# - Post-install for disabled syncthing:
if [[ -e "$HOME/Library/LaunchAgents/homebrew.mxcl.syncthing.plist" ]]
then
  launchctl unload "$HOME/Library/LaunchAgents/homebrew.mxcl.syncthing.plist"
  rm "$HOME/Library/LaunchAgents/homebrew.mxcl.syncthing.plist"
fi

# tag
#
# A command line tool to manipulate tags on Mavericks files, and to query for
# files with those tags.
#
# https://github.com/jdberry/tag
brew install tag

# Task - Taskwarrior
#
# Feature-rich console based todo list manager.
#
# https://taskwarrior.org/
brew install task

# Tig - text-mode interface for Git
#
# Tig is an ncurses-based text-mode interface for git. It functions mainly as a
# Git repository browser, but can also assist in staging changes for commit at
# chunk level and act as a pager for output from various Git commands.
#
# http://jonas.nitro.dk/tig/
brew install tig

# tmux
#
# tmux is a terminal multiplexer. It lets you switch easily between several
# programs in one terminal, detach them (they keep running in the background)
# and reattach them to a different terminal.
#
# http://tmux.sourceforge.net
brew install tmux

# tmuxinator
#
# Manage complex tmux sessions easily
#
# https://github.com/tmuxinator/tmuxinator
brew install tmuxinator-completion

# The Silver Searcher
#
# A code-searching tool similar to ack, but faster.
#
# https://github.com/ggreer/the_silver_searcher
# http://geoff.greer.fm/ag/
#
# NOTE: command name is `ag`
brew install the_silver_searcher

# TOIlet
#
# The TOIlet project attempts to create a free replacement for the FIGlet
# utility. TOIlet stands for “The Other Implementation’s letters”, coined
# after FIGlet’s “Frank, Ian and Glen’s letters”.
#
# TOIlet is in its very early development phase. It uses the powerful libcaca
# library to achieve various text-based effects.
#
# TOIlet also aims for full FIGlet compatibility.
#
# http://caca.zoy.org/wiki/toilet
brew install toilet

# tree
#
# Tree is a recursive directory listing command that produces a depth indented
# listing of files.
#
# http://mama.indstate.edu/users/ice/tree/
brew install tree

# ttygif
#
# Convert terminal recordings to animated gifs
#
# ttygif converts a ttyrec file into gif files. It's a stripped down version
# of ttyplay that captures every frame.
#
# https://github.com/icholy/ttygif
#
# NOTE: Installs ttyrec
#
# ttyrec is a tty recorder. Recorded data can be played back with the included
# ttyplay command. ttyrec is just a derivative of script command for recording
# timing information with microsecond accuracy as well. It can record emacs
# -nw, vi, lynx, or any programs running on tty.
#
# https://github.com/mjording/ttyrec
#
# NOTE: Not installed but related: terminal-gif
#
# A simple wrapper around https://github.com/icholy/ttygif that allows you to
# record terminal commands to a gif in one command
#
# https://github.com/michaeldfallen/terminal-gif
brew install https://raw.githubusercontent.com/icholy/ttygif/master/ttygif.rb

# Tup
#
# Tup is a file-based build system for Linux, OSX, and Windows. It inputs a
# list of file changes and a directed acyclic graph (DAG), then processes
# the DAG to execute the appropriate commands required to update dependent
# files. Updates are performed with very little overhead since tup implements
# powerful build algorithms to avoid doing unnecessary work. This means you
# can stay focused on your project rather than on your build system.
#
# http://gittup.org/tup/
# https://github.com/gittup/tup
brew install homebrew/fuse/tup

# Unison
#
# Unison is a file-synchronization tool for OSX, Unix, and Windows. It allows
# two replicas of a collection of files and directories to be stored on
# different hosts (or different disks on the same host), modified separately,
# and then brought up to date by propagating the changes in each replica to
# the other.
#
# http://www.cis.upenn.edu/~bcpierce/unison/
brew install unison

# Valgrind
#
# Valgrind is an instrumentation framework for building dynamic analysis tools.
# There are Valgrind tools that can automatically detect many memory management
# and threading bugs, and profile your programs in detail.
#
# http://valgrind.org/
#
# NOTE: installing head version for yosemite support.
brew install --HEAD valgrind

# vim
#
# Vim (a contraction of Vi IMproved) is a clone of Bill Joy's vi editor for
# Unix. It was written by Bram Moolenaar based on source for a port of the
# Stevie editor to the Amiga and first released publicly in 1991. Vim is
# designed for use both from a command-line interface and as a standalone
# application in a graphical user interface.
#
# http://www.vim.org/
brew install vim --override-system-vi

# vimpager
#
# Use ViM as PAGER
#
# A PAGER using less.vim with support for highlighting of man pages and many
# other features.
#
# https://github.com/rkitover/vimpager
# http://www.vim.org/scripts/script.php?script_id=1723
#
# NOTE: also installs vimcat
#
# cat with Vim's syntax highlighting
#
# https://github.com/ofavre/vimcat
brew install vimpager

# vv
#
# 🌐 Variable VVV - a VVV Site Creation Wizard
#
# vv makes it extremely easy to create a new WordPress site using Varying
# Vagrant Vagrants. vv supports site creation with many different options;
# site blueprints to set up all your plugins, themes, and more; deployments;
# and lots more features.
#
# https://github.com/bradp/vv
brew install bradp/vv/vv

# w3m
#
# w3m is a text-based web browser as well as a pager like `more' or `less'.
# With w3m you can browse web pages through a terminal emulator window (xterm,
# rxvt or something like that). Moreover, w3m can be used as a text formatting
# tool which typesets HTML into plain text.
#
# http://w3m.sourceforge.net/
brew install w3m

# Wcalc
#
# Wcalc is a very capable calculator. It supports abitrary precision, has
# standard functions (sin, asin, and sinh for example, in either radians or
# degrees), many pre-defined constants (pi, e, c, etc.), support for using
# variables, "active" variables, a command history, hex/octal/binary input
# and output, unit conversions, embedded comments, and an expandable
# expression entry field. It evaluates expressions using the standard order
# of operations.
#
# http://w-calc.sourceforge.net
brew install w-calc

# webkit2png
#
# webkit2png is a command line tool that creates screenshots of webpages
#
# http://www.paulhammond.org/webkit2png/
brew install webkit2png

# WeeChat
#
# WeeChat is a fast, light and extensible chat client.
#
# https://weechat.org/
brew install weechat

# wget
#
# GNU Wget is a free software package for retrieving files using HTTP, HTTPS
# and FTP, the most widely-used Internet protocols.
#
# https://www.gnu.org/software/wget/
#
# NOTE: including support of IRIs, Internationalized Resource Identifiers,
# which are similar to URI, but allow unicode charaters to be used.
brew install wget --with-iri

# Wine
#
# Run Windows applications on Linux, BSD, Solaris and Mac OS X.
#
# http://winehq.org/
brew install wine

# Winetricks
#
# Winetricks is an easy way to work around problems in Wine.
#
# http://code.google.com/p/winetricks/
brew install winetricks

# Xpdf
#
# Xpdf is an open source viewer for Portable Document Format (PDF) files.
#
# http://www.foolabs.com/xpdf/
#
# NOTE: Uninstall xpdf in favor of poppler.
#
# TODO: remove this entry when xpdf has been removed from all systems.
if _homebrew_formula_is_installed "xpdf"
then
  brew uninstall xpdf
fi

# XZ Utils
#
# XZ Utils is free general-purpose data compression software with high
# compression ratio.
#
# http://tukaani.org/xz/
brew install xz

# yap
#
# YAP is a high-performance Prolog compiler developed at LIACC/Universidade do
# Porto and at COPPE Sistemas/UFRJ. Its Prolog engine is based in the WAM
# (Warren Abstract Machine), with several optimizations for better performance.
# YAP follows the Edinburgh tradition, and is largely compatible with the
# ISO-Prolog standard and with Quintus and SICStus Prolog.
#
# http://www.dcc.fc.up.pt/~vsc/Yap/index.html
#
# NOTE: There have been a number of issues with this formula, which currently
# isn't being used.
# TODO: Remove this section when yap has been uninstalled from all systems.
if _homebrew_formula_is_installed "yap"
then
  brew uninstall yap
fi

# zeromq
#
# ØMQ (also spelled ZeroMQ, 0MQ or ZMQ) is a high-performance asynchronous
# messaging library aimed at use in scalable distributed or concurrent
# applications. It provides a message queue, but unlike message-oriented
# middleware, a ØMQ system can run without a dedicated message broker. The
# library is designed to have a familiar socket-style API.
#
# http://zeromq.org/
brew install zeromq

# Zopfli
#
# Zopfli Compression Algorithm is a new zlib (gzip, deflate) compatible
# compressor. This compressor takes more time (~100x slower), but compresses
# around 5% better than zlib and better than any other zlib-compatible
# compressor.
#
# https://code.google.com/p/zopfli/
brew install zopfli

# ZSH
#
# A UNIX shell (command interpreter)
#
# http://www.zsh.org/
brew install zsh
