#!/usr/bin/env bash
###############################################################################
# sublime-text-3
#
# Customize the Sublime Text 3 setup on OS X
###############################################################################

###############################################################################
# Platform Check
###############################################################################

if [[ ! "$OSTYPE" =~ ^darwin ]]
then
  printf "sublime-text-3 is only supported on OS X.\nSkipping...\n"
  exit 0
fi

###############################################################################
# Link Config
###############################################################################

# link_config()
#
# Usage:
#   link_config
#
# Description:
#   Add links from the OS X preferences location to the ~/.config location.
#   ~/.config is used on linux systems and versioned within in this
#   configuration project.
link_config() {
  local osx_prefs_path="${HOME}/Library/Application Support/Sublime Text 3"
  local config_path="${HOME}/.config/sublime-text-3"

  if [[ ! -e "${config_path}" ]]
  then
    printf "%s not found. Skipping...\n" "${config_path}"
    exit 0
  fi

  if [[ -L "$osx_prefs_path" ]]
  then
    printf "%s is already a link. Skipping...\n" "${osx_prefs_path}"
    exit 0
  elif [[ ! -d "${osx_prefs_path}" ]]
  then
    printf "%s is not a directory. Skipping...\n" "${osx_prefs_path}"
    exit 0
  elif [[ -e "${osx_prefs_path}.bak" ]]
  then
    printf "%s.bak exists. Manually remove it to proceed. Skipping...\n" \
      "${osx_prefs_path}"
  else
    mv "${osx_prefs_path}" "${osx_prefs_path}.bak"
    ln -s "${config_path}" "${osx_prefs_path}"
  fi
}

link_config
