#!/usr/bin/env bash
###############################################################################
# Atom packages via APM, the Atom Package Manager
#
# Install packages for the Atom text editor using the apm command line tool.
#
# https://github.com/atom/apm
# https://atom.io/packages
# https://atom.io/
###############################################################################

# Get the path to the apm executable.
_apm=$(which apm)

# If the apm command is not found, exit.
if [[ ! -e "${_apm}" ]]
then
  printf "apm not found. Skipping...\n" && exit 0
fi

# override to apm command to do updates when a package is already installed.
#
# Overriding the apm command rather than using a unique function name in order
# to keep the apm install entries in case I want to remove this function, since
# it's not totally necessary and just speeds things up a bit.
apm() {
  if [[ "${1:-}" == "install" ]]
  then
    local local_entry
    local_entry=$(apm ls | grep "${2:-}")
    printf "%s\n" "$local_entry"
    if [[ -z ${local_entry} ]]
    then
      "$_apm" install "${2}"
    fi
  else
    "$_apm" "${@}"
  fi
}

# _apm_package_is_installed()
#
# Usage:
#   _apm_package_is_installed <package-name>
#
# Returns:
#   0  If a package with the given name is installed.
#   1  If not.
_apm_package_is_installed() {
  [[ "$(apm show "${1:-}" &>/dev/null)" ]]
}

###############################################################################
# Upgrade
###############################################################################

# Upgrade without confirmation.
apm upgrade -c false

###############################################################################
# Packages
###############################################################################

# atom-beautify
#
# Beautify HTML, CSS, JavaScript, PHP, Python, Ruby, Java, C, C++, C#,
# Objective-C, CoffeeScript, TypeScript, and SQL in Atom.
#
# https://atom.io/packages/atom-beautify
# https://github.com/Glavin001/atom-beautify
apm install atom-beautify

# atom-dark-ui-slim
#
# Default dark theme for interface components
#
# https://github.com/bmathews/atom-dark-ui-slim
apm install atom-dark-ui-slim

# atom-jshint
#
# Validates your JS against JSHint as you type. The original and most used.
#
# https://github.com/Joezo/atom-jshint
apm install atom-jshint

# atom-material-syntax
#
# A dark syntax theme for Atom that uses Google's Material Design color
# palette.
#
# https://atom.io/themes/atom-material-syntax
# https://github.com/silvestreh/atom-material-syntax
apm install atom-material-syntax

# atom-material-syntax-light
#
# A light syntax theme for Atom that uses Google's Material Design color
# palette.
#
# https://atom.io/themes/atom-material-syntax-light
# https://github.com/silvestreh/atom-material-syntax-light
apm install atom-material-syntax-light

# atom-material-ui
#
# A dark UI theme for Atom that follows Google's Material Design Guidelines.
#
# https://atom.io/themes/atom-material-ui
# https://github.com/silvestreh/atom-material-ui
apm install atom-material-ui

# atom-prettify
#
# Prettify your HTML.
#
# https://atom.io/packages/atom-prettify
# https://github.com/adambutler/atom-prettify
apm install atom-prettify

# atom-simple-dark-ui
#
# Simple default dark theme for interface components
#
# https://github.com/cristianferrarig/atom-simple-dark-ui
apm install atom-simple-dark-ui

# atom-soda-dark-ui
#
#Soda Dark theme for interface components
#
# https://github.com/dmackerman/atom-soda-dark-ui
apm install atom-soda-dark-ui

# atom-typescript
#
# A TypeScript package for Atom.
#
# https://atom.io/packages/atom-typescript
# https://github.com/TypeStrong/atom-typescript
apm install atom-typescript

# autocomplete-plus
#
# Display possible completions in the editor while typing
#
# https://github.com/atom-community/autocomplete-plus
apm install autocomplete-plus

# box-edit
#
# An Atom package to edit rectangular areas; supports short lines.
#
# https://atom.io/packages/box-edit
# https://github.com/mark-hahn/box-edit
# https://discuss.atom.io/t/announce-the-box-edit-package/22621
apm install box-edit

# color-picker
#
# Right click or press CMD-SHIFT-C/CTRL-ALT-C to open it.
#
# https://github.com/thomaslindstrom/color-picker
apm install color-picker

# command-logger
#
# View a treemap of your Atom activity. Open from the command palette.
#
# https://github.com/kevinsawicki/command-logger
apm install "command-logger"

# editor-stats
#
# Display a graph of keyboard and mouse usage for the last 6 hours.
#
# https://github.com/atom/editor-stats
apm install editor-stats

# ex-mode
#
# ex-mode for Atom's vim-mode.
#
# https://atom.io/packages/ex-mode
# https://github.com/lloeki/ex-mode
apm install ex-mode

# file-types
#
# Specify additional file types for languages.
#
# https://atom.io/packages/file-types
# https://github.com/execjosh/atom-file-types
apm install file-types

# fizzy
#
# A light-hearted, bright and bubbly syntax theme featuring bright colors,
# and inspired by the Espresso default highlighting, and the Soda Sublime Text
# 2 theme.
#
# https://github.com/jglovier/fizzy
apm install fizzy

# go-plus
#
# Adds `gocode`, `gofmt`, `goimports`, `go vet`, `golint`, `go build` and
# `go test` functionality for the go language.
#
# https://github.com/joefitzgerald/go-plus
apm install go-plus

# Hydrogen
#
# Run code and get results inline using Jupyter kernels like IPython, IJulia,
# and iTorch
#
# https://atom.io/packages/hydrogen
# https://github.com/willwhitney/hydrogen
apm install Hydrogen

# imdone-atom
#
# A task-board for TODOs, FIXMEs, HACKs, etc in your code.
#
# https://atom.io/packages/imdone-atom
# https://github.com/imdone/imdone-core
apm install imdone-atom

# jumpy
#
# An Atom package that creates dynamic hotkeys to jump around files and across
# visible panes.
#
# https://atom.io/packages/jumpy
# https://github.com/DavidLGoldberg/jumpy
apm install jumpy

# language-generic-config
#
# Provides basic syntax highlighting for configuration files that are just
# composed of comments or non-comments.
#
# https://atom.io/packages/language-generic-config
# https://github.com/lee-dohm/language-generic-config
apm install language-generic-config

# language-haml
#
# HAML package for atom
#
# https://github.com/cannikin/language-haml
apm install language-haml

# language-haskell
#
# Haskell language support in Atom
#
# https://github.com/jroesch/language-haskell
apm install language-haskell

# language-ini
#
# Syntax support for ini files.
#
# https://atom.io/packages/language-ini
# https://github.com/jacobbednarz/atom-language-ini
apm install language-ini

# language-jade
#
# Jade TextMate bundle converted for Atom
#
# https://github.com/devongovett/atom-jade
apm install language-jade

# language-lisp
#
# Lisp support for Atom (converted from Textmate bundle)
#
# https://atom.io/packages/language-lisp
# https://github.com/enriquefernandez/language-lisp
apm install language-lisp

# language-rust
#
# Rust language support in Atom
#
# https://atom.io/packages/language-rust
# https://github.com/zargony/atom-language-rust
apm install language-rust

# language-scala
#
# Scala language support in atom
#
# https://github.com/jroesch/language-scala
apm install language-scala

# language-shellscript
#
# ShellScript package for Atom.
#
# https://atom.io/packages/language-shellscript
# https://github.com/atom/language-shellscript
#
# NOTE: This is a core package and should not be installed separately. However,
# as of this time the bundled package is out of date and the newline-style
# `if..then` support is in version 0.20.0.
# TODO: Remove when the bundled version is at or above 0.20.0.
apm install landuage-shellscript

# language-swift
#
# Swift language support for the Atom editor
#
# https://github.com/freebroccolo/atom-language-swift
apm install language-swift

# language-viml
#
# VimL for Atom.
#
# https://atom.io/packages/language-viml
# https://github.com/EvanHahn/atom-vimL
apm install language-viml

# linter
#
# Validates your code using linter
#
# http://atomlinter.github.io
# https://github.com/AtomLinter/Linter
apm install linter

# linter-chktex
#
# Linter plugin for LaTeX, using chktex
#
# https://atom.io/packages/linter-chktex
# https://github.com/nscaife/linter-chktex
apm install linter-chktex

# linter-clang
#
# Lint C-based files using clang
#
# https://atom.io/packages/linter-clang
# https://github.com/AtomLinter/linter-clang
apm install linter-clang

# linter-clojure
#
# Lint Clojure on the fly, using clojure-x.x.x.jar
#
# https://atom.io/packages/linter-clojure
# https://github.com/AtomLinter/linter-clojure
apm install linter-clojure

# linter-coffeelint
#
# Lint CoffeeScript on the fly, using coffeelint
#
# https://atom.io/packages/linter-coffeelint
# https://github.com/AtomLinter/linter-coffeelint
apm install linter-coffeelint

# linter-crystal
#
# Lint Crystal using the Crystal compiler
#
# https://atom.io/packages/linter-crystal
# https://github.com/atom-crystal/linter-crystal
apm install linter-crystal

# linter-csslint
#
# This linter plugin for Linter provides an interface to csslint. It will be
# used with files that have the “CSS” or “HTML” syntax.
#
# https://atom.io/packages/linter-csslint
# https://github.com/AtomLinter/linter-csslint
apm install linter-csslint

# linter-erlang
#
# Simple erlang linter
#
# https://atom.io/packages/linter-erlang
# https://github.com/RaoH/linter-erlang
apm install linter-erlang

# linter-eslint
#
# Lint JavaScript on the fly, using ESLint
#
# https://atom.io/packages/linter-eslint
# https://github.com/AtomLinter/linter-eslint
apm install linter-eslint

# linter-flow
#
# Lint JavaScript on the fly, using Flow
#
# https://atom.io/packages/linter-flow
# https://github.com/AtomLinter/linter-flow
apm install linter-flow

# linter-haml
#
# Atom linter plugin for HAML, using haml-lint
#
# https://atom.io/packages/linter-haml
# https://github.com/AtomLinter/linter-haml
apm install linter-haml

# linter-hlint
#
# Lint haskell code with hlint
#
# https://atom.io/packages/linter-hlint
# https://github.com/AtomLinter/linter-hlint
apm install linter-hlint

# linter-htmlhint
#
# Linter plugin for HTML, using htmlhint
#
# https://atom.io/packages/linter-htmlhint
# https://github.com/AtomLinter/linter-htmlhint
apm install linter-htmlhint

# linter-jade
#
# Jade linter
#
# https://atom.io/packages/linter-jade
# https://github.com/d9d/atom-linter-jade
apm install linter-jade

# linter-js-yaml
#
# Linter plugin for YAML, using js-yaml
#
# https://atom.io/packages/linter-js-yaml
# https://github.com/AtomLinter/linter-js-yaml
apm install linter-js-yaml

# linter-jshint
#
# Linter plugin for JavaScript, using jshint
#
# https://atom.io/packages/linter-jshint
# https://github.com/AtomLinter/linter-jshint
apm install linter-jshint

# linter-jsonlint
#
# Lint JSON on the fly
#
# https://atom.io/packages/linter-jsonlint
# https://github.com/AtomLinter/linter-jsonlint
apm install linter-jsonlint

# linter-markdown
#
# Lint markdown on the fly, using mdast-lint
#
# https://atom.io/packages/linter-markdown
# https://github.com/AtomLinter/linter-markdown
apm install linter-markdown

# linter-protocol-buffer
#
# Basic protocol buffer linter
#
# https://atom.io/packages/linter-protocol-buffer
# https://github.com/d9d/atom-linter-protocol-buffer
apm install linter-protocol-buffer

# linter-pylama
#
# Lint python on the fly, using pylama. pylama is a wrapper for pylint, pep8,
# pep257, pyflakes and mccabe
#
# https://atom.io/packages/linter-pylama
# https://github.com/AtomLinter/linter-pylama
apm install linter-pylama

# linter-rubocop
#
# Lint `Ruby` on the fly, using rubocop
#
# https://atom.io/packages/linter-rubocop
# https://github.com/AtomLinter/linter-rubocop
apm install linter-rubocop

# linter-ruby
#
# Lint Ruby on the fly, using ruby -wc
#
# https://atom.io/packages/linter-ruby
# https://github.com/AtomLinter/linter-ruby
apm install linter-ruby

# linter-rust
#
# Lint Rust-files, using rustc and/or cargo
#
# https://atom.io/packages/linter-rust
# https://github.com/AtomLinter/linter-rust
apm install linter-rust

# linter-scss-lint
#
# Lint SCSS on the fly, using scss-lint
#
# https://atom.io/packages/linter-scss-lint
# https://github.com/AtomLinter/linter-scss-lint
apm install linter-scss-lint

# linter-shellcheck
#
# Linter plugin for Bash, using shellcheck.
#
# https://github.com/AtomLinter/linter-shellcheck
# https://atom.io/packages/linter-shellcheck
apm install linter-shellcheck

# linter-stylint
#
# Linter plugin for Stylus, using `stylint`.
#
# https://atom.io/packages/linter-stylint
# https://github.com/AtomLinter/linter-stylint
apm install linter-stylint

# linter-swiftc
#
# Lint Swift using swiftc
#
# https://atom.io/packages/linter-swiftc
# https://github.com/AtomLinter/linter-swiftc
apm install linter-swiftc

# linter-tslint
#
# Linter plugin for Typescript, using tslint
#
# https://atom.io/packages/linter-tslint
# https://github.com/AtomLinter/linter-tslint
apm install linter-tslint

# minimap
#
# A preview of the full source code
#
# https://github.com/atom-minimap/minimap
apm install minimap

# monokai
#
# A monokai theme
#
# https://github.com/kevinsawicki/monokai
apm install monokai

# next-dark-ui
#
# Next Dark UI theme
#
# https://github.com/casesandberg/next-dark-ui
apm install next-dark-ui

# Nuclide
#
# An open IDE for web and native mobile development, built on top of Atom.
#
# Nuclide is a collection of packages for Atom to provide IDE-like
# functionality for a variety of programming languages and technologies.
#
# http://nuclide.io/
# https://github.com/facebook/nuclide
# https://code.facebook.com/posts/397706937084869/
apm install nuclide-installer

# pigments
#
# A package to display colors in project and files.
#
# https://atom.io/packages/pigments
# https://github.com/abe33/atom-pigments
apm install pigments

# Seti Syntax
#
# A subtle dark colored theme for Atom.
#
# https://atom.io/themes/seti-syntax
# https://github.com/jesseweed/seti-syntax
apm install seti-syntax

# Seti UI
#
# A dark colored UI theme for Atom with custom file icons
#
# https://atom.io/themes/seti-ui
# https://github.com/jesseweed/seti-ui
apm install seti-ui

# sort-lines
#
# Sorts your lines. Never gets tired
#
# https://github.com/atom/sort-lines
apm install "sort-lines"

# ssh-config
#
# ssh config syntax
#
# https://atom.io/packages/ssh-config
# https://github.com/lalyos/ssh-config
apm install ssh-config

# symbols-tree-view
#
# Symbols Tree View for Atom.io, just like taglist or tagbar for VIM.
#
# https://atom.io/packages/symbols-tree-view
# https://github.com/xndcn/symbols-tree-view
apm install symbols-tree-view

# toggle-quotes
#
# Quickly toggle between single and double quotes
#
# https://github.com/atom/toggle-quotes
apm install toggle-quotes

# trailing-spaces
#
# Highlight trailing whitespace.
#
# https://atom.io/packages/trailing-spaces
# https://github.com/wpillar/atom-trailing-spaces
apm install trailing-spaces

# twilight-syntax
#
# Twilight syntax theme for GitHub's Atom ID
#
# https://github.com/cannikin/twilight-syntax
apm install twilight-syntax

# unity-dark-ui
#
# An atom theme for a more native experience in OS X
#
# https://github.com/rschiang/unity-dark-ui
apm install unity-dark-ui

# vim-mode
#
# Add vim modal control.
#
# https://github.com/atom/vim-mode
apm install vim-mode

# vim-mode-plus
#
# vim-mode improved.
#
# https://atom.io/packages/vim-mode-plus
# https://github.com/t9md/atom-vim-mode-plus
apm install vim-mode-plus

# vim-mode-visual-block
#
# Add visual-block operation to vim-mode.
#
# https://atom.io/packages/vim-mode-visual-block
# https://github.com/t9md/atom-vim-mode-visual-block
apm install vim-mode-visual-block

# visual-bell
#
# Shows a visual cue when the `beep` event is triggered
#
# https://github.com/probablycorey/visual-bell
apm install visual-bell

# Sublime-Style-Column-Selection
#
# Enable Sublime style 'Column Selection'. Just hold 'alt' while you
# select. Also similar to Texmate's 'Multiple Carets', or BBEdit's 'Block
# Select'
#
# https://github.com/bigfive/atom-sublime-select
apm install Sublime-Style-Column-Selection

# Zen
#
# Distraction free writing.
#
# https://github.com/defunkt/zen
apm install Zen
