#!/usr/bin/env bash
#
# apt-packages

###############################################################################
# Platform Check
###############################################################################

if [[ ! "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]]; then
  printf "apt-packages is only supported on Ubuntu.\nSkipping...\n"
  exit 0
fi

###############################################################################
# Packages
###############################################################################

# ack-grep (ack)
#
# grep-like program specifically for large source trees
#
# http://beyondgrep.com/
# http://packages.ubuntu.com/trusty/ack-grep
sudo apt-get install -y ack-grep

# build-essential
#
# Informational list of build-essential packages
#
# http://packages.ubuntu.com/trusty/build-essential
sudo apt-get install -y build-essential

# curl
#
# command line tool for transferring data with URL syntax
#
# http://packages.ubuntu.com/trusty/curl
# http://curl.haxx.se/
sudo apt-get install -y curl

# dnsutils
#
# Clients provided with BIND
#
# http://packages.ubuntu.com/trusty/dnsutils
sudo apt-get install -y dnsutils

# emacs
#
# GNU Emacs editor (metapackage)
#
# http://packages.ubuntu.com/trusty/emacs
sudo apt-get install -y emacs

# finger
#
# user information lookup program
#
# http://packages.ubuntu.com/trusty/finger
sudo apt-get install -y finger

# gnutls-bin
#
# GNU TLS library - commandline utilities
#
# http://packages.ubuntu.com/trusty/gnutls-bin
sudo apt-get install -y gnutls-bin

# less
#
# pager program similar to more
#
# http://packages.ubuntu.com/trusty/less
sudo apt-get install -y less

# libssl-dev
#
# Secure Sockets Layer toolkit - development files
#
# http://packages.ubuntu.com/trusty/libssl-dev
sudo apt-get install -y libssl-dev

# mercurial
#
# easy-to-use, scalable distributed version control system
#
# http://packages.ubuntu.com/trusty/mercurial
# http://mercurial.selenic.com/
sudo apt-get install -y mercurial

# screen
#
# terminal multiplexer with VT100/ANSI terminal emulation
#
# http://packages.ubuntu.com/trusty/screen
sudo apt-get install -y screen

# tmux
#
# terminal multiplexer
#
# http://packages.ubuntu.com/trusty/tmux
# http://tmux.sourceforge.net/
# https://en.wikipedia.org/wiki/Tmux
sudo apt-get install -y tmux

# unzip
#
# De-archiver for .zip files
#
# http://packages.ubuntu.com/trusty/unzip
sudo apt-get install -y unzip

# vim
#
# Vi IMproved - enhanced vi editor
#
# http://packages.ubuntu.com/trusty/vim
sudo apt-get install -y vim

# wget
#
# retrieves files from the web
#
# http://packages.ubuntu.com/trusty/wget
sudo apt-get install -y wget

# zsh
#
# shell with lots of features
#
# http://packages.ubuntu.com/trusty/zsh
sudo apt-get install -y zsh
