#!/usr/bin/env bash
###############################################################################
# apt-packages
###############################################################################

###############################################################################
# Platform Check
###############################################################################

if ! hash "apt-get" 2>/dev/null
then
  printf "apt-packages requires APT.\nSkipping...\n"
  exit 0
fi

###############################################################################
# Update package lists
###############################################################################

sudo apt-get update

###############################################################################
# Package Scripts
###############################################################################

# Get the current directory path.
#
# This is a more explicit derivative of the following:
# http://stackoverflow.com/a/246128
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]
then
  DIR="$PWD"
fi

# Source primary install scripts for Homebrew and Homewbrew Cask.
. "$DIR/apt-packages.d/apt-ctf-tools"
. "$DIR/apt-packages.d/apt-base-packages"
. "$DIR/apt-packages.d/apt-ruby-build-packages"
