#!/usr/bin/env bash
###############################################################################
# bpkg-packages
#
# Install various bpkg (bash package manager) packages
#
# http://www.bpkg.io/
# https://github.com/bpkg/bpkg
###############################################################################

###############################################################################
# Setup
###############################################################################

# PREFIX ---------------------------------------------------------------------

# In order to keep bpkg-installed programs separated from everything else,
# place installed items in ~/.bpkg/bin, which needs to be added to the $PATH.

export PREFIX="$HOME/.bpkg"

if [[ ! -e "$PREFIX" ]]
then
  mkdir -p "$PREFIX"
fi

###############################################################################
# Packages
###############################################################################

# C
#
# Compile and execute C "scripts" in one go!
#
# https://github.com/ryanmjacobs/c
# https://news.ycombinator.com/item?id=9144467

# Temporarily set PREFIX to $HOME to ensure installation in $HOME/bin
# https://github.com/ryanmjacobs/c/blob/master/package.json#L6
bpkg install -g ryanmjacobs/c

# Clock
#
# Track your working hours on the command line.
#
# https://github.com/lordvlad/clock
bpkg install -g lordvlad/clock

# clip
#
# Silly terminal clipboard
#
# https://github.com/bpkg/clip
# http://www.bpkg.io/pkg/clip/
bpkg install -g clip

# mush
#
# Mustache templates for bash
#
# https://github.com/jwerle/mush
bpkg install -g jwerle/mush

# osx-screencast
#
# Easily create a screencast on OS X in a few commands.
#
# https://github.com/bpkg/osx-screencast
bpkg install -g osx-screencast
