#!/usr/bin/env bash
###############################################################################
# bpkg-packages
#
# Install various bpkg (bash package manager) packages
#
# http://www.bpkg.io/
# https://github.com/bpkg/bpkg
###############################################################################

###############################################################################
# Setup
###############################################################################

# PREFIX ---------------------------------------------------------------------

# In order to keep bpkg-installed programs separated from everything else,
# place installed items in ~/.bpkg/bin, which needs to be added to the $PATH.

export PREFIX="$HOME/.local"

if [[ ! -e "$PREFIX" ]]; then
  mkdir -p "$PREFIX"
fi

###############################################################################
# Packages
###############################################################################

# C
#
# Compile and execute C "scripts" in one go!
#
# https://github.com/ryanmjacobs/c
# https://news.ycombinator.com/item?id=9144467

# Temporarily set PREFIX to $HOME to ensure installation in $HOME/bin
# https://github.com/ryanmjacobs/c/blob/master/package.json#L6
bpkg install -g ryanmjacobs/c

# clip
#
# Silly terminal clipboard
#
# https://github.com/bpkg/clip
# http://www.bpkg.io/pkg/clip/
bpkg install -g clip

###############################################################################
# Cleanup
###############################################################################

unset PREFIX
