#!/usr/bin/env bash
#
# brew-all
#
# Install programs and applications using Homebrew and Homebrew Cask.

###############################################################################
# Platform Check
###############################################################################

# Exit unless OS X
if [[ ! "$OSTYPE" =~ ^darwin ]]; then
  printf "brew-all is only supported on OS X\nSkipping...\n"
  exit 0
fi

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/brew-formulae"
. "$DIR/brew-casks"

