#!/usr/bin/env bash
###############################################################################
# brew-casks
#
# Install programs and applications using Homebrew and Homebrew Cask.
#
# http://brew.sh/
# http://caskroom.io/
###############################################################################

###############################################################################
# Platform Check
###############################################################################

if [[ ! "$OSTYPE" =~ ^darwin ]]; then
  printf "brew-casks is only supported on OS X\nSkipping...\n"
  exit 0
fi

###############################################################################
# Homebrew - Update
###############################################################################

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade --all

###############################################################################
# Homebrew Cask
###############################################################################

# install brew cask
brew install caskroom/cask/brew-cask

###############################################################################
# Homebrew Cask - Taps
#
# `brew tap` allows you to add more Github repos to the list of formulae that
# brew tracks, updates and installs from.
###############################################################################

# homebrew-cask-versions
#
# Alternate versions of Casks for homebrew-cask
#
# https://github.com/caskroom/homebrew-versions
brew tap caskroom/versions

# Caskroom-fonts
#
# Caskroom-fonts is a Homebrew Tap which allows you to use the same friendly
# Homebrew-style CLI workflow for the administration of binary font files on
# your Mac.
#
# https://github.com/caskroom/homebrew-fonts
brew tap caskroom/fonts

###############################################################################
# Homebrew Cask - Fonts
###############################################################################

# Sauce Code Powerline
#
# Source Code Pro is a set of monospaced OpenType fonts that have been designed
# to work well in coding environments. This family of fonts is a complementary
# design to the Source Sans family. Sauce Code Powerline is derived from Source
# Code Pro for Powerline users.
#
# https://github.com/powerline/fonts/tree/master/SourceCodePro
brew cask install font-sauce-code-powerline

# Office Code Pro
#
# Office Code Pro is a customized version of the Source Code Pro type family,
# originally created for Adobe Systems Incorporated by Paul D. Hunt. The
# customizations were made specifically for text editors and coding
# environments, but are still very usable in other applications.
#
# https://github.com/nathco/Office-Code-Pro
brew cask install font-office-code-pro

###############################################################################
# Homebrew Cask - Applications
###############################################################################

# VirtualBox
#
# VirtualBox is a powerful x86 and AMD64/Intel64 virtualization product.
#
# http://www.virtualbox.org
#
# NOTES:
#   - Installing first since it's important and other casks use it.
#   - Installation fails if a VM is running. If this happens, check from
#     running VMs, such as a boot2docker VM.
brew cask install virtualbox

# 1Password
#
# Password manager and secure wallet
#
# https://agilebits.com/onepassword
brew cask install 1password

# Adium
#
# Adium is a free instant messaging application for Mac OS X that can connect
# to AIM, MSN, XMPP (Jabber), Yahoo, and more.
#
# https://adium.im/
brew cask install adium

# Amethyst
#
# Tiling window manager for OS X similar to xmonad, written in pure
# Objective-C.
#
# http://ianyh.com/amethyst/
brew cask install amethyst

# Android Studio
#
# https://developer.android.com/sdk/index.html
brew cask install android-studio

# Atom
#
# A hackable text editor for the 21st Century.
#
# http://atom.io
brew cask install atom

# Audacity
#
# Audacity® is free, open source, cross-platform software for recording and
# editing sounds.
#
# http://audacity.sourceforge.net/
brew cask install audacity

# AU Lab
#
# Apple’s free digital audio mixing application, AU Lab, can be used as a host
# application for Audio Unit effects, including AURoundTripAAC Audio Unit, one
# of the new Mastered for iTunes tools.
#
# http://www.apple.com/itunes/mastered-for-itunes/
brew cask install au-lab

# BibDesk - Mac Bibliography Manager
#
# Use BibDesk to edit and manage your bibliography. It will keep track of both
# the bibliographic information and the associated files or web links for you.
# BibDesk’s services will simplify using your bibliography in other
# applications and are particularly well suited for LATEX users.
#
# http://bibdesk.sourceforge.net/
brew cask install bibdesk

# bittorrent-sync
#
# Fast, private file sharing for teams and individuals.
#
# http://www.bittorrent.com/sync
# https://www.getsync.com/
brew cask install bittorrent-sync

# Blender
#
# Blender is a free and open source 3D animation suite.
#
# http://www.blender.org/
brew cask install blender

# Brackets
#
# Adobe's open source text editor built with and focused on web technologies.
#
# http://brackets.io
brew cask install brackets

# Breach
#
# A new modular browser. Entirely written in Javascript. Free. Hackable.
#
# http://breach.cc
brew cask install breach

# Boot2Docker Status
#
# Status bar application to manage the state of your Boot2Docker VM.
#
# http://boot2docker-status.nickgartmann.com/
# https://github.com/nickgartmann/boot2docker-status
brew cask install "boot2docker-status"

# Cakebrew
#
# The Mac App for Homebrew.
#
# http://www.cakebrew.com
brew cask install cakebrew

# Calibre
#
# calibre is a free and open source e-book library management application
# developed by users of e-books for users of e-books.
#
# http://calibre-ebook.com/
brew cask install calibre

# Codebox
#
# Open source cloud & desktop IDE.
#
# https://www.codebox.io
brew cask install codebox

# Colors
#
# Colors is a color picker that takes Apple's basic color chooser (complete
# with "magnifying glass" to pull colors from other applications), and combines
# it with an easy way to copy common formats of color values (eg., #rrggbb,
# rgba(r, g, b, a), etc.) to the clipboard.
#
# http://mattpatenaude.com/
brew cask install colors

# Consul
#
# Consul is a tool for service discovery, monitoring and configuration.
#
# http://www.consul.io/
brew cask install consul

# Context Free
#
# Context Free is a program that generates images from written instructions
# called a grammar. The program follows the instructions in a few seconds to
# create images that can contain millions of shapes.
#
# http://www.contextfreeart.org/
brew cask install context-free

# coqide
#
# a graphical user interface based on gtk (CoqIde) for coq.
#
# NOTE: see `brew install coq` in `brew-programs`.
#
# https://coq.inria.fr/
brew cask install coqide

# CotEditor
#
# Lightweight Plain-Text Editor for OS X.
#
# http://coteditor.com/
# https://github.com/coteditor/CotEditor
brew cask install coteditor

# Disk Inventory X
#
# Disk Inventory X is a disk usage utility for Mac OS X 10.3 (and later). It
# shows the sizes of files and folders in a special graphical way called
# "treemaps".
#
# http://www.derlien.com/
brew cask install disk-inventory-x

# Docear
#
# Free and Open Source Academic Literature Suite
#
# Docear (pronounced dog-ear) is what we call an “academic literature suite”.
# It integrates everything you need to search, organize and create academic
# literature in a single application: a digital library, reference manager,
# PDF and file manager, note taking and mind mapping. And the best: Docear
# works seemlessly with many existing tools like Mendeley, Microsoft Word, and
# Foxit Reader.
#
# Docear is free and open source, based on Freeplane, funded by the German
# Federal Ministry of Technology and developed by scientists from around the
# world, among others from OvGU, and the University of California, Berkeley.
#
# http://www.docear.org/
# http://sourceforge.net/projects/docear/
brew cask install docear

# Elm
#
# A functional reactive language for interactive applications
#
# http://www.elm-lang.org
brew cask install elm-platform

# Facter
#
# Facter gathers basic facts about nodes (systems) such as hardware details,
# network settings, OS type and version, IP addresses, MAC addresses, SSH keys
# and more. These facts are then made available in your Puppet manifests as
# variables.
#
# https://puppetlabs.com/facter
brew cask install facter

# Factor
#
# The Factor programming language combines powerful language features with a
# full-featured library. Factor belongs to the family of concatenative
# languages: this means that, at the lowest level, a Factor program is a
# series of words (functions) that manipulate a stack of references to
# dynamically-typed values. This gives the language a powerful foundation
# which allows many abstractions and paradigms to be built on top.
#
# http://factorcode.org/
brew cask install factor

# Firefox
#
# A free and open-source web browser.
#
# https://www.mozilla.org/en-US/firefox/
brew cask install firefox

# Firefox Developer Edition
#
# A distribution of the Firefox web browser designed for developers.
#
# https://www.mozilla.org/en-US/firefox/developer/
brew cask install firefoxdeveloperedition

# Gimp
#
# GIMP is the GNU Image Manipulation Program. It is a freely distributed piece
# of software for such tasks as photo retouching, image composition and image
# authoring.
#
# http://www.gimp.org
brew cask install gimp

# GnuCash
#
# GnuCash is open source personal and small-business financial-accounting
# software.
#
# http://www.gnucash.org
brew cask install gnucash

# gridwars
#
# GridWars or GridWars 2 is a computer game inspired by Bizarre Creations'
# Geometry Wars developed by Marco Incitti.
#
# http://gridwars.marune.de/
brew cask install gridwars

# Google Chrome
#
# A freeware web browser developed by Google.
#
# https://www.google.com/chrome/
brew cask install google-chrome

# gpgtools / GPG Suite
#
# Everything you need to get started with secure communication and encrypting
# files in one simple package. Use GPG Suite to encrypt, decrypt, sign and
# verify files or messages. Manage your GPG Keychain with a few simple clicks
# and experience the full power of GPG easier than ever before.
#
# https://gpgtools.org/
brew cask install gpgtools

# The Haskell Platform
#
# http://www.haskell.org/platform/
brew cask install haskell-platform

# Hammerspoon
#
# Hammersppon is a tool for powerful automation of OS X. At its core,
# Hammerspoon is just a bridge between the operating system and a Lua
# scripting engine. What gives Hammerspoon its power is a set of extensions
# that expose specific pieces of system functionality, to the user.
#
# Hammerspoon is a fork of Mjolnir by Steven Degutis. Mjolnir aims to be a very
# minimal application, with its extensions hosted externally and managed using
# a Lua package manager. We felt that we wanted to take the project in a
# different direction to its maintainer, so the fork was born.
#
# http://www.hammerspoon.org/
# https://github.com/Hammerspoon/hammerspoon
brew cask install hammerspoon

# Inform
#
# Inform is a design system for interactive fiction based on natural language.
# It is a radical reinvention of the way interactive fiction is designed,
# guided by contemporary work in semantics and by the practical experience of
# some of the world's best-known writers of IF.
#
# http://inform7.com/
#
# Additional links and resources:
#
# https://news.ycombinator.com/item?id=9279639
brew cask install inform

# Inkscape
#
# Inkscape is an open-source vector graphics editor similar to Adobe
# Illustrator, Corel Draw, Freehand, or Xara X that used Scalable Vector
# Graphics (SVG), an open XML-based W3C standard, as the native format.
#
# https://inkscape.org/en/
brew cask install inkscape

# iTerm2
#
# iTerm2 is a replacement for Terminal and the successor to iTerm.
#
# http://www.iterm2.com/
brew cask install iterm2-nightly

# KindleGen
#
# KindleGen is a command line tool which enables publishers to work in an
# automated environment with a variety of source content including HTML, XHTML
# or EPUB. KindleGen converts this source content to a single file which
# supports both KF8 and Mobi formats enabling publishers to create
# great-looking books that work on all Kindle devices and apps.
#
# http://www.amazon.com/gp/feature.html?docId=1000765211
brew cask install kindlegen

# Kitematic
#
# Kitematic is a simple application for managing Docker containers on Mac OS X.
#
# https://kitematic.com/
# https://github.com/kitematic/kitematic
brew cask install kitematic

# Krita
#
# Krita is a digital painting and illustration application.
#
# https://krita.org/
brew cask install krita

# LibreOffice
#
# LibreOffice is a free and open source office suite, developed by The Document
# Foundation. It was forked from OpenOffice.org in 2010, which was an
# open-sourced version of the earlier StarOffice. The LibreOffice suite
# comprises programs to do word processing, spreadsheets, slideshows, diagrams
# and drawings, maintain databases, and compose mathematical formulae.
#
# http://www.libreoffice.org/
brew cask install libreoffice

# Light Table
#
# A text editor and IDE build with JavaScript.
#
# http://www.lighttable.com/
# https://github.com/LightTable/LightTable
brew cask install lighttable

# LyX – The Document Processor
#
# LyX is a document processor that encourages an approach to writing based on
# the structure of your documents (WYSIWYM) and not simply their appearance
# (WYSIWYG). LyX combines the power and flexibility of TeX/LaTeX with the ease
# of use of a graphical interface.
#
# http://www.lyx.org/Home
#
# NOTE: as of LyX version 2.1.3, retina / hidpi display is still suboptimal,
# with text blurred in the main work area. There are patches in the wild, but
# none have apparently been applied at this time.
brew cask install lyx

# Macfusion
#
# Macfusion brings servers from across the internet directly to your Mac's
# desktop. Mount files and documents as a "Volume" in the Mac OS X Finder.
# Support for SSH (Secure Shell) and FTP (File Transfer Protocol) servers.
#
# http://macfusionapp.org/
brew cask install macfusion

# MacTex
#
# MacTeX is an OS X-specific redistribution of TeX Live, a typesetting
# environment.
#
# http://www.tug.org/mactex/
brew cask install mactex

# MAME
#
# MAME stands for Multiple Arcade Machine Emulator. When used in conjunction
# with images of the original arcade game's ROM and disk data, MAME attempts
# to reproduce that game as faithfully as possible on a more modern
# general-purpose computer. MAME can currently emulate several thousand
# different classic arcade video games from the late 1970s through the modern
# era.
#
# http://mamedev.org/
# https://github.com/mamedev/mame
# http://mameosx.sourceforge.net/
brew cask install mame

# Mapbox Studio
#
# Design radically custom maps and datasets powered by vector tiles.
#
# https://www.mapbox.com/mapbox-studio/
brew cask install mapbox-studio

# Monodraw
#
# Powerful ASCII art editor designed for the Mac.
#
# http://monodraw.helftone.com/
brew cask install monodraw

# Monu
#
# Monu is an open source process monitoring menu bar application for Mac OS.
# You can configure Monu to launch programs, and when Monu starts up it will
# start them. Additionally, it will monitor the processes and restart them if
# they crash.
#
# https://github.com/maxogden/monu
brew cask install monu

# Natron
#
# Natron is an open-source • crossplatform nodal • compositing software
#
# https://natron.inria.fr/
brew cask install natron

# nvALT
#
# nvALT 2 is a fork of the original Notational Velocity with some additional
# features and interface modifications, including MultiMarkdown functionality.
#
# http://brettterpstra.com/projects/nvalt/
brew cask install nvalt

# OpenSCAD
#
# OpenSCAD is a software for creating solid 3D CAD models. It is free software
# and available for Linux/UNIX, Windows and Mac OS X. Unlike most free
# software for creating 3D models (such as Blender) it does not focus on the
# artistic aspects of 3D modelling but instead on the CAD aspects. Thus it
# might be the application you are looking for when you are planning to
# create 3D models of machine parts but pretty sure is not what you are
# looking for when you are more interested in creating computer-animated
# movies.
#
# http://www.openscad.org/
brew cask install openscad

# Origami - Design Prototyping
#
# Origami is a free tool for designing modern user interfaces. Quickly put
# together a prototype, run it on your iPhone or iPad, iterate on it, and
# export code snippets.
#
# http://facebook.github.io/origami/
brew cask install origami

# osxfuse - FUSE for OS X
#
# The easiest and fastest way to create filesystems for OS X. FUSE for OS X
# allows you to extend OS X's native file handling capabilities via third-party
# file systems. OSXFUSE is a successor to MacFUSE.
#
# https://osxfuse.github.io/
#
# NOTE: There is a vanilla Homebrew osxfuse formula, but it can't be
# installed on Yosemite because of the unsigned kext ban.
brew cask install osxfuse

# Packer
#
# Packer is a tool for creating identical machine images for multiple platforms
# from a single source configuration.
#
# http://www.packer.io/
brew cask install packer

# pd-extended - PureData
#
# Pure Data (aka Pd) is an open source visual programming language. Pd enables
# musicians, visual artists, performers, researchers, and developers to create
# software graphically, without writing lines of code.
#
# http://puredata.info/
# http://puredata.info/downloads/pd-extended
brew cask install pd-extended

# Pencil
#
# Multiplatform GUI Prototyping/Wireframing
#
# https://github.com/prikhi/pencil
brew cask install pencil

# pgAdmin
#
# pgAdmin is the most popular and feature rich Open Source administration and
# development platform for PostgreSQL
#
# http://pgadmin.org
brew cask install pgadmin3

# Pharo
#
# Pharo is a pure object-oriented programming language and a powerful
# environment, focused on simplicity and immediate feedback (think IDE and
# OS rolled into one).
#
# http://pharo.org/
brew cask install pharo

# Postgres.app
#
# Postgres.app contains a full-featured PostgreSQL installation in a single
# package.
#
# http://postgresapp.com/
brew cask install postgres

# processing3
#
# Processing is an open source programming language and integrated development
# environment (IDE) built for the electronic arts, new media art, and visual
# design communities with the purpose of teaching the fundamentals of computer
# programming in a visual context, and to serve as the foundation for
# electronic sketchbooks.
#
# NOTE: processing3 is the alpha for the upcoming version 3.
#
# https://processing.org
brew cask install processing3

# RetroArch / libretro
#
# RetroArch is the reference frontend for the libretro API. Popular examples of
# implementations for this API includes videogame system emulators and game
# engines, but also more generalized 3D programs. These programs are
# instantiated as dynamic libraries. We refer to these as "libretro cores".
#
# https://github.com/libretro/RetroArch
# http://www.libretro.com/
brew cask install retroarch

# rowanj-gitx
#
# GitX-dev is a fork (variant) of GitX, a long-defunct GUI for the git
# version-control system. It has been maintained and enhanced with productivity
# and friendliness oriented changes, with effort focused on making a
# first-class, maintainable tool for today's active developers.
#
# http://rowanj.github.io/gitx/
# https://github.com/rowanj/gitx
brew cask install rowanj-gitx

# Rust (Rust Nightly)
#
# Rust is a systems programming language that runs blazingly fast, prevents
# almost all crashes, and eliminates data races.
#
# http://www.rust-lang.org/
#
# Also installs Cargo
#
# Cargo is a tool that allows Rust projects to declare their various
# dependencies, and ensure that you'll always get a repeatable build.
#
# https://crates.io/
brew cask install rust

# Scribus
#
# Scribus is an Open Source program that brings professional page layout to
# Linux, BSD UNIX, Solaris, OpenIndiana, GNU/Hurd, Mac OS X, OS/2 Warp 4,
# eComStation, Windows and Haiku desktops with a combination of press-ready
# output and new approaches to page design.
#
# Underneath a modern and user-friendly interface, Scribus supports
# professional publishing features, such as color separations, CMYK and spot
# colors, ICC color management, and versatile PDF creation.
#
# http://www.scribus.net/canvas/Scribus
brew cask install scribus

# Secrets
#
# A database of hidden settings for Mac OS X
#
# http://secrets.blacktree.com
brew cask install secrets

# Sequel Pro
#
# A fast, easy-to-use Mac database management application for working with
# MySQL databases.

# http://www.sequelpro.com/
brew cask install sequel-pro

# SmartGit
#
# SmartGit is a Git client with support for GitHub Pull Requests+Comments,
# SVN, and Mercurial.
#
# http://www.syntevo.com/smartgit/
brew cask install smartgit

# Sonic Pi
#
# Audible Computing. A free sound synthesiser for live coding designed to
# support computing and music lessons within schools. Make Music Using Ruby.
#
# http://sonic-pi.net/
brew cask install sonic-pi

# Sonic Visualiser
#
# Sonic Visualiser is an application for viewing and analysing the contents of
# music audio files.
#
# http://www.sonicvisualiser.org/
brew cask install sonic-visualiser

# Soundflower
#
# Soundflower is a MacOS system extension that allows applications to pass
# audio to other applications. Soundflower is easy to use, it simply presents
# itself as an audio device, allowing any audio application to send and receive
# audio with no other support needed.
#
# https://code.google.com/p/soundflower/
brew cask install soundflower

# Soundnode
#
# Soundnode App is a Open-Source project to support Soundcloud for desktop.
# Built with Node-Webkit, Node.js, Angular.js and consuming Soundcloud API.
#
# http://www.soundnodeapp.com/
# https://github.com/Soundnode/soundnode-app
brew cask install soundnode

# Spectacle
#
# Move and resize windows with ease. Window control with simple, customizable
# keyboard shortcuts.
#
# http://spectacleapp.com
brew cask install spectacle

# Spotify
#
# A commercial music streaming service.
#
# https://www.spotify.com
brew cask install spotify

# sublime-text3
#
# Sublime Text is a text editor for code, markup and prose.
#
# http://www.sublimetext.com/
# http://www.sublimetext.com/3
brew cask install sublime-text3

# Sunvox
#
# SunVox is a small, fast and powerful modular synthesizer with pattern-based
# sequencer (tracker). It is a tool for those people who like to compose music
# wherever they are, whenever they wish.
#
# http://www.warmplace.ru/soft/sunvox/
brew cask install sunvox

# swi-prolog
#
# SWI-Prolog offers a comprehensive free Prolog environment. Since its start in
# 1987, SWI-Prolog development has been driven by the needs of real world
# applications.
#
# http://www.swi-prolog.org/
brew cask install swi-prolog

# TeXShop
#
# TeXShop is a TeX previewer for Mac OS X, written in Cocoa. Since pdf is a
# native file format on OS X, TeXShop uses "pdftex" and "pdflatex" rather
# than "tex" and "latex" to typeset in its default configuration; these
# programs in the standard TeX Live distribution of TeX produce pdf output
# instead of dvi output.
#
# http://pages.uoregon.edu/koch/texshop
brew cask install texshop

# Textadept
#
# A fast, minimalist, and remarkably extensible cross-platform text editor
#
# http://foicica.com/textadept/
brew cask install textadept

# Thunderbird
#
# Mozilla Thunderbird is a free, open source, cross-platform email, news, and
# chat client developed by the Mozilla Foundation.
#
# http://www.mozilla.org/en-US/thunderbird/
brew cask install thunderbird

# Twine
#
# Twine is an open-source tool for telling interactive, nonlinear stories. You
# don't need to write any code to create a simple story with Twine, but you
# can extend your stories with variables, conditional logic, images, CSS, and
# JavaScript when you're ready. Twine publishes directly to HTML, so you can
# post your work nearly anywhere. Anything you create with it is completely
# free to use any way you like, including for commercial purposes.
#
# http://twinery.org/
brew cask install twine

# UnicodeChecker
#
# Exploration Unicode number and UTF encodings for each codepoint • Related
# codepoints and decomposition • Browsing by plane, codepoint number or
# character block • Unihan data such as definitions, variants, pronunciations
# and older encodings for many Asian codepoints • Finding code points by name
# or their Unihan definition • Finding codepoints via Spotlight.
#
# Conversion To and from: HTML, CSS, URLs, IDNA and various programming
# languages • Unicode Normalisation with an indication whether the string is
# already normalised (NFC, NFKC, NFD and NFKD) • Split Up and Diff tools to
# analyse a string codepoint by codepoint and highlight the differences • Most
# of the features are available to all applications you use via the ‘Services’
# menu and AppleScript.
#
# http://earthlingsoft.net/UnicodeChecker/
#
# NOTE: there is an official cask for this application, but it's outdated.
# Experimenting with own cask localy.
brew cask install alphabetum/taps/unicodechecker

# Unity
#
# Unity is a flexible and powerful development platform for creating
# multiplatform 3D and 2D games and interactive experiences.
#
# http://unity3d.com/unity/
brew cask install unity

# Vagrant
#
# Create and configure lightweight, reproducible, and portable development
# environments.
#
# http://www.vagrantup.com
brew cask install vagrant

# Vault
#
# Vault is a tool for securely accessing secrets. A secret is anything that you
# want to tightly control access to, such as API keys, passwords, certificates,
# and more. Vault provides a unified interface to any secret, while providing
# tight access control and recording a detailed audit log.
#
# https://www.vaultproject.io
# https://github.com/hashicorp/vault
brew cask install vault

# Vico
#
# Vico is a programmers text editor with a strong focus on keyboard control and
# uses vi key bindings.
#
# http://www.vicoapp.com
brew cask install vico

# VimR
#
# A Vim GUI for OS X
#
# http://vimr.org/
brew cask install vimr

# Visual Studio Code
#
# An editor built with Electron.
#
# https://code.visualstudio.com/
brew cask install visual-studio-code

# Vivaldi
#
# A web browser.
#
# https://vivaldi.com
brew cask install vivaldi

# VLC - vlc-nightly
#
# VLC is a free and open source cross-platform multimedia player and framework
# that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and
# various streaming protocols.
#
# http://www.videolan.org/vlc/
brew cask install vlc-nightly

# XQuartz
#
# The XQuartz project is an open-source effort to develop a version of the
# X.Org X Window System that runs on OS X. Together with supporting libraries
# and applications, it forms the X11.app that Apple has shipped with OS X since
# version 10.5.
#
# http://xquartz.macosforge.org/landing/
brew cask install xquartz

# Zed
#
# Zed is a fully offline-capable, open source, keyboard-focused, text and code
# editor for power users.
#
# http://zedapp.org
brew cask install zed

###############################################################################
# Cleanup
###############################################################################

# Remove outdated versions.
brew cask cleanup

###############################################################################
# Application Aliasing
#
# Custom brew commands for creating spotlight-recognizable application aliases.
#
# Uses the alias-app command line tool: https://github.com/alphabetum/alias-app
###############################################################################

brew cask aliasapps

