#!/usr/bin/env bash
################################################################################
# brew-forumlae
#
# Install programs and applications using Homebrew.
#
# http://brew.sh/
###############################################################################

###############################################################################
# Platform Check
###############################################################################

if [[ ! "$OSTYPE" =~ ^darwin ]]
then
  printf "brew-formulae is only supported on OS X\nSkipping...\n"
  exit 0
fi

###############################################################################
# Homebrew - Update
###############################################################################

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade --all

###############################################################################
# Homebrew - Taps
#
# `brew tap` allows you to add more Github repos to the list of formulae that
# brew tracks, updates and installs from.
#
###############################################################################

# alphabetum-taps
#
# My custom taps.
#
# https://github.com/alphabetum/homebrew-taps
brew tap alphabetum/taps

# bramstein/webfonttools
#
# Homebrew web font tools
#
# https://github.com/bramstein/homebrew-webfonttools
brew tap bramstein/webfonttools

# homebrew-completions
#
# Shell completion formulae for the Homebrew package manager
#
# https://github.com/Homebrew/homebrew-completions
brew tap homebrew/completions

# homebrew devel-only
#
# These formulae are only available as pre-release versions and have no stable
# tarballs.
#
# https://github.com/Homebrew/homebrew-devel-only
brew tap homebrew/devel-only

# homebrew-dupes
#
# These formulae duplicate software provided by OS X, though may provide more
# recent or bugfix versions.
#
# https://github.com/Homebrew/homebrew-dupes
brew tap homebrew/dupes

# homebrew-games
#
# Game formulae for the Homebrew package manager
#
# https://github.com/Homebrew/homebrew-games
brew tap homebrew/games

# homebrew-head-only
#
# These formulae are unversioned (they have no stable release) so are only
# available as the latest version from e.g. a version control system.
#
# https://github.com/Homebrew/homebrew-head-only
brew tap homebrew/head-only

# homebrew-python
#
# Homebrew formulae to install Python 2.x and 3.x libraries, which are not yet
# well supported by pip install due to compiler and dependency issues.
#
# https://github.com/Homebrew/homebrew-python
brew tap homebrew/python

# homebrew-science
#
# These formulae provide software tailored to scientific endeavours. Need to
# store large amounts of data in a sparse matrix, solve a huge optimization
# problem or process the images from your space telescope? Maybe we can help!
#
# https://github.com/Homebrew/homebrew-science
brew tap homebrew/science

# brew tap manastech-crystal
#
# Formulae for the Crystal Programming Language.
#
# https://github.com/manastech/homebrew-crystal
# https://github.com/manastech/crystal
# http://crystal-lang.org/
brew tap manastech/crystal

# homebrew-neovim
#
# Homebrew formula for neovim.
#
# https://github.com/neovim/homebrew-neovim
brew tap neovim/homebrew-neovim

# railwaycat/emacsmacport
#
# Emacs mac port formulae for the Homebrew package manager
#
# https://github.com/railwaycat/homebrew-emacsmacport
brew tap railwaycat/emacsmacport

# brew-desc.rb
#
# Searchable descriptions for Homebrew formulas
#
# https://github.com/telemachus/homebrew-desc
brew tap telemachus/homebrew-desc

# thoughtbot/formulae
#
# A Homebrew tap for various thoughtbot projects.
#
# https://github.com/thoughtbot/homebrew-formulae
brew tap thoughtbot/formulae

###############################################################################
# Homebrew - Core Formula
#
# Formulae that override or supercede utilities included with OS X, plus some
# additional core utilities.
###############################################################################

# GCC, the GNU Compiler Collection
#
# The GNU Compiler Collection includes front ends for C, C++, Objective-C,
# Fortran, Java, Ada, and Go, as well as libraries for these languages
# (libstdc++, libgcj,...). GCC was originally written as the compiler for the
# GNU operating system. The GNU system was developed to be 100% free software,
# free in the sense that it respects the user's freedom.
#
# http://gcc.gnu.org
#
# NOTE: languages built: c c++ objc obj-c++ fortran
brew install gcc

# GNU Core Utilities
#
# For using in place of outdated OS X versions.
#
# https://www.gnu.org/software/coreutils
#
# NOTE: To use, add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils

# moreutils
#
# moreutils is a growing collection of the unix tools that nobody thought to
# write long ago when unix was young, eg, `sponge`.
#
# http://joeyh.name/code/moreutils/
brew install moreutils

# findutils
#
# GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
#
# http://www.gnu.org/software/findutils/
brew install findutils

# GNU sed
#
# sed (stream editor) isn't an interactive text editor.
#
# https://www.gnu.org/software/sed/
brew install gnu-sed

###############################################################################
# brew-formulae.d
#
# Install lists for homebrew forumlae.
###############################################################################

# Load all files in brew-formulae.d if it exists.
brewformulaed="$DOTFILES/script/install/brew-formulae.d"
if [[ -e "$brewformulaed" ]]
then
  for f in "$brewformulaed"/*
  do
    source "$f"
  done
fi

###############################################################################
# Homebrew - Linking
###############################################################################

# linkapps
#
# link apps installed with homebrew. Pass the `--local` flag in order to
# symlink apps to ~/Applications.
#
# NOTE: first unlinking apps to cleanup old links that apparently sometimes
# stick around.
brew unlinkapps --local
brew linkapps --local

###############################################################################
# Cleanup
###############################################################################

# Remove outdated versions.
brew cleanup

###############################################################################
# Application Aliasing
#
# Custom brew commands for creating spotlight-recognizable application aliases.
#
# Uses the alias-app command line tool: https://github.com/alphabetum/alias-app
###############################################################################

brew aliasapps
