#!/usr/bin/env bash
#
# brew-forumlae
#
# Install programs and applications using Homebrew.
#
# http://brew.sh/

###############################################################################
# Platform Check
###############################################################################

# Exit unless OS X
if [[ ! "$OSTYPE" =~ ^darwin ]]; then
  printf "brew-formulae is only supported on OS X\nSkipping...\n"
  exit 0
fi

###############################################################################
# Homebrew - Update
###############################################################################

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

###############################################################################
# Homebrew - Taps
#
# `brew tap` allows you to add more Github repos to the list of formulae that
# brew tracks, updates and installs from.
#
###############################################################################

# alphabetum-taps
#
# My custom taps.
#
# https://github.com/alphabetum/homebrew-taps
brew tap alphabetum/taps

# homebrew-completions
#
# Shell completion formulae for the Homebrew package manager
#
# https://github.com/Homebrew/homebrew-completions
brew tap homebrew/completions

# homebrew-dupes
#
# These formulae duplicate software provided by OS X, though may provide more
# recent or bugfix versions.
#
# https://github.com/Homebrew/homebrew-dupes
brew tap homebrew/dupes

# homebrew-games
#
# Game formulae for the Homebrew package manager
#
# https://github.com/Homebrew/homebrew-games
brew tap homebrew/games

# homebrew-head-only
#
# These formulae are unversioned (they have no stable release) so are only
# available as the latest version from e.g. a version control system.
#
# https://github.com/Homebrew/homebrew-head-only

brew tap homebrew/head-only

# homebrew-science
#
# These formulae provide software tailored to scientific endeavours. Need to
# store large amounts of data in a sparse matrix, solve a huge optimization
# problem or process the images from your space telescope? Maybe we can help!
#
# https://github.com/Homebrew/homebrew-science
brew tap homebrew/science

# brew-desc.rb
#
# Searchable descriptions for Homebrew formulas
#
# https://github.com/telemachus/homebrew-desc
brew tap telemachus/homebrew-desc

###############################################################################
# Homebrew - Formula
###############################################################################

# ----------------------------------------------------------------------------
# Utilities and Basic Programs
# ----------------------------------------------------------------------------

# GNU Core Utilities
#
# For using in place of outdated OS X versions.
#
# https://www.gnu.org/software/coreutils
#
# NOTE: To use, add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

# moreutils
#
# moreutils is a growing collection of the unix tools that nobody thought to
# write long ago when unix was young, eg, `sponge`.
#
# http://joeyh.name/code/moreutils/
brew install moreutils

# findutils
#
# GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
#
# http://www.gnu.org/software/findutils/
brew install findutils

# GNU sed
#
# sed (stream editor) isn't an interactive text editor.
#
# https://www.gnu.org/software/sed/
#
# NOTE: overwriting the built-in `sed`
brew install gnu-sed --default-names


# GNU Bash
#
# Bash 4. Newer than OS X default.
#
# http://www.gnu.org/software/bash/
#
# NOTE: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before
# running `chsh`.
brew install bash
brew install bash-completion

# GNU wget
#
# GNU Wget is a free software package for retrieving files using HTTP, HTTPS
# and FTP, the most widely-used Internet protocols.
#
# https://www.gnu.org/software/wget/
#
# NOTE: including support of IRIs, Internationalized Resource Identifiers,
# which are similar to URI, but allow unicode charaters to be used.
brew install wget --with-iri

# RingoJS and Narwhal.
#
# Ringo is a CommonJS-based JavaScript runtime written in Java and based on the
# Mozilla Rhino JavaScript engine.
#
# http://ringojs.org
#
# Narwhal is a cross-platform, multi-interpreter, general purpose JavaScript
# platform. It aims to provide a solid foundation for building JavaScript
# applications, primarily outside the web browser. Narwhal includes a package
# manager, module system, and standard library for multiple JavaScript
# interpreters.
#
# https://github.com/280north/narwhal
#
# NOTE: the order in which these are installed is important. See:
# http://git.io/brew-narwhal-ringo.
brew install ringojs
brew install narwhal

# ----------------------------------------------------------------------------
# More recent versions of some OS X tools.
# ----------------------------------------------------------------------------

brew install vim --override-system-vi
brew install homebrew/dupes/grep
brew install homebrew/dupes/screen
brew install homebrew/php/php55 --with-gmp

###############################################################################
# Docker
#
# https://www.docker.com/
###############################################################################

brew install boot2docker
# To have launchd start boot2docker at login:
#     ln -sfv /usr/local/opt/boot2docker/*.plist ~/Library/LaunchAgents
# Then to load boot2docker now:
#     launchctl load ~/Library/LaunchAgents/homebrew.mxcl.boot2docker.plist
ln -sfv /usr/local/opt/boot2docker/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.boot2docker.plist
brew install docker

###############################################################################
# brew-formulae.d
#
# Install lists for homebrew forumlae.
###############################################################################

# Load all files in brew-formulae.d if it exists.
brewformulaed="$DOTFILES/script/install/brew-formulae.d"
if [ -e "$brewformulaed" ]; then
  for f in "$brewformulaed"/*
    do
      source "$f"
  done
fi

###############################################################################
# Homebrew - Linking
###############################################################################

# linkapps
#
# link apps installed with homebrew. Pass the `--local` flag in order to
# symlink apps to ~/Applications.
#
# NOTE: first unlinking apps to cleanup old links that apparently sometimes
# stick around.
brew unlinkapps --local
brew linkapps --local

###############################################################################
# Cleanup
###############################################################################

# Remove outdated versions.
brew cleanup

###############################################################################
# Application Aliasing
#
# Custom brew commands for creating spotlight-recognizable application aliases.
#
# Uses the alias-app command line tool: https://github.com/alphabetum/alias-app
###############################################################################

brew aliasapps
