#!/usr/bin/env bash
################################################################################
# brew-linux
#
# Install programs into the home directory on linux using Linuxbrew / Homebrew.
#
# http://brew.sh/linuxbrew/
# https://github.com/Homebrew/linuxbrew
###############################################################################

###############################################################################
# Platform Check
###############################################################################

if [[ ! "$(uname -a)" =~ ^Linux ]]
then
  printf "brew-linux is only supported on Linux.\nSkipping...\n"
  exit 0
fi

###############################################################################
# Helpers
###############################################################################

# _homebrew_formula_is_installed()
#
# Test whether a given homebrew formula is installed on the system.
#
# Usage:
#   _homebrew_formula_is_installed "formula_name"
_homebrew_formula_is_installed() {
  local _formula_name="$1"
  [[ -n "$(brew list "$_formula_name" 2>/dev/null)" ]]
}

###############################################################################
# Homebrew - Update
###############################################################################

# Upgrade any already-installed formulae.
brew upgrade --all

###############################################################################
# Programs
###############################################################################

# Ack
#
# Ack is a tool like grep, optimized for programmers
#
# http://beyondgrep.com/
brew install ack

# Bats
#
# Bash Automated Testing System
#
# Bats is a TAP-compliant testing framework for Bash. It provides a simple way
# to verify that the UNIX programs you write behave as expected.
#
# https://github.com/sstephenson/bats
brew install bats

# fasd
#
# CLI tool for quick access to files and directories
#
# https://github.com/clvv/fasd
brew install fasd

# The Silver Searcher
#
# A code-searching tool similar to ack, but faster.
#
# https://github.com/ggreer/the_silver_searcher
# http://geoff.greer.fm/ag/
#
# NOTE: command name is `ag`
brew install the_silver_searcher

# Tig - text-mode interface for Git
#
# Tig is an ncurses-based text-mode interface for git. It functions mainly as a
# Git repository browser, but can also assist in staging changes for commit at
# chunk level and act as a pager for output from various Git commands.
#
# http://jonas.nitro.dk/tig/
brew install tig

# tree
#
# Tree is a recursive directory listing command that produces a depth indented
# listing of files.
#
# http://mama.indstate.edu/users/ice/tree/
brew install tree

# zsh
#
# UNIX shell (command interpreter)
#
# http://www.zsh.org/
brew install zsh

# htop (htop-osx)
#
# htop, an interactive process viewer.
#
# https://github.com/max-horvath/htop-osx
#
# NOTE: install htop last because otherwise it fails.
brew install htop

###############################################################################
# Cleanup
###############################################################################

# Remove outdated versions.
brew cleanup
