#!/usr/bin/env bash
###############################################################################
# brew-casks
#
# Install programs and applications using Homebrew and Homebrew Cask.
#
# http://brew.sh/
# http://caskroom.io/
###############################################################################

###############################################################################
# Platform Check
###############################################################################

if [[ ! "$OSTYPE" =~ ^darwin ]]; then
  printf "brew-casks is only supported on OS X\nSkipping...\n"
  exit 0
fi

###############################################################################
# Homebrew - Update
###############################################################################

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

###############################################################################
# Homebrew Cask
###############################################################################

# install brew cask
brew install caskroom/cask/brew-cask

###############################################################################
# Homebrew Cask - Taps
#
# `brew tap` allows you to add more Github repos to the list of formulae that
# brew tracks, updates and installs from.
###############################################################################

# homebrew-cask-versions
#
# Alternate versions of Casks for homebrew-cask
#
# https://github.com/caskroom/homebrew-versions
brew tap caskroom/versions

# Caskroom-fonts
#
# Caskroom-fonts is a Homebrew Tap which allows you to use the same friendly
# Homebrew-style CLI workflow for the administration of binary font files on
# your Mac.
#
# https://github.com/caskroom/homebrew-fonts
brew tap caskroom/fonts

###############################################################################
# Homebrew Cask - Fonts
###############################################################################

# Sauce Code Powerline
#
# Source Code Pro is a set of monospaced OpenType fonts that have been designed
# to work well in coding environments. This family of fonts is a complementary
# design to the Source Sans family. Sauce Code Powerline is derived from Source
# Code Pro for Powerline users.
#
# https://github.com/powerline/fonts/tree/master/SourceCodePro
brew cask install font-sauce-code-powerline

###############################################################################
# Homebrew Cask - Applications
###############################################################################

# VirtualBox
#
# VirtualBox is a powerful x86 and AMD64/Intel64 virtualization product.
#
# http://www.virtualbox.org
#
# NOTE: Installing first since it's important and other casks use it.
brew cask install virtualbox

# 1Password
#
# Password manager and secure wallet
#
# https://agilebits.com/onepassword
brew cask install 1password

# Adium
#
# Adium is a free instant messaging application for Mac OS X that can connect
# to AIM, MSN, XMPP (Jabber), Yahoo, and more.
#
# https://adium.im/
brew cask install adium

# Amethyst
#
# Tiling window manager for OS X similar to xmonad, written in pure
# Objective-C.
#
# http://ianyh.com/amethyst/
brew cask install amethyst

# Android Studio
#
# https://developer.android.com/sdk/index.html
brew cask install android-studio

# Atom
#
# A hackable text editor for the 21st Century.
#
# http://atom.io
brew cask install atom

# Audacity
#
# Audacity® is free, open source, cross-platform software for recording and
# editing sounds.
#
# http://audacity.sourceforge.net/
brew cask install audacity

# Blender
#
# Blender is a free and open source 3D animation suite.
#
# http://www.blender.org/
brew cask install blender

# Brackets
#
# Adobe's open source text editor built with and focused on web technologies.
#
# http://brackets.io
brew cask install brackets

# Breach
#
# A new modular browser. Entirely written in Javascript. Free. Hackable.
#
# http://breach.cc
brew cask install breach

# Cakebrew
#
# The Mac App for Homebrew.
#
# http://www.cakebrew.com
brew cask install cakebrew

# Cargo
#
# Cargo is a tool that allows Rust projects to declare their various
# dependencies, and ensure that you'll always get a repeatable build.
#
# https://crates.io/
brew cask install cargo

# Codebox
#
# Open source cloud & desktop IDE.
#
# https://www.codebox.io
brew cask install codebox

# Colors
#
# Colors is a color picker that takes Apple's basic color chooser (complete
# with "magnifying glass" to pull colors from other applications), and combines
# it with an easy way to copy common formats of color values (eg., #rrggbb,
# rgba(r, g, b, a), etc.) to the clipboard.
#
# http://mattpatenaude.com/
brew cask install colors

# Consul
#
# Consul is a tool for service discovery, monitoring and configuration.
#
# http://www.consul.io/
brew cask install consul

# Disk Inventory X
#
# Disk Inventory X is a disk usage utility for Mac OS X 10.3 (and later). It
# shows the sizes of files and folders in a special graphical way called
# "treemaps".
#
# http://www.derlien.com/
brew cask install disk-inventory-x

# Elm
#
# A functional reactive language for interactive applications
#
# http://www.elm-lang.org
brew cask install elm-platform

# Factor
#
# The Factor programming language combines powerful language features with a
# full-featured library. Factor belongs to the family of concatenative
# languages: this means that, at the lowest level, a Factor program is a
# series of words (functions) that manipulate a stack of references to
# dynamically-typed values. This gives the language a powerful foundation
# which allows many abstractions and paradigms to be built on top.
#
# http://factorcode.org/
brew cask install factor

# Firefox
#
# A free and open-source web browser.
#
# https://www.mozilla.org/en-US/firefox/
brew cask install firefox

# Firefox Developer Edition
#
# A distribution of the Firefox web browser designed for developers.
#
# https://www.mozilla.org/en-US/firefox/developer/
brew cask install firefoxdeveloperedition

# Gimp
#
# GIMP is the GNU Image Manipulation Program. It is a freely distributed piece
# of software for such tasks as photo retouching, image composition and image
# authoring.
#
# http://www.gimp.org
brew cask install gimp

# GnuCash
#
# GnuCash is open source personal and small-business financial-accounting
# software.
#
# http://www.gnucash.org
brew cask install gnucash

# gridwars
#
# GridWars or GridWars 2 is a computer game inspired by Bizarre Creations'
# Geometry Wars developed by Marco Incitti.
#
# http://gridwars.marune.de/
brew cask install gridwars

# Google Chrome
#
# A freeware web browser developed by Google.
#
# https://www.google.com/chrome/
brew cask install google-chrome

# The Haskell Platform
#
# http://www.haskell.org/platform/
brew cask install haskell-platform

# Inkscape
#
# Inkscape is an open-source vector graphics editor similar to Adobe
# Illustrator, Corel Draw, Freehand, or Xara X that used Scalable Vector
# Graphics (SVG), an open XML-based W3C standard, as the native format.
#
# https://inkscape.org/en/
brew cask install inkscape

# iTerm2
#
# iTerm2 is a replacement for Terminal and the successor to iTerm.
#
# http://www.iterm2.com/
brew cask install iterm2-nightly

# KindleGen
#
# KindleGen is a command line tool which enables publishers to work in an
# automated environment with a variety of source content including HTML, XHTML
# or EPUB. KindleGen converts this source content to a single file which
# supports both KF8 and Mobi formats enabling publishers to create
# great-looking books that work on all Kindle devices and apps.
#
# http://www.amazon.com/gp/feature.html?docId=1000765211
brew cask install kindlegen

# Krita
#
# Krita is a digital painting and illustration application.
#
# https://krita.org/
brew cask install krita

# LibreOffice
#
# LibreOffice is a free and open source office suite, developed by The Document
# Foundation. It was forked from OpenOffice.org in 2010, which was an
# open-sourced version of the earlier StarOffice. The LibreOffice suite
# comprises programs to do word processing, spreadsheets, slideshows, diagrams
# and drawings, maintain databases, and compose mathematical formulae.
#
# http://www.libreoffice.org/
brew cask install libreoffice

# Light Table
#
# A text editor and IDE build with JavaScript.
#
# http://www.lighttable.com/
# https://github.com/LightTable/LightTable
brew cask install lighttable

# MacTex
#
# MacTeX is an OS X-specific redistribution of TeX Live, a typesetting
# environment.
#
# http://www.tug.org/mactex/
brew cask install mactex

# Natron
#
# Natron is an open-source • crossplatform nodal • compositing software
#
# https://natron.inria.fr/
brew cask install natron

# osxfuse - FUSE for OS X
#
# The easiest and fastest way to create filesystems for OS X. FUSE for OS X
# allows you to extend OS X's native file handling capabilities via third-party
# file systems. OSXFUSE is a successor to MacFUSE.
#
# https://osxfuse.github.io/
brew cask install osxfuse

# Packer
#
# Packer is a tool for creating identical machine images for multiple platforms
# from a single source configuration.
#
# http://www.packer.io/
brew cask install packer

# pd-extended - PureData
#
# Pure Data (aka Pd) is an open source visual programming language. Pd enables
# musicians, visual artists, performers, researchers, and developers to create
# software graphically, without writing lines of code.
#
# http://puredata.info/
# http://puredata.info/downloads/pd-extended
brew cask install pd-extended

# pgAdmin
#
# pgAdmin is the most popular and feature rich Open Source administration and
# development platform for PostgreSQL
#
# http://pgadmin.org
brew cask install pgadmin3

# rowanj-gitx
#
# GitX-dev is a fork (variant) of GitX, a long-defunct GUI for the git
# version-control system. It has been maintained and enhanced with productivity
# and friendliness oriented changes, with effort focused on making a
# first-class, maintainable tool for today's active developers.
#
# http://rowanj.github.io/gitx/
# https://github.com/rowanj/gitx
brew cask install rowanj-gitx

# Scribus
#
# Scribus is an Open Source program that brings professional page layout to
# Linux, BSD UNIX, Solaris, OpenIndiana, GNU/Hurd, Mac OS X, OS/2 Warp 4,
# eComStation, Windows and Haiku desktops with a combination of press-ready
# output and new approaches to page design.
#
# Underneath a modern and user-friendly interface, Scribus supports
# professional publishing features, such as color separations, CMYK and spot
# colors, ICC color management, and versatile PDF creation.
#
# http://www.scribus.net/canvas/Scribus
brew cask install scribus

# Secrets
#
# A database of hidden settings for Mac OS X
#
# http://secrets.blacktree.com
brew cask install secrets

# Sonic Pi
#
# Audible Computing. A free sound synthesiser for live coding designed to
# support computing and music lessons within schools. Make Music Using Ruby.
#
# http://sonic-pi.net/
brew cask install sonic-pi

# Sonic Visualiser
#
# Sonic Visualiser is an application for viewing and analysing the contents of
# music audio files.
#
# http://www.sonicvisualiser.org/
brew cask install sonic-visualiser

# Spectacle
#
# Move and resize windows with ease. Window control with simple, customizable
# keyboard shortcuts.
#
# http://spectacleapp.com
brew cask install spectacle

# sublime-text3
#
# Sublime Text is a text editor for code, markup and prose.
#
# http://www.sublimetext.com/
# http://www.sublimetext.com/3
brew cask install sublime-text3

# Vagrant
#
# Create and configure lightweight, reproducible, and portable development
# environments.
#
# http://www.vagrantup.com
brew cask install vagrant

# Vico
#
# Vico is a programmers text editor with a strong focus on keyboard control and
# uses vi key bindings.
#
# http://www.vicoapp.com
brew cask install vico

# VimR
#
# A Vim GUI for OS X
#
# http://vimr.org/
brew cask install vimr

# Vivaldi
#
# A web browser.
#
# https://vivaldi.com
brew cask install vivaldi

# VLC - vlc-nightly
#
# VLC is a free and open source cross-platform multimedia player and framework
# that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and
# various streaming protocols.
#
# http://www.videolan.org/vlc/
brew cask install vlc-nightly

# XQuartz
#
# The XQuartz project is an open-source effort to develop a version of the
# X.Org X Window System that runs on OS X. Together with supporting libraries
# and applications, it forms the X11.app that Apple has shipped with OS X since
# version 10.5.
#
# http://xquartz.macosforge.org/landing/
brew cask install xquartz

# Zed
#
# Zed is a fully offline-capable, open source, keyboard-focused, text and code
# editor for power users.
#
# http://zedapp.org
brew cask install zed

###############################################################################
# Cleanup
###############################################################################

# Remove outdated versions.
brew cask cleanup

###############################################################################
# Application Aliasing
#
# Custom brew commands for creating spotlight-recognizable application aliases.
#
# Uses the alias-app command line tool: https://github.com/alphabetum/alias-app
###############################################################################

brew cask aliasapps

