#!/usr/bin/env bash
###############################################################################
# cabal-packages
#
# Download and install cabal / haskell packages.
###############################################################################

###############################################################################
# Update
###############################################################################

# Download the latest package list from hackage.haskell.org
cabal update

###############################################################################
# Packages
###############################################################################

# HLint
#
# HLint is a tool for suggesting possible improvements to Haskell code. These
# suggestions include ideas such as using alternative functions, simplifying
# code and spotting redundancies. You can try HLint online at lpaste.net
#
# https://github.com/ndmitchell/hlint
cabal install hlint

# record
#
# An API of just two quasi-quoters, providing a full-scale solution to the
# notorious records problem of Haskell.
#
# http://hackage.haskell.org/package/record
# https://github.com/nikita-volkov/record
# http://nikita-volkov.github.io/record/
cabal install record
