#!/usr/bin/env bash
###############################################################################
# cabal-packages
#
# Download and install cabal / haskell packages.
###############################################################################

###############################################################################
# Update
###############################################################################

# Download the latest package list from hackage.haskell.org
cabal update

###############################################################################
# Packages
###############################################################################

# cabalg
#
# cabalg is an alias for installing cabal package from a git source repository.
#
# https://hackage.haskell.org/package/cabalg
# https://github.com/dmalikov/cabalg
cabal install cabalg

# HLint
#
# HLint is a tool for suggesting possible improvements to Haskell code. These
# suggestions include ideas such as using alternative functions, simplifying
# code and spotting redundancies. You can try HLint online at lpaste.net
#
# https://github.com/ndmitchell/hlint
cabal install hlint

# lushtags
#
# Create ctags compatible tags files for Haskell programs. Similar programs
# are hasktags, gasbag, hothasktags, and GHC's builtin ctags generation.
# lushtags differs from these by being designed to have smooth integration
# with the Vim Tagbar plugin.
#
# https://github.com/bitc/lushtags
cabalg https://github.com/bitc/lushtags.git@429fab3

# record
#
# An API of just two quasi-quoters, providing a full-scale solution to the
# notorious records problem of Haskell.
#
# http://hackage.haskell.org/package/record
# https://github.com/nikita-volkov/record
# http://nikita-volkov.github.io/record/
cabal install record
