#!/usr/bin/env bash
###############################################################################
# rubygems
#
# Install various global ruby gems modules
###############################################################################

# faker
#
# A library for generating fake data such as names, addresses, and phone
# numbers.
#
# https://github.com/stympy/faker
gem install faker

# foreman - manage Procfile-based applications
#
# Foreman is a manager for Procfile-based applications. Its aim is to abstract
# away the details of the Procfile format, and allow you to either run your
# application directly or export it to some other process management format.
#
# https://github.com/ddollar/foreman
gem install foreman

# git-up
#
# fetch and rebase all locally-tracked remote branches
#
# https://github.com/aanand/git-up
gem install git-up

# hijack
#
# Provides an irb session to a running ruby process.
#
# https://github.com/ileitch/hijack
gem install hijack

# jekyll
#
# Jekyll is a simple, blog-aware, static site generator perfect for personal,
# project, or organization sites.
#
# http://jekyllrb.com/
# https://github.com/jekyll/jekyll
gem install jekyll

# lunchy
#
# A friendly wrapper for launchctl. Start your agents and go to lunch!
#
# https://github.com/eddiezane/lunchy
gem install lunchy

# Powify
#
# Powify is a management tool for Pow by 37 signals. It allows you to easily
# install, update, and manage pow and pow applications seamlessly.
#
# https://github.com/sethvargo/powify
gem install powify

# Puppet-lint
#
# Check that your Puppet manifests conform to the style guide
#
# https://github.com/rodjek/puppet-lint
gem install puppet-lint

# ruby-lint
#
# Static code analysis for Ruby.
#
# https://github.com/YorickPeterse/ruby-lint
gem install ruby-lint

# scss-lint
#
# scss-lint is a tool to help keep your SCSS files clean and readable. You can
# run it manually from the command-line, or integrate it into your SCM hooks.
#
# https://github.com/causes/scss-lint
gem install scss-lint

# Tmuxinator
#
# Create and manage tmux sessions easily.
#
# https://github.com/tmuxinator/tmuxinator
gem install tmuxinator
