#!/usr/bin/env bash
#
# rubygems
#
# Install various global ruby gems modules

# faker
#
# A library for generating fake data such as names, addresses, and phone
# numbers.
#
# https://github.com/stympy/faker
gem install faker

# foreman - manage Procfile-based applications
#
# Foreman is a manager for Procfile-based applications. Its aim is to abstract
# away the details of the Procfile format, and allow you to either run your
# application directly or export it to some other process management format.
#
# https://github.com/ddollar/foreman
gem install foreman

# hijack
#
# Provides an irb session to a running ruby process.
#
# https://github.com/ileitch/hijack
gem install hijack

# Powify
#
# Powify is a management tool for Pow by 37 signals. It allows you to easily
# install, update, and manage pow and pow applications seamlessly.
#
# https://github.com/sethvargo/powify
gem install powify

# ruby-lint
#
# Static code analysis for Ruby.
#
# https://github.com/YorickPeterse/ruby-lint
gem install ruby-lint
