#!/usr/bin/env bash
###############################################################################
# rubygems
#
# Install various global ruby gems modules
###############################################################################

###############################################################################
# Utility Functions
###############################################################################

# _gem_is_installed
#
# Usage:
#   _gem_is_installed <gem-name>
#
# Description:
#   Test whether a gem with the specified name is currently installed
#   globally. More information: http://serverfault.com/q/391621
_gem_is_installed() {
  if [[ -z "${1:-}" ]]
  then
    printf "No gem name specified.\n" && exit 1
  fi
  [[ "$(gem query -i -n "^t$")" == "true" ]]
}

###############################################################################
# Global Gems
###############################################################################

# artoo
#
# Ruby robotics framework using Celluloid with support for 15 different
# platforms.
#
# http://artoo.io/
# https://github.com/hybridgroup/artoo
gem install artoo

# CocoaPods
#
# CocoaPods is the dependency manager for Swift and Objective-C Cocoa projects.
# It has almost ten thousand libraries and can help you scale your projects
# elegantly.
#
# https://cocoapods.org/
gem install cocoapods

# contracts.ruby
#
# contracts.ruby brings code contracts to the Ruby language. Code contracts
# allow you make some assertions about your code, and then checks them to make
# sure they hold.

# https://github.com/egonSchiele/contracts.ruby
# http://egonschiele.github.io/contracts.ruby/
gem install contracts

# faker
#
# A library for generating fake data such as names, addresses, and phone
# numbers.
#
# https://github.com/stympy/faker
gem install faker

# foreman - manage Procfile-based applications
#
# Foreman is a manager for Procfile-based applications. Its aim is to abstract
# away the details of the Procfile format, and allow you to either run your
# application directly or export it to some other process management format.
#
# https://github.com/ddollar/foreman
gem install foreman

# fpm
#
# Effing package management. Build packages for multiple platforms (deb,
# rpm, etc) with great ease and sanity.
#
# https://github.com/jordansissel/fpm
gem install fpm

# gem_updater
#
# Update gems in your Gemfile and fetch their changelogs
#
# https://github.com/MaximeD/gem_updater
gem install gem_updater

# git-up
#
# fetch and rebase all locally-tracked remote branches
#
# https://github.com/aanand/git-up
gem install git-up

# hijack
#
# Provides an irb session to a running ruby process.
#
# https://github.com/ileitch/hijack
gem install hijack

# iStats
#
# iStats is a command-line tool that allows you to easily grab the CPU
# temperature, fan speeds and battery information on OS X.
#
# https://github.com/Chris911/iStats
gem install iStats

# jekyll
#
# Jekyll is a simple, blog-aware, static site generator perfect for personal,
# project, or organization sites.
#
# http://jekyllrb.com/
# https://github.com/jekyll/jekyll
gem install jekyll

# lolcat
#
# Rainbows and unicorns!
#
# https://github.com/busyloop/lolcat
# https://rubygems.org/gems/lolcat
gem install lolcat

# lunchy
#
# A friendly wrapper for launchctl. Start your agents and go to lunch!
#
# https://github.com/eddiezane/lunchy
gem install lunchy

# Middleman
#
# Middleman is a static site generator using all the shortcuts and tools in
# modern web development.
#
# https://middlemanapp.com
# https://github.com/middleman/middleman
gem install middleman

# mina
#
# Really fast deployer and server automation tool.
#
# Mina works really fast because it's a deploy Bash script generator. It
# generates an entire procedure as a Bash script and runs it remotely in the
# server.
#
# http://nadarei.co/mina/
# https://github.com/mina-deploy/mina
gem install mina

# Powify
#
# Powify is a management tool for Pow by 37 signals. It allows you to easily
# install, update, and manage pow and pow applications seamlessly.
#
# https://github.com/sethvargo/powify
gem install powify

# Puppet-lint
#
# Check that your Puppet manifests conform to the style guide
#
# https://github.com/rodjek/puppet-lint
gem install puppet-lint

# rubocop
#
# A Ruby static code analyzer, based on the community Ruby style guide.
#
# http://batsov.com/rubocop/
# https://github.com/bbatsov/rubocop
gem install rubocop

# ruby-lint
#
# Static code analysis for Ruby.
#
# https://github.com/YorickPeterse/ruby-lint
gem install ruby-lint

# Rush
#
# manage your unix systems with pure Ruby
#
# rush is a unix integration library and an interactive shell which uses pure
# Ruby syntax. Walk directory trees; create, copy, search, and destroy files;
# find and kill processes - everything you'd normally do with shell commands,
# now in the strict and elegant world of Ruby.
#
# https://github.com/s-mage/rush
#
# rush2 is a fork of the original that's currently being developed. The
# original version of Rush:
# https://github.com/adamwiggins/rush
gem install rush2

# scss-lint
#
# scss-lint is a tool to help keep your SCSS files clean and readable. You can
# run it manually from the command-line, or integrate it into your SCM hooks.
#
# https://github.com/causes/scss-lint
gem install scss-lint

# Timetrap
#
# Timetrap is a simple command line time tracker written in ruby. It provides
# an easy to use command line interface for tracking what you spend your time
# on.
#
# https://github.com/samg/timetrap
#
# NOTE: This conflicts with the previously installed t twitter client, so that
# gem needs to be uninstalled first.
# TODO: remove this uninstall section.
if _gem_is_installed "t"
then
  gem uninstall t
fi
gem install timetrap

# Tmuxinator
#
# Create and manage tmux sessions easily.
#
# https://github.com/tmuxinator/tmuxinator
gem install tmuxinator

# Tugboat
#
# A command line tool for interacting with your DigitalOcean droplets.
#
# https://github.com/pearkes/tugboat
gem install tugboat
