#!/usr/bin/env bash
###############################################################################
# go-packages
#
# Download and install go / golang packages
###############################################################################

# bolt
#
# Bolt is a pure Go key/value store inspired by Howard Chu's and the LMDB
# project. The goal of the project is to provide a simple, fast, and reliable
# database for projects that don't require a full database server such as
# Postgres or MySQL.
#
# https://github.com/boltdb/bolt
# https://news.ycombinator.com/item?id=8735684
go get -u -v github.com/boltdb/bolt/...

# elvish
#
# An experimental Unix shell
#
# https://github.com/elves/elvish
go get -u -v github.com/elves/elvish

# errcheck
#
# errcheck is a program for checking for unchecked errors in go programs.
#
# https://github.com/kisielk/errcheck
go get -u -v github.com/kisielk/errcheck

# gocode
#
# An autocompletion daemon for the Go programming language.
#
# https://github.com/nsf/gocode
go get -u -v github.com/nsf/gocode

# godef
#
# Godef prints the source location of definitions in Go programs.
#
# http://godoc.org/code.google.com/p/rog-go/exp/cmd/godef
# https://code.google.com/p/rog-go/source/browse/exp/cmd/godef/
go get -u -v code.google.com/p/rog-go/exp/cmd/godef

# godep
#
# Command godep helps build packages reproducibly by fixing their dependencies.
#
# https://github.com/tools/godep
go get -u -v github.com/tools/godep

# godoc
#
# Godoc extracts and generates documentation for Go programs.
#
# https://godoc.org/golang.org/x/tools/cmd/godoc
go get -u -v golang.org/x/tools/cmd/godoc

# gore
#
# Yet another Go REPL that works nicely. Featured with line editing, code
# completion, and more
#
# https://github.com/motemen/gore
go get -u -v github.com/motemen/gore

# go-ipfs / ipfs
#
# ipfs implementation in go
#
# IPFS - The Permanent Web
#
# IPFS is a distributed file system that seeks to connect all computing devices
# with the same system of files. In some ways, this is similar to the original
# aims of the Web, but IPFS is actually more similar to a single bittorrent
# swarm exchanging git objects.
#
# https://github.com/jbenet/ipfs
# https://github.com/jbenet/go-ipfs
go get -u -v github.com/jbenet/go-ipfs/cmd/ipfs

# goimports
#
# Command goimports updates your Go import lines, adding missing ones and
# removing unreferenced ones.
#
# https://godoc.org/golang.org/x/tools/cmd/goimports
go get -u -v golang.org/x/tools/cmd/goimports

# golint
#
# Golint is a linter for Go source code.
#
# https://github.com/golang/lint/
go get -u -v github.com/golang/lint/golint

# gorename
#
# The gorename command performs precise type-safe renaming of identifiers in
# Go source code.
#
# https://godoc.org/golang.org/x/tools/cmd/gorename
go get -u -v golang.org/x/tools/cmd/gorename

# gotags
#
# ctags-compatible tag generator for Go.
#
# https://github.com/jstemmer/gotags
go get -u -v github.com/jstemmer/gotags

# oracle
#
# a tool for answering questions about Go source code.
#
# https://godoc.org/golang.org/x/tools/cmd/oracle
go get -u -v golang.org/x/tools/cmd/oracle

# pt
#
# A path tracer written in Go.
#
# https://github.com/fogleman/pt
go get -u -v github.com/fogleman/pt/pt

# stack
#
# Minimalist provisioning tool written in Go.
#
# https://github.com/tj/stack
go get -u -v github.com/visionmedia/stack/cmd/stack

# termui
#
# Go terminal dashboard. Inspired by blessed-contrib, but purely in Go.
#
# https://github.com/gizak/termui
go get -u -v github.com/gizak/termui

# vet
#
# Vet examines Go source code and reports suspicious constructs, such as Printf
# calls whose arguments do not align with the format string. Vet uses
# heuristics that do not guarantee all reports are genuine problems, but it can
# find errors not caught by the compilers.
#
# https://godoc.org/golang.org/x/tools/cmd/vet
go get -u -v golang.org/x/tools/cmd/vet

