#!/usr/bin/env bash
###############################################################################
# go-packages
#
# Download and install go / golang packages
###############################################################################

# bolt
#
# Bolt is a pure Go key/value store inspired by Howard Chu's and the LMDB
# project. The goal of the project is to provide a simple, fast, and reliable
# database for projects that don't require a full database server such as
# Postgres or MySQL.
#
# https://github.com/boltdb/bolt
# https://news.ycombinator.com/item?id=8735684
go get -u -v github.com/boltdb/bolt/...

# ccat
#
# ccat is the colorizing cat. It works similar to cat but displays content with
# syntax highlighting.
#
# https://github.com/jingweno/ccat
go get -u -v github.com/jingweno/ccat

# Delve
#
# Delve is a debugger for the Go programming language.
#
# https://github.com/derekparker/delve
go get github.com/derekparker/delve/cmd/dlv

# elvish
#
# An experimental Unix shell
#
# https://github.com/elves/elvish
go get -u -v github.com/elves/elvish

# errcheck
#
# errcheck is a program for checking for unchecked errors in go programs.
#
# https://github.com/kisielk/errcheck
go get -u -v github.com/kisielk/errcheck

# Escher: A language for programming in metaphors
#
# Escher is a simple syntax for representing generic labeled graphs called
# circuits, much like XML is a (not-so-simple) syntax for representing generic
# labeled trees.
#
# http://gocircuit.github.io/escher/
# https://github.com/gocircuit/escher
go get -u -v github.com/gocircuit/escher/escher

# go-bootstrap
#
# Generates a lean and mean Go web project.
#
# http://go-bootstrap.io/
# https://github.com/go-bootstrap/go-bootstrap
go get -u -v github.com/go-bootstrap/go-bootstrap

# gb
#
# gb, the project based build tool for Go
#
# https://github.com/constabulary/gb
# https://walledcity.com/supermighty/building-go-projects-with-gb
go get -u -v github.com/constabulary/gb/...

# gocode
#
# An autocompletion daemon for the Go programming language.
#
# https://github.com/nsf/gocode
go get -u -v github.com/nsf/gocode

# godef
#
# Godef prints the source location of definitions in Go programs.
#
# http://godoc.org/code.google.com/p/rog-go/exp/cmd/godef
# https://code.google.com/p/rog-go/source/browse/exp/cmd/godef/
go get -u -v code.google.com/p/rog-go/exp/cmd/godef

# godep
#
# Command godep helps build packages reproducibly by fixing their dependencies.
#
# https://github.com/tools/godep
go get -u -v github.com/tools/godep

# godoc
#
# Godoc extracts and generates documentation for Go programs.
#
# https://godoc.org/golang.org/x/tools/cmd/godoc
go get -u -v golang.org/x/tools/cmd/godoc

# gotermimg
#
# Display images and play gifs in your 256 color terminal!
#
# https://github.com/moshen/gotermimg
go get github.com/moshen/gotermimg/...

# go-ipfs / ipfs
#
# ipfs implementation in go
#
# IPFS - The Permanent Web
#
# IPFS is a distributed file system that seeks to connect all computing devices
# with the same system of files. In some ways, this is similar to the original
# aims of the Web, but IPFS is actually more similar to a single bittorrent
# swarm exchanging git objects.
#
# https://github.com/jbenet/ipfs
# https://github.com/jbenet/go-ipfs
go get -u -v github.com/jbenet/go-ipfs/cmd/ipfs

# goimports
#
# Command goimports updates your Go import lines, adding missing ones and
# removing unreferenced ones.
#
# https://godoc.org/golang.org/x/tools/cmd/goimports
go get -u -v golang.org/x/tools/cmd/goimports

# golint
#
# Golint is a linter for Go source code.
#
# https://github.com/golang/lint/
go get -u -v github.com/golang/lint/golint

# gore
#
# Yet another Go REPL that works nicely. Featured with line editing, code
# completion, and more
#
# https://github.com/motemen/gore
go get -u -v github.com/motemen/gore

# gorename
#
# The gorename command performs precise type-safe renaming of identifiers in
# Go source code.
#
# https://godoc.org/golang.org/x/tools/cmd/gorename
go get -u -v golang.org/x/tools/cmd/gorename

# gotags
#
# ctags-compatible tag generator for Go.
#
# https://github.com/jstemmer/gotags
go get -u -v github.com/jstemmer/gotags

# hashpipe
#
# hashpipe helps you venture into the unknown. It reads from stdin, checks the
# hash of the content, and outputs it IF AND ONLY IF it matches the provided
# hash checksum. This makes executing things a teensy bit safer, as it
# requires compromising more communication channels.
#
# https://github.com/jbenet/hashpipe
# http://jbenet.github.io/hashpipe/
go get -u -v github.com/jbenet/hashpipe

# happyfinder / hf
#
# Fuzzy file finder for the command line
#
# hf is a command line utility to quickly find files and execute a command -
# something like Helm/Anything/CtrlP for the terminal. It tries to find the
# best match, like other fuzzy finders (Sublime, ido, Helm).
#
# https://github.com/hugows/hf
go get -u -v github.com/hugows/hf

# oracle
#
# a tool for answering questions about Go source code.
#
# https://godoc.org/golang.org/x/tools/cmd/oracle
go get -u -v golang.org/x/tools/cmd/oracle

# pt
#
# A path tracer written in Go.
#
# https://github.com/fogleman/pt
go get -u -v github.com/fogleman/pt/pt

# rtop
#
# rtop is an interactive, remote system monitoring tool based on SSH
#
# rtop is a remote system monitor. It connects over SSH to a remote system and
# displays vital system metrics (CPU, disk, memory, network). No special
# software is needed on the remote system, other than an SSH server and
# working credentials.
#
# https://github.com/rapidloop/rtop
go get -u -v github.com/rapidloop/rtop

# stack
#
# Minimalist provisioning tool written in Go.
#
# https://github.com/tj/stack
go get -u -v github.com/visionmedia/stack/cmd/stack

# termui
#
# Go terminal dashboard. Inspired by blessed-contrib, but purely in Go.
#
# https://github.com/gizak/termui
go get -u -v github.com/gizak/termui

# Thyme
#
# Automatically track which applications you use and for how long.
#
# - Simple CLI to track and analyze your application usage
# - Detailed charts that let you profile how you spend your time
# - Stores data locally, giving you full control and privacy
# - Open-source, well-documented, and easily extensible
#
# https://github.com/sourcegraph/thyme
# https://text.sourcegraph.com/thyme-a-simple-cli-to-measure-human-time-and-focus-577b87337b9c
# https://news.ycombinator.com/item?id=12298747
go get -u github.com/sourcegraph/thyme/cmd/thyme

# vet
#
# Vet examines Go source code and reports suspicious constructs, such as Printf
# calls whose arguments do not align with the format string. Vet uses
# heuristics that do not guarantee all reports are genuine problems, but it can
# find errors not caught by the compilers.
#
# https://godoc.org/golang.org/x/tools/cmd/vet
go get -u -v golang.org/x/tools/cmd/vet

# wego
#
# wego is a weather client for the terminal.
#
# https://github.com/schachmat/wego
#
# NOTE: this requires additional setup, including getting an API key from
# worldweatheronline.com See the Readme for additional information.
go get -u -v github.com/schachmat/wego
