#!/usr/bin/env bash
#
# go-packages
#
# Download and install go / golang packages

# godoc
#
# Godoc extracts and generates documentation for Go programs.
#
# https://godoc.org/golang.org/x/tools/cmd/godoc
go get -u golang.org/x/tools/cmd/godoc

# vet
#
# Vet examines Go source code and reports suspicious constructs, such as Printf
# calls whose arguments do not align with the format string. Vet uses
# heuristics that do not guarantee all reports are genuine problems, but it can
# find errors not caught by the compilers.
#
# https://godoc.org/golang.org/x/tools/cmd/vet
go get -u golang.org/x/tools/cmd/vet

