#!/usr/bin/env bash
###############################################################################
# luarocks
#
# Install various global lua rocks.
###############################################################################

###############################################################################
# Setup
###############################################################################

# Alias the luarocks command to the luarocks-5.2 executable.
#
# Homebrew-installed lua includes luarocks with an executable name that
# includes the version. In order to make a simpler `luarocks` command
# available, alias luarocks to the current executable.
#
# More background information here:
# https://github.com/Homebrew/homebrew/pull/37842
alias luarocks="luarocks-5.2"

###############################################################################
# Install
###############################################################################

# Mjolnir
#
# Lightweight automation and productivity app for OS X. Mjolnir is an OS X app
# that lets you automate common tasks using the language Lua. At its core, it
# doesn't actually do anything besides load up a Lua environment; the real
# power lies in all the useful modules that you can install.
#
# https://github.com/sdegutis/mjolnir
luarocks install mjolnir.hotkey
luarocks install mjolnir.application
