#!/usr/bin/env bash

# npm
#
# Install various global node modules

# https://github.com/broccolijs/broccoli
npm install -g broccoli-cli

# http://bower.io/
npm install -g bower

# http://coffeescript.org/
npm install -g coffee-script

# http://jashkenas.github.io/docco/
npm install -g docco

# http://www.ember-cli.com/
npm install -g ember-cli

# http://gruntjs.com/
npm install -g grunt-cli

# http://gulpjs.com/
npm install --g gulp

# https://github.com/rvagg/learnyounode
npm install -g learnyounode

# https://github.com/slap-editor/slap
# slap is a Sublime-like terminal-based text editor that strives to make editing from the terminal easier
npm install -g slap

# http://yeoman.io/
npm install -g yo
