#!/usr/bin/env bash
###############################################################################
# npm-packages
#
# Install various global npm packages.
###############################################################################

# ava
#
# Futuristic test runner.
#
# Even though JavaScript is single-threaded, IO in Node.js can happen in
# parallel due to its async nature. AVA takes advantage of this and runs your
# tests concurrently, which is especially beneficial for IO heavy tests. In
# addition, test files are run in parallel as separate processes, giving you
# even better performance and an isolated environment for each test file.
# Switching from Mocha to AVA in Pageres brought the test time down from 31
# sec to 11 sec. Having tests run concurrently forces you to write atomic
# tests, meaning tests don't depend on global state or the state of other
# tests, which is a great thing!
#
# https://github.com/sindresorhus/ava/
# https://news.ycombinator.com/item?id=11177690
# https://news.ycombinator.com/item?id=10135078
# https://news.ycombinator.com/item?id=10626291
npm install --global ava

# Babel
#
# Babel is a JavaScript transpiler. Use next generation JavaScript, today.
# Babel is a transpiler for writing next generation JavaScript. (Previously
# 6to5). ES6 and beyond. Babel will turn your ES6+ code into ES5 friendly code,
# so you can start using it right now without waiting for browser support
#
# https://babeljs.io/
# https://github.com/babel/babel
npm install --global babel

# Broccoli
#
# Browser compilation library – a build tool for applications that run in the
# browser.
#
# https://github.com/broccolijs/broccoli
npm install --global broccoli-cli

# Brunch
#
# A lightweight approach to building HTML5 applications with emphasis on
# elegance and simplicity. Brunch is a build tool for front-end web
# applications. It's agnostic to frameworks, libraries, programming,
# stylesheet & templating languages and backend technology.
#
# http://brunch.io/
# https://github.com/brunch/brunch
# https://www.npmjs.com/package/brunch
npm install --global brunch

# Bower
#
# A package manager for the web.
#
# http://bower.io/
npm install --global bower

# CoffeeLint
#
# CoffeeLint is a style checker that helps keep CoffeeScript code clean and
# consistent.
#
# http://www.coffeelint.org/
# https://github.com/clutchski/coffeelint
npm install --global coffeelint

# CoffeeScript
#
# A little language that compiles into JavaScript.
#
# http://coffeescript.org/
npm install --global coffee-script

# Component
#
# Component is a vertically integrated frontend solution, handling everything
# from package management to the build process, handling everything including
# HTML, JS, CSS, images, and fonts. Think of it as an opinionated npm +
# browserify + rework-npm + grunt/gulp/broccoli all wrapped into component
# build.
#
# http://component.github.io/
# https://github.com/componentjs/component
npm install --global component

# CSSLint
#
# Automated linting of Cascading Stylesheets.
#
# http://csslint.net
# https://github.com/CSSLint/csslint
# https://github.com/CSSLint/csslint/wiki/Command-line-interface
npm install --global csslint

# Cylon
#
# JavaScript framework for robotics, physical computing, and the Internet of
# Things.
#
# https://github.com/hybridgroup/cylon/
# http://cylonjs.com/
npm install --global cylon

# dat
#
# Dat is an open source project that provides a streaming interface between
# every file format and data storage backend.
#
# Real-time replication and versioning for data sets.
#
# http://dat-data.com/
# https://github.com/maxogden/dat
npm install --global dat

# datop
#
# top for dat
#
# https://github.com/maxogden/datop
npm install --global datop

# Docco
#
# A quick-and-dirty documentation generator, written in Literate
# CoffeeScript.
#
# http://jashkenas.github.io/docco/
npm install --global docco

# Electron (formerly Atom Shell)
#
# The Electron framework lets you write cross-platform desktop applications
# using JavaScript, HTML and CSS. It is based on io.js and Chromium and is
# used in the Atom editor.
#
# https://github.com/atom/electron
# https://github.com/atom/electron/tree/master/docs
npm install --global electron-prebuilt

# Ember CLI
#
# The command line interface for ambitious web applications.
#
# http://www.ember-cli.com/
npm install --global ember-cli

# ESLint
#
# A fully pluggable tool for identifying and reporting on patterns in
# JavaScript.
#
# http://eslint.org/
# https://github.com/eslint/eslint
npm install --global eslint

# Fly
#
# Fly is a build system for Node based in ES6 generators and promises that
# aims to be simple and elegant to write and extend.
#
# https://github.com/flyjs/fly
npm install --global fly

# GitBook
#
# GitBook is a command line tool (and Node.js library) for building beautiful
# books using GitHub/Git and Markdown (or AsciiDoc).
#
# You can publish and host book easily online using gitbook.com, a web-editor
# is also available.
#
# https://www.gitbook.com/
# https://github.com/GitbookIO/gitbook
npm install --global gitbook-cli

# gg
#
# Shortcuts for git commands
#
# https://github.com/qw3rtman/gg
npm install --global gitgoodies

# GitTorrent
#
# A decentralization of GitHub using BitTorrent and Bitcoin.
#
# GitTorrent is a peer-to-peer network of Git repositories being shared over
# BitTorrent.
#
# https://github.com/cjb/gittorrent
# http://blog.printf.net/articles/2015/05/29/announcing-gittorrent-a-decentralized-github/
# https://news.ycombinator.com/item?id=9625840
npm install --global gittorrent

# Grunt
#
# The JavaScript task runner.
#
# http://gruntjs.com/
npm install --global grunt-cli

# gulp
#
# The streaming build system.
#
# http://gulpjs.com/
npm install --global gulp

# harp
#
# The static web server with built-in preprocessing.
#
# Harp serves Jade, Markdown, EJS, CoffeeScript, Sass, LESS and Stylus as
# HTML, CSS & JavaScript—no configuration necessary.
#
# http://harpjs.com/
npm install --global harp

# jasmine
#
# Jasmine is a Behavior Driven Development testing framework for JavaScript.
# It does not rely on browsers, DOM, or any JavaScript framework. Thus it's
# suited for websites, Node.js projects, or anywhere that JavaScript can run.
#
# http://jasmine.github.io
# https://github.com/jasmine/jasmine
npm install --global jasmine

# JSHint, A Static Code Analysis Tool for JavaScript
#
# JSHint is a community-driven tool to detect errors and potential problems in
# JavaScript code.
#
# http://jshint.com/
# https://github.com/jshint/jshint
npm install --global jshint

# jspm CLI
#
# jspm is a package manager for the SystemJS universal module loader, built on
# top of the dynamic ES6 module loader
#
# http://jspm.io/
# https://github.com/jspm/jspm-cli
npm install --global jspm

# Karma CLI
#
# A simple tool that allows you to execute JavaScript code in multiple real
# browsers. Karma is not a testing framework, nor an assertion library. Karma
# just launches a HTTP server, and generates the test runner HTML file you
# probably already know from your favourite testing framework.
#
# http://karma-runner.github.io/
# https://github.com/karma-runner/karma/
# https://github.com/karma-runner/karma-cli
npm install --global karma-cli

# Learn You The Node.js
#
# An intro to Node.js via a set of self-guided workshops.
#
# NOTE: this is a good demonstration of a program built with workshopper:
# https://github.com/rvagg/workshopper
#
# https://github.com/rvagg/learnyounode
npm install --global learnyounode

# LiveScript
#
# LiveScript is a language which compiles to JavaScript. It has a
# straightforward mapping to JavaScript and allows you to write expressive
# code devoid of repetitive boilerplate. While LiveScript adds many features
# to assist in functional style programming, it also has many improvements for
# object oriented and imperative programming.
#
# LiveScript is a fork of Coco and an indirect descendant of CoffeeScript,
# with which it has much compatibility.
#
# http://livescript.net/
npm install --global livescript

# lodash-cli
#
# The lodash command-line interface for creating custom builds & precompiling
# templates.
#
# lodash
#
# A JavaScript utility library delivering consistency, modularity, performance,
# & extras.
#
# An alternative to Underscore.
#
# https://www.npmjs.com/package/lodash-cli
# https://github.com/lodash/lodash-cli
# https://lodash.com/
# https://github.com/lodash/lodash/
npm install --global lodash-cli

# mad
#
# mad(1) is a markdown driven manual page viewer, this makes manuals easier to
# write, reuse, and read.
#
# https://github.com/tj/mad
npm install --global mad

# Mocha
#
# Mocha is a feature-rich JavaScript test framework running on node.js and the
# browser, making asynchronous testing simple and fun. Mocha tests run
# serially, allowing for flexible and accurate reporting, while mapping
# uncaught exceptions to the correct test cases.
#
# http://mochajs.org/
# https://github.com/mochajs/mocha
npm install --global mocha

# nativefier
#
# Wrap any web page natively without even thinking, across Windows, OSX and
# Linux.
#
# https://github.com/jiahaog/nativefier
npm install --global nativefier

# nd
#
# a documentation viewer for node
#
# nd is a documentation viewer for npm packages. Similar to mad(1), it displays
# markdown documents in your terminal. Dissimilarly to mad, nd is written in
# javascript, and reads documentation out of npm module directories, not out
# of its own repository of pages.
#
# https://github.com/rf/nd
# https://www.npmjs.com/package/nd
npm install --global nd

# nshell
#
# scriptable shell written with node. A work-in-progress scriptable shell
# written with node (replacing bash, ksh, etc).
#
# https://www.npmjs.com/package/nshell
# https://github.com/tj/nshell
npm install --global nshell

# node-osa
#
# Node.js module for running Open Scripting Architecture code in OSX 10.10+
#
# OSA allows for advanced interaction between applications on OSX. In the past,
# it has largely been implemented using AppleScript. Beginning in OSX 10.10
# Yosemite, Apple has opened up this platform for development in Javascript.
#
# https://github.com/brandonhorst/node-osa
#
# Apple "JavaScript for Automation" Documentation:
# http://goo.gl/cigQfz
npm install --global osa

# Overcast
#
# A command line program designed to make it easy to spin up, configure, and
# interact with any number of machines over SSH.
#
# https://github.com/andrewchilds/overcast
# http://andrewchilds.github.io/overcast/
npm install --global overcast

# react-tools
#
# A set of complementary tools to React, including the JSX transformer.
#
# https://www.npmjs.com/package/react-tools
# https://github.com/facebook/react
# http://facebook.github.io/react/
npm install --global react-tools

# ShellJS - Unix shell commands for Node.js
#
# ShellJS is a portable (Windows/Linux/OS X) implementation of Unix shell
# commands on top of the Node.js API. You can use it to eliminate your shell
# script's dependency on Unix while still keeping its familiar and powerful
# commands. You can also install it globally so you can run it from outside
# Node projects.
#
# http://documentup.com/arturadib/shelljs
# https://github.com/arturadib/shelljs
npm install --global shelljs

# Shipit
#
# Universal automation and deployment tool written in JavaScript.
#
# https://github.com/shipitjs/shipit
npm install --global shipit-cli

# slap
#
# A Sublime-like terminal-based text editor that strives to make
# editing from the terminal easier
#
# https://github.com/slap-editor/slap
npm install --global slap

# surge
#
# Static web publishing for Front-End Developers
#
# Zero-bullshit, single–command, bring your own source control web publishing
# CDN. Yes, it's free.
#
# http://surge.sh/
# http://surge.sh/help/getting-started-with-surge
npm install --global surge

# tldr
#
# Simplified and community-driven man pages.
#
# http://tldr-pages.github.io/
# https://github.com/tldr-pages/tldr
# https://news.ycombinator.com/item?id=10797303
npm install --global tldr

# TypeScript
#
# TypeScript is a superset of JavaScript that adds optional types, classes,
# and modules and compiles to JavaScript.
#
# http://www.typescriptlang.org/
npm install --global typescript

# volo
#
# volo is a tool which lets you quickly create projects, add libraries, and
# automate common tasks using node and JavaScript. Create browser-based,
# front-end projects from project templates, and add dependencies by fetching
# them from GitHub. Once your project is set up, automate common tasks.
#
# http://volojs.org/
# https://github.com/volojs/volo
npm install --global volo

# vtop
#
# A graphical activity monitor for the command line.
#
# https://parall.ax/vtop
# https://github.com/MrRio/vtop
npm install --global vtop

# Yeoman
#
# A robust and opinionated set of tools, libraries, and a workflow that can
# help developers quickly build beautiful, compelling web apps.
#
# http://yeoman.io/
npm install --global yo
