#!/usr/bin/env bash
###############################################################################
# pip-packages
#
# Install script for pip-install Python 2 packages.
#
# http://www.pip-installer.org/
# https://pip.pypa.io
###############################################################################

###############################################################################
# Update
###############################################################################
pip install --upgrade setuptools
pip install --upgrade pip

###############################################################################
# Packages
###############################################################################

# 1pass
#
# A command line interface for 1Password
#
# https://pypi.python.org/pypi/1pass
# https://github.com/georgebrock/1pass
pip install --upgrade 1pass

# IPython
#
# A rich architecture for interactive computing.
#
# http://ipython.org/
pip install --upgrade "ipython[all]"

# mitmproxy
#
# An interactive console program that allows traffic flows to be intercepted,
# inspected, modified and replayed.
#
# http://mitmproxy.org/
pip install --upgrade mitmproxy

# neovim
#
# Python client for Neovim. Library for scripting Nvim processes through it's
# msgpack-rpc API.
#
# https://github.com/neovim/python-client
# https://pypi.python.org/pypi/neovim
# http://neovim.org/doc/user/nvim_python.html
pip install --upgrade neovim

# pep8 - Python style guide checker
#
# pep8 is a tool to check your Python code against some of the style
# conventions in PEP 8.
#
# https://github.com/jcrocholl/pep8
pip install --upgrade pep8

# pgcli
#
# Postgres CLI with autocompletion and syntax highlighting
#
# https://github.com/amjith/pgcli
pip install --upgrade pgcli

# pre-commit
#
# A framework for managing and maintaining multi-language pre-commit hooks.
#
# http://pre-commit.com/
# https://github.com/pre-commit/pre-commit
pip install --upgrade pre-commit

# python-Levenshtein
#
# The Levenshtein Python C extension module contains functions for fast
# computation of Levenshtein distance and string similarity
#
# https://github.com/ztane/python-Levenshtein/
# https://pypi.python.org/pypi/python-Levenshtein/
pip install --upgrade python-Levenshtein

# pythonpy
#
# python -c, with shorthand and tab completion
#
# https://github.com/Russell91/pythonpy
# https://github.com/Russell91/pythonpy/wiki/Python3
pip3 install -I --upgrade pythonpy

# virtualenv - Virtual Environments
#
# virtualenv is a tool to create isolated Python environments.
#
# https://virtualenv.pypa.io/en/latest/
# http://docs.python-guide.org/en/latest/dev/virtualenvs/
# https://pypi.python.org/pypi/virtualenv
pip install --upgrade virtualenv

# virtualenvwrapper
#
# virtualenvwrapper is a set of extensions to Ian Bicking’s virtualenv tool.
# The extensions include wrappers for creating and deleting virtual
# environments and otherwise managing your development workflow, making it
# easier to work on more than one project at a time without introducing
# conflicts in their dependencies.
#
# https://virtualenvwrapper.readthedocs.org/en/latest/
# https://bitbucket.org/dhellmann/virtualenvwrapper
# https://pypi.python.org/pypi/virtualenvwrapper/
pip install --upgrade virtualenvwrapper
