#!/usr/bin/env bash
###############################################################################
# pip3-packages
#
# Install script for pip3-install Python 3 packages.
#
# http://www.pip-installer.org/
# https://pip.pypa.io
###############################################################################

###############################################################################
# Update
###############################################################################

pip3 install --upgrade pip

# Default `pip` back to python 2
#
# Upgrading pip with pip3 makes `pip` default to pip3 rather than pip2.
# Running another upgrade using pip2 sets it back to pip2. Also checking for
# the presence of the pip2 command before running the pip2 upgrade.
if ( hash pip2 2>/dev/null ); then
  pip2 install --upgrade pip
fi

###############################################################################
# Packages
###############################################################################

# Mochi
#
# Dynamically typed functional programming language.
#
# https://github.com/i2y/mochi
pip3 install --upgrade mochi

