#!/usr/bin/env bash
###############################################################################
# pip3-packages
#
# Install script for pip3-install Python 3 packages.
#
# http://www.pip-installer.org/
# https://pip.pypa.io
###############################################################################

###############################################################################
# Update
###############################################################################

pip3 install --upgrade pip

# Default `pip` back to python 2
#
# Upgrading pip with pip3 makes `pip` default to pip3 rather than pip2.
# Running another upgrade using pip2 sets it back to pip2. Also checking for
# the presence of the pip2 command before running the pip2 upgrade.
if ( hash pip2 2>/dev/null ); then
  pip2 install --upgrade pip
fi

###############################################################################
# Packages
###############################################################################

# csvkit
#
# csvkit is a suite of utilities for converting to and working with CSV, the
# king of tabular file formats.
#
# https://github.com/onyxfish/csvkit
# https://robots.thoughtbot.com/csvkit-brings-the-unix-philosophy-to-csv
pip3 install --upgrade csvkit

# Hy
#
# Hy is a wonderful dialect of Lisp that’s embedded in Python.
#
# Since Hy transforms its Lisp code into the Python Abstract Syntax Tree, you
# have the whole beautiful world of Python at your fingertips, in Lisp form!
#
# https://github.com/hylang/hy
# http://hylang.org/
pip3 install --upgrade hy

# Mochi
#
# Dynamically typed functional programming language.
#
# https://github.com/i2y/mochi
pip3 install --upgrade mochi

# Rainbow Stream
#
# Terminal-based Twitter Client. Realtime tweetstream, compose, search,
# favorite … and much more fun directly from terminal.
#
# http://www.rainbowstream.org/
# https://github.com/DTVD/rainbowstream
pip3 install --upgrade rainbowstream

# Stellar
#
# Fast database snapshot and restore tool for development. Stellar allows you
# to quickly restore database when you are e.g. writing database migrations,
# switching branches or messing with SQL. PostgreSQL and MySQL are supported.
#
# https://github.com/fastmonkeys/stellar
pip3 install --upgrade stellar

# the xonsh shell
#
# xonsh is a Python-ish, BASHwards-compatible shell language and command
# prompt. The language is a superset of Python 3.4 with additional shell
# primitives that you are used to from BASH and IPython.
#
# http://xonsh.org/
# https://github.com/scopatz/xonsh
pip3 install --upgrade xonsh
