#!/usr/bin/env bash
###############################################################################
# vagrant-plugins
#
# https://docs.vagrantup.com/v2/plugins/
# https://github.com/mitchellh/vagrant/wiki/Available-Vagrant-Plugins
###############################################################################

# sahara
#
# plugin for vagrant that allows you manage a sandbox state
#
# https://github.com/jedi4ever/sahara
vagrant plugin install sahara

# vagrant-aws
#
# Use Vagrant to manage your EC2 and VPC instances.
#
# https://github.com/mitchellh/vagrant-aws
vagrant plugin install vagrant-aws

# Digital Ocean Vagrant Provider
#
# A Vagrant provider plugin that supports the management of Digital Ocean
# droplets (instances).
#
# https://github.com/smdahlen/vagrant-digitalocean
#
# NOTE: This fails to install in some cases. Setting `$ARCHFLAGS` to a
# temporary value as a workaround. More information:
# https://github.com/devopsgroup-io/vagrant-digitalocean/issues/232
_install_vagrant_digitalocean() {
  local _archflags_original="${ARCHFLAGS}"
  printf "⚠️  Temporarily setting \$ARCHFLAGS...\n"
  export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future
  vagrant plugin install vagrant-digitalocean
  export ARCHFLAGS="${_archflags_original}"
  printf "⚠️  \$ARCHFLAGS set to original value: '%s'\n" "${ARCHFLAGS}"
}
_install_vagrant_digitalocean

# vagrant-ghost
#
# This plugin adds an entry to your /etc/hosts file on the host system.
#
# On up, resume and reload commands, it tries to add the information, if its
# not already in your hosts file. If it needs to be added, you will be asked
# for an administrator password, since it uses sudo to edit the file.
#
# On halt, destroy, and suspend those entries will be removed again.
#
# https://github.com/10up/vagrant-ghost
vagrant plugin install vagrant-ghost

# vagrant-hostmanager
#
# A Vagrant plugin that manages the /etc/hosts file on guests within a
# multi-machine environment
#
# NOTE: alternatives include:
# - https://github.com/cogitatio/vagrant-hostsupdater
# - https://github.com/adrienthebo/vagrant-hosts
#
# https://github.com/smdahlen/vagrant-hostmanager
vagrant plugin install vagrant-hostmanager

# Vagrant::Hostsupdater
#
# This plugin adds an entry to your /etc/hosts file on the host system.
#
# https://github.com/cogitatio/vagrant-hostsupdater
#
# NOTE: alternatives include:
# - https://github.com/smdahlen/vagrant-hostmanager
# - https://github.com/adrienthebo/vagrant-hosts
#
# NOTE: this is included for full support of Varying Vagrant Vagrants:
# https://github.com/Varying-Vagrant-Vagrants/VVV
# Conflict have been encountered with it in the past with the CoreOS vagrant
# examples.
vagrant plugin install vagrant-hostsupdater

# vagrant-triggers
#
# Allow the definition of arbitrary scripts that will run on the host before
# and/or after Vagrant commands.
#
# https://github.com/emyl/vagrant-triggers
vagrant plugin install vagrant-triggers

# vagrant-vbguest
#
# vagrant-vbguest is a Vagrant plugin which automatically installs the host's
# VirtualBox Guest Additions on the guest system.
#
# https://github.com/dotless-de/vagrant-vbguest
vagrant plugin install vagrant-vbguest
