#!/usr/bin/env bash
###############################################################################
# vagrant-plugins
#
# https://docs.vagrantup.com/v2/plugins/
# https://github.com/mitchellh/vagrant/wiki/Available-Vagrant-Plugins
###############################################################################

# sahara
#
# plugin for vagrant that allows you manage a sandbox state
#
# https://github.com/jedi4ever/sahara
vagrant plugin install sahara

# vagrant-aws
#
# Use Vagrant to manage your EC2 and VPC instances.
#
# https://github.com/mitchellh/vagrant-aws
vagrant plugin install vagrant-aws

# Digital Ocean Vagrant Provider
#
# A Vagrant provider plugin that supports the management of Digital Ocean
# droplets (instances).
#
# https://github.com/smdahlen/vagrant-digitalocean
vagrant plugin install vagrant-digitalocean

# vagrant-hostmanager
#
# A Vagrant plugin that manages the /etc/hosts file on guests within a
# multi-machine environment
#
# NOTE: alternatives include:
# - https://github.com/cogitatio/vagrant-hostsupdater
# - https://github.com/adrienthebo/vagrant-hosts
#
# https://github.com/smdahlen/vagrant-hostmanager
vagrant plugin install vagrant-hostmanager
