#!/usr/bin/env bash
###############################################################################
# workshoppers
#
# Workshop application built with workshopper.
#
# Workshopper
#
# > A terminal workshop runner framework
#
# https://github.com/rvagg/workshopper
###############################################################################

# Functional JavaScript
#
# Learn fundamental functional programming features of JavaScript in vanilla
# ES5.
#
# https://github.com/timoxley/functional-javascript-workshop
npm install -g functional-javascript-workshop

# javascripting
#
# Learn the basics of JavaScript. No previous programming experience required.
npm install -g javascripting

# Learn You The Node.js
#
# An intro to Node.js via a set of self-guided workshops.
#
# https://github.com/rvagg/learnyounode
npm install -g learnyounode
