#!/usr/bin/env bash
###############################################################################
# workshoppers
#
# Workshop application built with workshopper.
#
# Workshopper
#
# > A terminal workshop runner framework
#
# https://github.com/rvagg/workshopper
###############################################################################

# Async You
#
# Learn to use the async package.
#
# https://github.com/bulkan/async-you
npm install -g async-you

# Count to 6
#
# Learn how to use some features from ES6, the next version of JavaScript.
#
# https://github.com/domenic/count-to-6
npm install -g count-to-6

# expressworks
#
# Learn the basics of the Express.js framework.
#
# Learn Express.js from the author of one of the best books on Express.js—Pro
# Express.js—workshop to teach you basics of Express.js.
#
# https://github.com/azat-co/expressworks
npm install -g expressworks

# Functional JavaScript
#
# Learn fundamental functional programming features of JavaScript in vanilla
# ES5.
#
# https://github.com/timoxley/functional-javascript-workshop
npm install -g functional-javascript-workshop

# javascripting
#
# Learn the basics of JavaScript. No previous programming experience required.
npm install -g javascripting

# Kick Off Koa
#
# Getting started with Koa, the next generation web framework for Node.js
#
# https://github.com/koajs/kick-off-koa
npm install -g kick-off-koa

# Learn You The Node.js
#
# An intro to Node.js via a set of self-guided workshops.
#
# https://github.com/rvagg/learnyounode
npm install -g learnyounode

# Promise It Won't Hurt
#
# Learn to use promises in JavaScript to handle async operations.
#
# https://github.com/stevekane/promise-it-wont-hurt
npm install -g promise-it-wont-hurt
