#!/usr/bin/env bash
###############################################################################
# Bootstrap dotfiles on a fresh OS X install
###############################################################################

###############################################################################
# Platform Check
###############################################################################

# Skip unless OS X
if [[ ! "${OSTYPE}" =~ ^darwin ]]
then
  printf "OS X bootstrapping is only supported on OS X\nSkipping...\n"
  exit 0
fi

###############################################################################
# Bootstrap
###############################################################################

if [[ ! -e "${HOME}/bin" ]]
then
  mkdir "${HOME}/bin"
fi

export BINDLEPATH="${HOME}/.dotfiles" && \
  cd "${BINDLEPATH}" && \
  git submodule init && \
  git submodule update --init --recursive

# Finalize Janus setup.
if hash "rake" 2>/dev/null
then
  cd "${BINDLEPATH}/home/.vim/"
  rake || _die printf "Janus bootstrap failed."
  cd "${BINDLEPATH}"
else
  printf "rake not installed. Janus not completely initialized."
fi

printf "\
All done!

The configuration has been initialized at the following location:

~/.dotfiles

So far, your existing configuration has not been changed. Use the \`bindle\`
tool to experiment with linking files into your environment. \`bindle\`
commands can be discovered by running \`bindle help\`.
"
