#!/usr/bin/env bash
###############################################################################
# Bootstrap dotfiles on a fresh OS X install
###############################################################################

###############################################################################
# Platform Check
###############################################################################

# Skip unless OS X
if [[ ! "${OSTYPE}" =~ ^darwin ]]
then
  printf "OS X bootstrapping is only supported on OS X\nSkipping...\n"
  exit 0
fi

###############################################################################
# Bootstrap
###############################################################################

if [[ ! -e "${HOME}/bin" ]]
then
  mkdir "${HOME}/bin"
fi

export BINDLEPATH="${HOME}/.dotfiles" && \
  cd "${BINDLEPATH}" && \
  git submodule init && \
  git submodule update --init --recursive

# Bootstrap janus
"${BINDLEPATH}/home/.vim/bootstrap.sh"
