#!/usr/bin/env bash
#
# Bootstrap dotfiles on a fresh ubuntu install

export DOTSPATH="$HOME/.dotfiles"

"$DOTSPATH"/script/install/apt-packages

mkdir ~/bin &&
cp ~/.ssh/* ~/.dotfiles/.ssh/ && \
cd "$DOTSPATH" && \
git submodule init && git submodule update --init --recursive && \
./bin/dots link --overwrite --with-backup &&
./bin/dots bin link

$(which zsh) --login
