#!/usr/bin/env bash
#
# Bootstrap dotfiles on a fresh ubuntu install

###############################################################################
# Platform Check
###############################################################################

# Skip unless ubuntu
if [[ ! "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]]; then
  printf "apt-packages is only supported on Ubuntu.\nExiting...\n"
  exit 1
fi

###############################################################################
# Bootstrap
###############################################################################

export DOTSPATH="$HOME/.dotfiles"

"$DOTSPATH"/script/install/apt-packages

[ ! -e "$HOME"/bin ] && mkdir "$HOME"/bin && \
cp "$HOME"/.ssh/* "$HOME"/.dotfiles/home/.ssh/ && \
cd "$DOTSPATH" && \
git submodule init && git submodule update --init --recursive && \
./bin/dots link --overwrite --with-backup &&
./bin/dots bin link

$(which zsh) --login

chsh -s "$(which zsh)"
